<?php
return [
    16 => [ // TypeScript
        'quizzes' => [
            [
                'question' => 'Какой из следующих типов является примитивным в TypeScript?',
                'options' => ['object', 'string', 'Array', 'Function'],
                'correct' => 1,
                'explanation' => 'string — это примитивный тип данных в TypeScript. object, Array и Function являются ссылочными типами.',
            ],
            [
                'question' => 'Что будет результатом typeof null в TypeScript?',
                'options' => ['"null"', '"object"', '"undefined"', '"boolean"'],
                'correct' => 1,
                'explanation' => 'Это известный баг в JavaScript, который TypeScript наследует: typeof null возвращает "object".',
            ],
            [
                'question' => 'Как правильно объявить интерфейс в TypeScript?',
                'options' => ['interface User {}', 'class User {}', 'type User = {}', 'struct User {}'],
                'correct' => 0,
                'explanation' => 'Интерфейсы объявляются с помощью ключевого слова interface.',
            ],
            [
                'question' => 'Что произойдёт, если интерфейс не определяет свойство, которое присутствует в объекте?',
                'options' => ['Ошибка компиляции', 'Свойство будет проигнорировано', 'Свойство станет опциональным', 'Зависит от настроек tsconfig'],
                'correct' => 1,
                'explanation' => 'TypeScript проверяет, что объект соответствует интерфейсу, но лишние свойства допускаются.',
            ],
            [
                'question' => 'Чем type alias отличается от interface?',
                'options' => ['Только синтаксисом', 'Type alias может описывать union типы', 'Interface быстрее', 'Type alias поддерживает наследование'],
                'correct' => 1,
                'explanation' => 'Type alias может представлять любые типы, включая union, intersection и примитивы.',
            ],
            [
                'question' => 'Как объявить переменную, которая может быть строкой или числом?',
                'options' => ['let value: string | number', 'let value: string, number', 'let value: string or number', 'let value: [string, number]'],
                'correct' => 0,
                'explanation' => 'Union types объединяются с помощью символа вертикальной черты (|).',
            ],
            [
                'question' => 'Что такое intersection type в TypeScript?',
                'options' => ['Тип пересечения двух типов', 'Тип с общими свойствами', 'Тип из одного из нескольких', 'Тип, создающий новый объект'],
                'correct' => 1,
                'explanation' => 'Intersection type (A & B) создаёт тип со всеми свойствами из обоих типов.',
            ],
            [
                'question' => 'Как объявить generic функцию?',
                'options' => ['function identity&lt;T&gt;(arg: T): T', 'function identity(arg: T): T', 'function identity(T arg): T', 'function&lt;T&gt; identity(arg: T): T'],
                'correct' => 0,
                'explanation' => 'Generic параметры указываются в угловых скобках после имени функции.',
            ],
            [
                'question' => 'Что такое constraints в generics?',
                'options' => ['Ограничения на тип', 'Ограничения на параметры', 'Ограничения на возвращаемый тип', 'Ограничения на имя'],
                'correct' => 0,
                'explanation' => 'Constraints ограничивают типы с помощью ключевого слова extends.',
            ],
            [
                'question' => 'Что делает Partial&lt;T&gt;?',
                'options' => ['Делает все свойства обязательными', 'Делает все свойства опциональными', 'Делает readonly', 'Удаляет свойства'],
                'correct' => 1,
                'explanation' => 'Partial&lt;T&gt; создаёт тип, где все свойства становятся опциональными.',
            ],
            [
                'question' => 'Какой utility type выбирает подмножество свойств?',
                'options' => ['Omit&lt;T, K&gt;', 'Pick&lt;T, K&gt;', 'Record&lt;K, T&gt;', 'Required&lt;T&gt;'],
                'correct' => 1,
                'explanation' => 'Pick&lt;T, K&gt; выбирает только указанные свойства K из типа T.',
            ],
            [
                'question' => 'Что делает Omit&lt;T, K&gt;?',
                'options' => ['Добавляет свойства', 'Удаляет свойства K из типа T', 'Делает обязательными', 'Преобразует в массив'],
                'correct' => 1,
                'explanation' => 'Omit&lt;T, K&gt; создаёт тип, исключая указанные свойства K.',
            ],
            [
                'question' => 'Что такое Record&lt;K, T&gt;?',
                'options' => ['Тип записи с ключами K и значениями T', 'Массив значений T', 'Кортеж из K элементов', 'Функция, возвращающая T'],
                'correct' => 0,
                'explanation' => 'Record&lt;K, T&gt; создаёт тип объекта с ключами K и значениями T.',
            ],
            [
                'question' => 'Как объявить enum в TypeScript?',
                'options' => ['enum Direction { Up, Down, Left, Right }', 'enum Direction = { Up, Down }', 'const enum Direction { Up, Down }', 'type Direction = "Up" | "Down"'],
                'correct' => 0,
                'explanation' => 'Enum объявляется с помощью ключевого слова enum.',
            ],
            [
                'question' => 'Что такое numeric enum?',
                'options' => ['Enum со строковыми значениями', 'Enum с числовыми значениями', 'Enum с автонумерацией', 'Enum без значений'],
                'correct' => 2,
                'explanation' => 'Numeric enum автоматически нумерует значения, начиная с 0.',
            ],
            [
                'question' => 'Как объявить tuple в TypeScript?',
                'options' => ['let x: [string, number]', 'let x: array&lt;string, number&gt;', 'let x: {string, number}', 'let x: (string | number)[]'],
                'correct' => 0,
                'explanation' => 'Tuple объявляется как массив с фиксированными типами элементов.',
            ],
            [
                'question' => 'Чем tuple отличается от массива?',
                'options' => ['Tuple имеет фиксированную длину и типы', 'Tuple быстрее', 'Tuple только строки', 'Ничем не отличается'],
                'correct' => 0,
                'explanation' => 'Tuple имеет фиксированную длину и типы для каждого элемента.',
            ],
            [
                'question' => 'Как сделать свойство readonly?',
                'options' => ['readonly prop: string', 'const prop: string', 'immutable prop: string', 'frozen prop: string'],
                'correct' => 0,
                'explanation' => 'Ключевое слово readonly делает свойство доступным только для чтения.',
            ],
            [
                'question' => 'Какой модификатор доступа по умолчанию?',
                'options' => ['private', 'protected', 'public', 'internal'],
                'correct' => 2,
                'explanation' => 'По умолчанию все свойства и методы имеют модификатор public.',
            ],
            [
                'question' => 'Что означает protected?',
                'options' => ['Доступно из любого места', 'Только внутри класса', 'Внутри класса и наследников', 'Только во время выполнения'],
                'correct' => 2,
                'explanation' => 'Protected члены доступны внутри класса и классов-наследников.',
            ],
            [
                'question' => 'Что такое декораторы в TypeScript?',
                'options' => ['Функции для модификации классов/свойств', 'Комментарии с особым синтаксисом', 'Стандартная функциональность JS', 'Способ комментирования'],
                'correct' => 0,
                'explanation' => 'Декораторы — специальные объявления для модификации классов и методов.',
            ],
            [
                'question' => 'Какой файл описывает типы JS-библиотек?',
                'options' => ['types.d.ts', 'types.js', 'types.ts', 'types.json'],
                'correct' => 0,
                'explanation' => 'Файлы деклараций (.d.ts) описывают типы JS-библиотек.',
            ],
            [
                'question' => 'Какой файл конфигурации TypeScript?',
                'options' => ['tsconfig.json', 'typescript.config.js', '.tsconfig', 'tsc.json'],
                'correct' => 0,
                'explanation' => 'tsconfig.json — основной файл конфигурации TypeScript.',
            ],
            [
                'question' => 'Что включает strict mode?',
                'options' => ['Только проверку типов', 'Строгую типизацию и дополнительные проверки', 'Только синтаксис', 'Только импорты'],
                'correct' => 1,
                'explanation' => 'Strict mode включает множество строгих проверок типов.',
            ],
            [
                'question' => 'Какой синтаксис type assertion?',
                'options' => ['value as Type', 'value: Type', '&lt;Type&gt;value', 'value instanceof Type'],
                'correct' => 0,
                'explanation' => 'Type assertion используется с ключевым словом as или угловыми скобками.',
            ],
            [
                'question' => 'Что такое тип never?',
                'options' => ['Тип для значений, которые никогда не возвращаются', 'Тип для undefined', 'Тип для null', 'Тип для ошибок'],
                'correct' => 0,
                'explanation' => 'Never表示 функции, которые никогда не завершаются нормально.',
            ],
            [
                'question' => 'Чем unknown отличается от any?',
                'options' => ['Unknown более строгий', 'Any более строгий', 'Ничем не отличаются', 'Unknown нельзя использовать'],
                'correct' => 0,
                'explanation' => 'Unknown требует проверки типа перед использованием.',
            ],
            [
                'question' => 'Что такое mapped type?',
                'options' => ['Тип, созданный перебором свойств', 'Тип массива', 'Тип функции', 'Тип класса'],
                'correct' => 0,
                'explanation' => 'Mapped type итерирует по свойствам существующего типа.',
            ],
            [
                'question' => 'Как создать readonly версию всех свойств?',
                'options' => ['Readonly&lt;T&gt;', 'ReadonlyArray&lt;T&gt;', 'Mutable&lt;T&gt;', 'Writable&lt;T&gt;'],
                'correct' => 0,
                'explanation' => 'Readonly&lt;T&gt; делает все свойства только для чтения.',
            ],
            [
                'question' => 'Что такое type narrowing?',
                'options' => ['Сужение типа с помощью условий', 'Расширение типа', 'Удаление типа', 'Конвертация типа'],
                'correct' => 0,
                'explanation' => 'Type narrowing уточняет тип с помощью условных проверок.',
            ],
            [
                'question' => 'Какой тип возвращает функция без возвращаемого значения?',
                'options' => ['void', 'undefined', 'null', 'never'],
                'correct' => 0,
                'explanation' => 'Void указывает, что функция не возвращает значения.',
            ],
            [
                'question' => 'Что такое function overloading?',
                'options' => ['Несколько объявлений функции с разными параметрами', 'Одна функция с разной логикой', 'Рекурсивная функция', 'Анонимная функция'],
                'correct' => 0,
                'explanation' => 'Function overloading позволяет определить несколько сигнатур для одной функции.',
            ],
            [
                'question' => 'Как работает optional chaining (?.)?',
                'options' => ['Возвращает undefined, если свойство не существует', 'Бросает ошибку', 'Возвращает null', 'Создаёт новое свойство'],
                'correct' => 0,
                'explanation' => 'Optional chaining безопасно обращается к вложенным свойствам.',
            ],
            [
                'question' => 'Что такое type guard?',
                'options' => ['Функция для проверки типа во время выполнения', 'Комментарий для типов', 'Специальная переменная', 'Интерфейс для типов'],
                'correct' => 0,
                'explanation' => 'Type guard проверяет тип во время выполнения.',
            ],
            [
                'question' => 'Как объявить abstract class?',
                'options' => ['abstract class MyClass {}', 'class abstract MyClass {}', 'abstract MyClass {}', 'MyClass abstract {}'],
                'correct' => 0,
                'explanation' => 'Abstract class объявляется с ключевым словом abstract перед class.',
            ],
            [
                'question' => 'Что такое conditional type?',
                'options' => ['Тип, зависящий от условия', 'Тип всегда true', 'Тип всегда false', 'Тип без условия'],
                'correct' => 0,
                'explanation' => 'Conditional type создаёт тип на основе условия T extends U ? X : Y.',
            ],
            [
                'question' => 'Какой тип代表 any value?',
                'options' => ['unknown', 'any', 'never', 'void'],
                'correct' => 0,
                'explanation' => 'Unknown表示 безопасный аналог any.',
            ],
            [
                'question' => 'Какой тип代表 any function?',
                'options' => ['Function', '() => void', 'any', 'unknown'],
                'correct' => 0,
                'explanation' => 'Function — тип для любой функции.',
            ],
            [
                'question' => 'Что такое const assertion?',
                'options' => ['as const — буквальное значение типа', 'const переменная', 'Константа', 'readonly массив'],
                'correct' => 0,
                'explanation' => 'As const делает литералы максимально конкретными типами.',
            ],
            [
                'question' => 'Как работает type compatibility?',
                'options' => ['Структурная типизация', 'Именная типизация', 'Номинальная типизация', 'Ранняя типизация'],
                'correct' => 0,
                'explanation' => 'TypeScript использует структурную типизацию.',
            ],
        ],
        'practices' => [
            ['title' => 'Создание интерфейса и типа', 'instructions' => 'Создайте интерфейс User с полями name, email, age. Создайте тип UserRole как union строк admin | user | guest. Используйте интерфейс в функции.', 'starter_code' => "interface User {\n  name: string;\n  email: string;\n  age: number;\n}\n\ntype UserRole = 'admin' | 'user' | 'guest';\n\nfunction greetUser(user: User): string {\n  // ваш код\n}", 'solution_code' => "interface User {\n  name: string;\n  email: string;\n  age: number;\n}\n\ntype UserRole = 'admin' | 'user' | 'guest';\n\nfunction greetUser(user: User): string {\n  return `Привет, \${user.name}! Тебе \${user.age} лет.`;\n}\n\nconst admin: User = { name: 'Админ', email: 'admin@test.com', age: 30 };\nconsole.log(greetUser(admin));", 'tests' => [['input' => 'greetUser({name:"Анна",email:"a@b.com",age:25})', 'expected' => 'Привет, Анна! Тебе 25 лет.', 'description' => 'Функция корректно форматирует строку']]],
            ['title' => 'Дженерики и utility types', 'instructions' => 'Создайте泛型 функцию wrapValue<T>, которая оборачивает значение в объект {value: T, timestamp: number}. Используйте Partial<T> для функции updateUser.', 'starter_code' => "function wrapValue<T>(value: T): { value: T; timestamp: number } {\n  // ваш код\n}\n\nfunction updateUser<T>(base: T, changes: Partial<T>): T {\n  // ваш код\n}", 'solution_code' => "function wrapValue<T>(value: T): { value: T; timestamp: number } {\n  return { value, timestamp: Date.now() };\n}\n\nfunction updateUser<T>(base: T, changes: Partial<T>): T {\n  return { ...base, ...changes };\n}\n\nconst wrapped = wrapValue('hello');\nconsole.log(wrapped);\n\nconst user = { name: 'Tom', age: 25, role: 'user' as const };\nconst updated = updateUser(user, { age: 26 });\nconsole.log(updated);", 'tests' => [['input' => 'wrapValue(42)', 'expected' => '{value: 42, timestamp: ...}', 'description' => 'Обёртка создаётся корректно']]],
            ['title' => 'Классы с модификаторами доступа', 'instructions' => 'Создайте класс BankAccount с приватным балансом, публичными методами deposit, getBalance. Добавьте readonly поле id.', 'starter_code' => "class BankAccount {\n  // ваш код\n}", 'solution_code' => "class BankAccount {\n  readonly id: number;\n  private balance: number;\n\n  constructor(id: number, initialBalance: number = 0) {\n    this.id = id;\n    this.balance = initialBalance;\n  }\n\n  deposit(amount: number): void {\n    if (amount > 0) this.balance += amount;\n  }\n\n  getBalance(): number {\n    return this.balance;\n  }\n}\n\nconst account = new BankAccount(1, 1000);\naccount.deposit(500);\nconsole.log(account.getBalance()); // 1500", 'tests' => [['input' => 'new BankAccount(1,100).deposit(50)', 'expected' => 'balance = 150', 'description' => 'Баланс увеличивается']]],
        ],
        'exam' => [
            'title' => 'Экзамен по TypeScript',
            'time' => 60,
            'pass' => 70,
            'bank' => [
                ['question' => 'Какой тип является примитивным?', 'options' => ['string', 'object', 'Array', 'Function'], 'correct' => 0, 'explanation' => 'string — примитивный тип.'],
                ['question' => 'Что делает Partial<T>?', 'options' => ['Делает все свойства опциональными', 'Делает readonly', 'Удаляет свойства', 'Делает обязательными'], 'correct' => 0, 'explanation' => 'Partial делает свойства опциональными.'],
                ['question' => 'Как объявить enum?', 'options' => ['enum Direction { Up, Down }', 'const enum = {}', 'type Direction = {}', 'class Direction {}'], 'correct' => 0, 'explanation' => 'enum — ключевое слово для перечислений.'],
                ['question' => 'Чем unknown отличается от any?', 'options' => ['unknown более строгий', 'any более строгий', 'Ничем', 'Unknown нельзя'], 'correct' => 0, 'explanation' => 'unknown требует проверки типа.'],
                ['question' => 'Как объявить tuple?', 'options' => ['let x: [string, number]', 'let x: array<string>', 'let x: {string, number}', 'let x: (string | number)[]'], 'correct' => 0, 'explanation' => 'Tuple — массив с фиксированными типами.'],
                ['question' => 'Что такое generic constraints?', 'options' => ['Ограничения типов через extends', 'Ограничения параметров', 'Ограничения функций', 'Ограничения классов'], 'correct' => 0, 'explanation' => 'Constraints ограничивают типы с помощью extends.'],
                ['question' => 'Какой модификатор по умолчанию?', 'options' => ['public', 'private', 'protected', 'internal'], 'correct' => 0, 'explanation' => 'По умолчанию public.'],
                ['question' => 'Что такое conditional type?', 'options' => ['T extends U ? X : Y', 'if (T) X else Y', 'type T = X | Y', 'T == X ? Y : Z'], 'correct' => 0, 'explanation' => 'Conditional type: T extends U ? X : Y.'],
                ['question' => 'Что делает Omit<T, K>?', 'options' => ['Удаляет свойства K из типа T', 'Добавляет свойства', 'Делает readonly', 'Преобразует в массив'], 'correct' => 0, 'explanation' => 'Omit исключает указанные свойства.'],
                ['question' => 'Как создать readonly массив?', 'options' => ['ReadonlyArray<T>', 'readonly T[]', 'const T[]', 'immutable T[]'], 'correct' => 0, 'explanation' => 'ReadonlyArray<T> или readonly T[].'],
                ['question' => 'Что такое function overloading?', 'options' => ['Несколько сигнатур для одной функции', 'Рекурсия', 'Анонимная функция', 'Замыкание'], 'correct' => 0, 'explanation' => 'Overloading — несколько сигнатур.'],
                ['question' => 'Как работает optional chaining?', 'options' => ['Возвращает undefined если нет свойства', 'Бросает ошибку', 'Возвращает null', 'Создаёт свойство'], 'correct' => 0, 'explanation' => '?. безопасно обращается к свойствам.'],
                ['question' => 'Что такое mapped type?', 'options' => ['Тип созданный перебором свойств', 'Тип массива', 'Тип функции', 'Тип класса'], 'correct' => 0, 'explanation' => 'Mapped type итерирует по свойствам.'],
                ['question' => 'Какой тип для функции без возврата?', 'options' => ['void', 'undefined', 'null', 'never'], 'correct' => 0, 'explanation' => 'void — функция ничего не возвращает.'],
                ['question' => 'Что такое type narrowing?', 'options' => ['Сужение типа через условия', 'Расширение типа', 'Удаление типа', 'Конвертация типа'], 'correct' => 0, 'explanation' => 'Type narrowing уточняет тип проверками.'],
            ],
        ],
    ],

    17 => [ // Docker
        'quizzes' => [
            ['question' => 'Что такое Docker image?', 'options' => ['Шаблон для контейнера', 'Контейнер', 'Скрипт', 'Сеть'], 'correct' => 0, 'explanation' => 'Образ — шаблон.'],
            ['question' => 'Что делает docker run?', 'options' => ['Запускает контейнер', 'Создаёт образ', 'Удаляет контейнер', 'Останавливает контейнер'], 'correct' => 0, 'explanation' => 'Запускает контейнер.'],
            ['question' => 'Что такое Dockerfile?', 'options' => ['Инструкции для сборки образа', 'Конфигурация сети', 'Скрипт деплоя', 'Логи контейнера'], 'correct' => 0, 'explanation' => 'Инструкции для сборки.'],
            ['question' => 'Какой образ самый маленький?', 'options' => ['Alpine', 'Ubuntu', 'Debian', 'CentOS'], 'correct' => 0, 'explanation' => 'Alpine минимальный.'],
            ['question' => 'Что такое Docker Compose?', 'options' => ['Управление мульти-контейнерными приложениями', 'Один контейнер', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Мульти-контейнерные приложения.'],
            ['question' => 'Что такое volume в Docker?', 'options' => ['Постоянное хранилище данных', 'Сеть', 'Контейнер', 'Образ'], 'correct' => 0, 'explanation' => 'Постоянное хранилище.'],
            ['question' => 'Какойetwork bridge по умолчанию?', 'options' => ['Связывает контейнеры', 'Хост', 'Overlay', 'None'], 'correct' => 0, 'explanation' => 'Bridge связывает контейнеры.'],
            ['question' => 'Что такое multi-stage build?', 'options' => ['Этапы сборки для уменьшения размера', 'Много контейнеров', 'Много сетей', 'Много томов'], 'correct' => 0, 'explanation' => 'Уменьшение размера образа.'],
        ],
        'practices' => [
            ['title' => 'Dockerfile для Node.js', 'instructions' => 'Напишите Dockerfile для Node.js приложения с multi-stage build. Используйте Alpine образы.', 'starter_code' => "# Stage 1: build\nFROM node:18-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\n# ваш код\n\n# Stage 2: production\nFROM node:18-alpine\n# ваш код", 'solution_code' => "# Stage 1: build\nFROM node:18-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nRUN npm run build\n\n# Stage 2: production\nFROM node:18-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nEXPOSE 3000\nCMD [\"node\", \"dist/index.js\"]", 'tests' => [['input' => 'docker build -t myapp .', 'expected' => 'Образ собран', 'description' => 'Dockerfile валиден']]],
            ['title' => 'Docker Compose для приложения с БД', 'instructions' => 'Создайте docker-compose.yml с двумя сервисами: web (Node.js) и db (PostgreSQL). Настройте зависимости и сети.', 'starter_code' => "version: '3.8'\nservices:\n  web:\n    # ваш код\n  db:\n    # ваш код", 'solution_code' => "version: '3.8'\nservices:\n  web:\n    build: .\n    ports:\n      - '3000:3000'\n    environment:\n      - DATABASE_URL=postgresql://user:pass@db:5432/mydb\n    depends_on:\n      - db\n    networks:\n      - app-network\n  db:\n    image: postgres:15-alpine\n    environment:\n      - POSTGRES_USER=user\n      - POSTGRES_PASSWORD=pass\n      - POSTGRES_DB=mydb\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    networks:\n      - app-network\nvolumes:\n  pgdata:\nnetworks:\n  app-network:", 'tests' => [['input' => 'docker-compose config', 'expected' => 'Конфигурация валидна', 'description' => 'Compose файл валиден']]],
            ['title' => 'Multi-stage сборка Go приложения', 'instructions' => 'Создайте multi-stage Dockerfile для Go приложения. Финальный образ должен быть минимум 10MB.', 'starter_code' => "# Build stage\nFROM golang:1.21 AS builder\nWORKDIR /app\nCOPY . .\n# ваш код\n\n# Final stage\nFROM scratch\n# ваш код", 'solution_code' => "# Build stage\nFROM golang:1.21 AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o main .\n\n# Final stage\nFROM scratch\nCOPY --from=builder /app/main /main\nEXPOSE 8080\nENTRYPOINT [\"/main\"]", 'tests' => [['input' => 'docker build -t goapp .', 'expected' => 'Образ собран', 'description' => 'Multi-stage работает']]],
        ],
        'exam' => [
            'title' => 'Экзамен по Docker',
            'time' => 60,
            'pass' => 70,
            'bank' => [
                ['question' => 'Что такое Docker image?', 'options' => ['Шаблон для контейнера', 'Контейнер', 'Скрипт', 'Сеть'], 'correct' => 0, 'explanation' => 'Образ — шаблон.'],
                ['question' => 'Что делает docker run?', 'options' => ['Запускает контейнер', 'Создаёт образ', 'Удаляет контейнер', 'Останавливает контейнер'], 'correct' => 0, 'explanation' => 'Запускает контейнер.'],
                ['question' => 'Что такое Dockerfile?', 'options' => ['Инструкции для сборки образа', 'Конфигурация сети', 'Скрипт деплоя', 'Логи контейнера'], 'correct' => 0, 'explanation' => 'Инструкции для сборки.'],
                ['question' => 'Какой образ самый маленький?', 'options' => ['Alpine', 'Ubuntu', 'Debian', 'CentOS'], 'correct' => 0, 'explanation' => 'Alpine минимальный.'],
                ['question' => 'Что такое Docker Compose?', 'options' => ['Управление мульти-контейнерными приложениями', 'Один контейнер', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Мульти-контейнерные приложения.'],
                ['question' => 'Что такое volume в Docker?', 'options' => ['Постоянное хранилище данных', 'Сеть', 'Контейнер', 'Образ'], 'correct' => 0, 'explanation' => 'Постоянное хранилище.'],
                ['question' => 'Какой bridge по умолчанию?', 'options' => ['Связывает контейнеры', 'Хост', 'Overlay', 'None'], 'correct' => 0, 'explanation' => 'Bridge связывает контейнеры.'],
                ['question' => 'Что такое multi-stage build?', 'options' => ['Этапы сборки для уменьшения размера', 'Много контейнеров', 'Много сетей', 'Много томов'], 'correct' => 0, 'explanation' => 'Уменьшение размера образа.'],
                ['question' => 'Как удалить контейнер?', 'options' => ['docker rm', 'docker delete', 'docker remove', 'docker destroy'], 'correct' => 0, 'explanation' => 'docker rm.'],
                ['question' => 'Как остановить контейнер?', 'options' => ['docker stop', 'docker pause', 'docker halt', 'docker end'], 'correct' => 0, 'explanation' => 'docker stop.'],
                ['question' => 'Как посмотреть логи?', 'options' => ['docker logs', 'docker output', 'docker show', 'docker view'], 'correct' => 0, 'explanation' => 'docker logs.'],
                ['question' => 'Что такое Docker network?', 'options' => ['Связь между контейнерами', 'Файловая система', 'Хранилище', 'Registry'], 'correct' => 0, 'explanation' => 'Сеть для контейнеров.'],
                ['question' => 'Какой тип сети bridge?', 'options' => ['Связывает контейнеры на одной машине', 'Между машинами', 'Только входящий', 'Нет сети'], 'correct' => 0, 'explanation' => 'Bridge — локальная сеть.'],
                ['question' => 'Что такое overlay сеть?', 'options' => ['Сеть между хостами', 'Локальная сеть', 'Только для контейнеров', 'Для Registry'], 'correct' => 0, 'explanation' => 'Overlay — межхостовая сеть.'],
                ['question' => 'Как войти в контейнер?', 'options' => ['docker exec -it', 'docker enter', 'docker attach', 'docker login'], 'correct' => 0, 'explanation' => 'docker exec -it.'],
            ],
        ],
    ],

    18 => [ // Kubernetes
        'quizzes' => [
            ['question' => 'Какой компонент хранит состояние кластера?', 'options' => ['etcd', 'API Server', 'Scheduler', 'Controller Manager'], 'correct' => 0, 'explanation' => 'etcd — распределенное хранилище состояния кластера.'],
            ['question' => 'Что такое Pod?', 'options' => ['Минимальная единица развертывания', 'Контейнер', 'Нода', 'Сеть'], 'correct' => 0, 'explanation' => 'Pod — минимальный объект для запуска контейнеров.'],
            ['question' => 'Какой объект поддерживает реплики?', 'options' => ['ReplicaSet', 'Deployment', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'ReplicaSet поддерживает количество реплик Pod.'],
            ['question' => 'Какой тип Service внутренний?', 'options' => ['ClusterIP', 'NodePort', 'LoadBalancer', 'ExternalName'], 'correct' => 0, 'explanation' => 'ClusterIP обеспечивает внутренний доступ в кластере.'],
            ['question' => 'Для чего Ingress?', 'options' => ['HTTP маршрутизация', 'Сеть', 'Хранилище', 'Мониторинг'], 'correct' => 0, 'explanation' => 'Ingress управляет HTTP маршрутизацией и TLS.'],
            ['question' => 'Чем Secrets отличаются от ConfigMaps?', 'options' => ['Для чувствительных данных', 'Быстрее', 'Больше', 'Другой формат'], 'correct' => 0, 'explanation' => 'Secrets предназначены для паролей, токенов и ключей.'],
            ['question' => 'Что такое Persistent Volume?', 'options' => ['Абстракция хранилища', 'Контейнер', 'Pod', 'Service'], 'correct' => 0, 'explanation' => 'PV — абстракция физического хранилища.'],
            ['question' => 'Для чего StatefulSets?', 'options' => ['Для stateful приложений', 'Для Stateless', 'Для маршрутизации', 'Для мониторинга'], 'correct' => 0, 'explanation' => 'StatefulSets для БД и приложений с состоянием.'],
            ['question' => 'Как посмотреть Pod?', 'options' => ['kubectl get pods', 'kubectl list pods', 'kubectl show pods', 'kubectl pods'], 'correct' => 0, 'explanation' => 'kubectl get pods выводит список Pod.'],
            ['question' => 'Для чего Labels?', 'options' => ['Организация и селекторы', 'Хранение данных', 'Сеть', 'Безопасность'], 'correct' => 0, 'explanation' => 'Labels для организации и фильтрации объектов.'],
            ['question' => 'Что такое HPA?', 'options' => ['Horizontal Pod Autoscaler', 'High Performance Allocator', 'Hardware Processing API', 'Hybrid Platform Adapter'], 'correct' => 0, 'explanation' => 'HPA автоматически масштабирует количество Pod.'],
            ['question' => 'Как удалить deployment?', 'options' => ['kubectl delete deployment', 'kubectl remove deployment', 'kubectl destroy deployment', 'kubectl delete pod'], 'correct' => 0, 'explanation' => 'kubectl delete deployment удаляет Deployment.'],
            ['question' => 'Как масштабировать?', 'options' => ['kubectl scale', 'kubectl replicas', 'kubectl count', 'kubectl expand'], 'correct' => 0, 'explanation' => 'kubectl scale --replicas=N масштабирует.'],
            ['question' => 'Как посмотреть логи Pod?', 'options' => ['kubectl logs', 'kubectl get logs', 'kubectl show logs', 'kubectl view logs'], 'correct' => 0, 'explanation' => 'kubectl logs выводит логи контейнера.'],
            ['question' => 'Как выполнить команду в Pod?', 'options' => ['kubectl exec -it', 'kubectl run', 'kubectl execute', 'kubectl start'], 'correct' => 0, 'explanation' => 'kubectl exec -it выполняет команду в Pod.'],
            ['question' => 'Что такое Service Account?', 'options' => ['Учетная запись для Pod', 'Пользователь', 'API', 'Хранилище'], 'correct' => 0, 'explanation' => 'Service Account для API-аутентификации Pod.'],
            ['question' => 'Как применить манифест?', 'options' => ['kubectl apply -f', 'kubectl create -f', 'kubectl deploy -f', 'kubectl run -f'], 'correct' => 0, 'explanation' => 'kubectl apply -f применяет манифест.'],
            ['question' => 'Что такое readiness probe?', 'options' => ['Проверка готовности', 'Проверка здоровья', 'Проверка сети', 'Проверка хранилища'], 'correct' => 0, 'explanation' => 'Readiness probe определяет готовность принимать трафик.'],
            ['question' => 'Что такое liveness probe?', 'options' => ['Проверка работоспособности', 'Проверка готовности', 'Проверка сети', 'Проверка хранилища'], 'correct' => 0, 'explanation' => 'Liveness probe проверяет работоспособность Pod.'],
            ['question' => 'Какой тип хранилища самый быстрый?', 'options' => ['emptyDir (RAM)', 'hostPath', 'NFS', 'PersistentVolume'], 'correct' => 0, 'explanation' => 'emptyDir на tmpfs обеспечивает максимальную скорость.'],
            ['question' => 'Что такое RBAC?', 'options' => ['Role-Based Access Control', 'Random Binary Access Channel', 'Remote Backup and Cache', 'Resource Balancing and Allocation'], 'correct' => 0, 'explanation' => 'RBAC — контроль доступа на основе ролей.'],
            ['question' => 'Как обновить без downtime?', 'options' => ['Rolling update', 'Recreate', 'Blue-green', 'Canary'], 'correct' => 0, 'explanation' => 'Rolling update постепенно обновляет Pod.'],
            ['question' => 'Как посмотреть события?', 'options' => ['kubectl get events', 'kubectl events', 'kubectl show events', 'kubectl list events'], 'correct' => 0, 'explanation' => 'kubectl get events показывает события кластера.'],
            ['question' => 'Что такое Taint?', 'options' => ['Отталкивает Pod с ноды', 'Привлекает Pod', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Taint не позволяет запускать Pod на ноде без Toleration.'],
            ['question' => 'Что такое Node Affinity?', 'options' => ['Правила размещения на нодах', 'Сеть', 'Безопасность', 'Хранилище'], 'correct' => 0, 'explanation' => 'Node Affinity определяет на каких нодах запускать Pod.'],
            ['question' => 'Как копировать файл из Pod?', 'options' => ['kubectl cp', 'kubectl copy', 'kubectl fetch', 'kubectl download'], 'correct' => 0, 'explanation' => 'kubectl cp копирует файлы между Pod и локальной FS.'],
            ['question' => 'Что такое Ingress Controller?', 'options' => ['Реализация Ingress', 'Контроллер Pod', 'Сетевой контроллер', 'Контроллер хранилища'], 'correct' => 0, 'explanation' => 'Ingress Controller (nginx, traefik) реализует Ingress.'],
            ['question' => 'Как посмотреть Service?', 'options' => ['kubectl get svc', 'kubectl ports', 'kubectl list ports', 'kubectl show ports'], 'correct' => 0, 'explanation' => 'kubectl get svc показывает Service.'],
            ['question' => 'Что такое Network Policy?', 'options' => ['Правила сетевого трафика', 'Безопасность', 'Конфигурация', 'Мониторинг'], 'correct' => 0, 'explanation' => 'Network Policy ограничивает сетевой трафик.'],
            ['question' => 'Какой объект для cron задач?', 'options' => ['CronJob', 'Job', 'Deployment', 'ReplicaSet'], 'correct' => 0, 'explanation' => 'CronJob выполняет задачи по расписанию.'],
            ['question' => 'Как масштабировать deployment?', 'options' => ['kubectl scale deployment --replicas=3', 'kubectl replicas deployment 3', 'kubectl count deployment 3', 'kubectl expand deployment 3'], 'correct' => 0, 'explanation' => 'kubectl scale с флагом --replicas.'],
            ['question' => 'Как посмотреть describe Pod?', 'options' => ['kubectl describe pod name', 'kubectl info pod name', 'kubectl detail pod name', 'kubectl show pod name'], 'correct' => 0, 'explanation' => 'kubectl describe pod показывает детальную информацию.'],
            ['question' => 'Как создать deployment?', 'options' => ['kubectl create deployment', 'kubectl new deployment', 'kubectl init deployment', 'kubectl start deployment'], 'correct' => 0, 'explanation' => 'kubectl create deployment создаёт Deployment.'],
            ['question' => 'Что такое Namespace?', 'options' => ['Изоляция ресурсов в кластере', 'Сеть', 'Хранилище', 'Мониторинг'], 'correct' => 0, 'explanation' => 'Namespace для изоляции и организации ресурсов.'],
            ['question' => 'Как посмотреть Namespace?', 'options' => ['kubectl get namespaces', 'kubectl list namespaces', 'kubectl show namespaces', 'kubectl namespaces'], 'correct' => 0, 'explanation' => 'kubectl get namespaces показывает все Namespace.'],
            ['question' => 'Как удалить Pod?', 'options' => ['kubectl delete pod name', 'kubectl remove pod name', 'kubectl kill pod name', 'kubectl destroy pod name'], 'correct' => 0, 'explanation' => 'kubectl delete pod удаляет Pod.'],
            ['question' => 'Что такое ReplicaSet?', 'options' => ['Поддерживает количество реплик Pod', 'Маршрутизатор', 'Хранилище', 'Сеть'], 'correct' => 0, 'explanation' => 'ReplicaSet поддерживает нужное число реплик.'],
            ['question' => 'Что такое Deployment?', 'options' => ['Управляет ReplicaSet и обновлениями', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Deployment управляет ReplicaSet и обновлениями.'],
            ['question' => 'Какой тип Service для внешнего доступа?', 'options' => ['LoadBalancer', 'ClusterIP', 'NodePort', 'ExternalName'], 'correct' => 0, 'explanation' => 'LoadBalancer для внешнего доступа через облачный балансировщик.'],
            ['question' => 'Какой тип Service через порт ноды?', 'options' => ['NodePort', 'ClusterIP', 'LoadBalancer', 'ExternalName'], 'correct' => 0, 'explanation' => 'NodePort открывает порт на каждой ноде.'],
            ['question' => 'Что такое DaemonSet?', 'options' => ['Запускает Pod на всех нодах', 'Запускает Pod один раз', 'Маршрутизатор', 'Хранилище'], 'correct' => 0, 'explanation' => 'DaemonSet гарантирует Pod на каждой ноде.'],
            ['question' => 'Что такое Job?', 'options' => ['Запускает одноразовые задачи', 'Deployment', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Job для одноразовых вычислительных задач.'],
            ['question' => 'Как посмотреть Container logs?', 'options' => ['kubectl logs pod_name -c container', 'kubectl logs container pod_name', 'kubectl get logs pod_name', 'kubectl show logs pod_name'], 'correct' => 0, 'explanation' => 'kubectl logs с флагом -c для контейнера.'],
            ['question' => 'Что такое Label?', 'options' => ['Ключ-значение для организации объектов', 'Имя Pod', 'IP адрес', 'Порт'], 'correct' => 0, 'explanation' => 'Label для организации и селекции объектов.'],
            ['question' => 'Что такое Selector?', 'options' => ['Фильтрация объектов по Labels', 'Имя Pod', 'IP адрес', 'Порт'], 'correct' => 0, 'explanation' => 'Selector фильтрует объекты по Labels.'],
            ['question' => 'Как посмотреть yaml манифест?', 'options' => ['kubectl get pod -o yaml', 'kubectl yaml pod', 'kubectl show yaml pod', 'kubectl view yaml pod'], 'correct' => 0, 'explanation' => 'kubectl get -o yaml выводит YAML.'],
            ['question' => 'Как посмотреть JSON манифест?', 'options' => ['kubectl get pod -o json', 'kubectl json pod', 'kubectl show json pod', 'kubectl view json pod'], 'correct' => 0, 'explanation' => 'kubectl get -o json выводит JSON.'],
            ['question' => 'Как применить манифест из URL?', 'options' => ['kubectl apply -f https://...', 'kubectl create -f https://...', 'kubectl deploy -f https://...', 'kubectl run -f https://...'], 'correct' => 0, 'explanation' => 'kubectl apply -f с URL.'],
            ['question' => 'Что такое ClusterRole?', 'options' => ['Роль для всего кластера', 'Роль для Namespace', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'ClusterRole для всего кластера.'],
            ['question' => 'Что такое ClusterRoleBinding?', 'options' => ['Связывает ClusterRole с пользователем', 'Сеть', 'Хранилище', 'Мониторинг'], 'correct' => 0, 'explanation' => 'ClusterRoleBinding связывает ClusterRole.'],
            ['question' => 'Как посмотреть права доступа?', 'options' => ['kubectl auth can-i create pods', 'kubectl permissions pods', 'kubectl access pods', 'kubectl rights pods'], 'correct' => 0, 'explanation' => 'kubectl auth can-i проверяет права.'],
            ['question' => 'Что такое Helm?', 'options' => ['Менеджер пакетов для Kubernetes', 'Контейнер', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Helm — менеджер пакетов (чартов) для K8s.'],
            ['question' => 'Как установить Helm chart?', 'options' => ['helm install release chart', 'helm deploy release chart', 'helm create release chart', 'helm start release chart'], 'correct' => 0, 'explanation' => 'helm install устанавливает чарт.'],
            ['question' => 'Как удалить Helm release?', 'options' => ['helm delete release', 'helm remove release', 'helm destroy release', 'helm uninstall release'], 'correct' => 0, 'explanation' => 'helm delete или helm uninstall.'],
            ['question' => 'Как посмотреть Helm releases?', 'options' => ['helm list', 'helm releases', 'helm show releases', 'helm get releases'], 'correct' => 0, 'explanation' => 'helm list показывает все релизы.'],
            ['question' => 'Что такое StorageClass?', 'options' => ['Определяет класс хранилища', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'StorageClass определяет тип и параметры хранилища.'],
            ['question' => 'Как создать PVC?', 'options' => ['kubectl apply -f pvc.yaml', 'kubectl create pvc', 'kubectl new pvc', 'kubectl init pvc'], 'correct' => 0, 'explanation' => 'kubectl apply -f pvc.yaml.'],
            ['question' => 'Что такое Endpoints?', 'options' => ['IP адреса и порты Pod за Service', 'Имена Pod', 'Labels', 'Namespace'], 'correct' => 0, 'explanation' => 'Endpoints содержат IP адреса Pod за Service.'],
            ['question' => 'Как посмотреть Endpoints?', 'options' => ['kubectl get endpoints', 'kubectl endpoints', 'kubectl show endpoints', 'kubectl list endpoints'], 'correct' => 0, 'explanation' => 'kubectl get endpoints.'],
            ['question' => 'Что такое ResourceQuota?', 'options' => ['Лимиты ресурсов в Namespace', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'ResourceQuota ограничивает ресурсы в Namespace.'],
            ['question' => 'Что такое LimitRange?', 'options' => ['Лимиты ресурсов для Pod/Container', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'LimitRange устанавливает дефолтные лимиты для Pod.'],
            ['question' => 'Как посмотреть kubectl config?', 'options' => ['kubectl config view', 'kubectl config show', 'kubectl config list', 'kubectl config info'], 'correct' => 0, 'explanation' => 'kubectl config view показывает конфигурацию.'],
            ['question' => 'Как переключить контекст?', 'options' => ['kubectl config use-context', 'kubectl context switch', 'kubectl change context', 'kubectl set context'], 'correct' => 0, 'explanation' => 'kubectl config use-context переключает контекст.'],
        ],
        'practices' => [
            ['title' => 'Deployment для Node.js', 'instructions' => 'Создайте Deployment для Node.js с 3 репликами и лимитами ресурсов.', 'starter_code' => 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: node-app\nspec:\n  replicas: 3', 'solution_code' => 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: node-app\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: node-app\n  template:\n    metadata:\n      labels:\n        app: node-app\n    spec:\n      containers:\n      - name: node-app\n        image: node:18-alpine\n        ports:\n        - containerPort: 3000\n        resources:\n          requests:\n            memory: "128Mi"\n            cpu: "100m"\n          limits:\n            memory: "256Mi"\n            cpu: "200m"', 'tests' => [['input' => 'kubectl apply -f deployment.yaml', 'expected' => 'Deployment создан', 'description' => 'Манифест применяется']]],
            ['title' => 'Service для доступа к приложению', 'instructions' => 'Создайте Service типа NodePort для доступа к приложению.', 'starter_code' => 'apiVersion: v1\nkind: Service\nmetadata:\n  name: node-app-service\nspec:\n  type: NodePort', 'solution_code' => 'apiVersion: v1\nkind: Service\nmetadata:\n  name: node-app-service\nspec:\n  type: NodePort\n  selector:\n    app: node-app\n  ports:\n  - port: 80\n    targetPort: 3000\n    nodePort: 30080', 'tests' => [['input' => 'kubectl apply -f service.yaml', 'expected' => 'Service создан', 'description' => 'Манифест применяется']]],
            ['title' => 'ConfigMap для приложения', 'instructions' => 'Создайте ConfigMap и подключите его к Deployment.', 'starter_code' => 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:', 'solution_code' => 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  DATABASE_HOST: "db-service"\n  DATABASE_PORT: "5432"\n  LOG_LEVEL: "info"\n---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: app\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: app\n  template:\n    metadata:\n      labels:\n        app: app\n    spec:\n      containers:\n      - name: app\n        image: myapp:latest\n        envFrom:\n        - configMapRef:\n            name: app-config', 'tests' => [['input' => 'kubectl apply -f configmap.yaml', 'expected' => 'ConfigMap создан', 'description' => 'ConfigMap применяется']]],
            ['title' => 'HPA для масштабирования', 'instructions' => 'Создайте HPA для автоматического масштабирования.', 'starter_code' => 'apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: app-hpa', 'solution_code' => 'apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: app-hpa\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: app\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n  - type: Resource\n    resource:\n      name: cpu\n      target:\n        type: Utilization\n        averageUtilization: 70', 'tests' => [['input' => 'kubectl apply -f hpa.yaml', 'expected' => 'HPA создан', 'description' => 'HPA применяется']]],
            ['title' => 'Persistent Volume для базы данных', 'instructions' => 'Создайте PV и PVC для базы данных.', 'starter_code' => 'apiVersion: v1\nkind: PersistentVolume\nmetadata:\n  name: my-pv', 'solution_code' => 'apiVersion: v1\nkind: PersistentVolume\nmetadata:\n  name: my-pv\nspec:\n  capacity:\n    storage: 10Gi\n  accessModes:\n    - ReadWriteOnce\n  hostPath:\n    path: /mnt/data\n---\napiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: my-pvc\nspec:\n  accessModes:\n    - ReadWriteOnce\n  resources:\n    requests:\n      storage: 5Gi', 'tests' => [['input' => 'kubectl apply -f pv.yaml', 'expected' => 'PV и PVC созданы', 'description' => 'Хранилище настроено']]],
        ],
        'exam' => [
            'title' => 'Экзамен по Kubernetes',
            'time' => 70,
            'pass' => 70,
            'bank' => [
                ['question' => 'Какой компонент хранит состояние кластера?', 'options' => ['etcd', 'API Server', 'Scheduler', 'Controller Manager'], 'correct' => 0, 'explanation' => 'etcd.'],
                ['question' => 'Что такое Pod?', 'options' => ['Минимальная единица развертывания', 'Контейнер', 'Нода', 'Сеть'], 'correct' => 0, 'explanation' => 'Минимальная единица.'],
                ['question' => 'Какой объект поддерживает реплики?', 'options' => ['ReplicaSet', 'Deployment', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'ReplicaSet.'],
                ['question' => 'Какой тип Service внутренний?', 'options' => ['ClusterIP', 'NodePort', 'LoadBalancer', 'ExternalName'], 'correct' => 0, 'explanation' => 'ClusterIP.'],
                ['question' => 'Для чего Ingress?', 'options' => ['HTTP маршрутизация', 'Сеть', 'Хранилище', 'Мониторинг'], 'correct' => 0, 'explanation' => 'HTTP маршрутизация.'],
                ['question' => 'Чем Secrets отличаются от ConfigMaps?', 'options' => ['Для чувствительных данных', 'Быстрее', 'Больше', 'Другой формат'], 'correct' => 0, 'explanation' => 'Для чувствительных данных.'],
                ['question' => 'Что такое Persistent Volume?', 'options' => ['Абстракция хранилища', 'Контейнер', 'Pod', 'Service'], 'correct' => 0, 'explanation' => 'Абстракция хранилища.'],
                ['question' => 'Для чего StatefulSets?', 'options' => ['Для stateful приложений', 'Для Stateless', 'Для маршрутизации', 'Для мониторинга'], 'correct' => 0, 'explanation' => 'Для stateful приложений.'],
                ['question' => 'Как посмотреть Pod?', 'options' => ['kubectl get pods', 'kubectl list pods', 'kubectl show pods', 'kubectl pods'], 'correct' => 0, 'explanation' => 'kubectl get pods.'],
                ['question' => 'Для чего Labels?', 'options' => ['Организация и селекторы', 'Хранение данных', 'Сеть', 'Безопасность'], 'correct' => 0, 'explanation' => 'Организация и селекторы.'],
                ['question' => 'Что такое HPA?', 'options' => ['Horizontal Pod Autoscaler', 'High Performance Allocator', 'Hardware Processing API', 'Hybrid Platform Adapter'], 'correct' => 0, 'explanation' => 'Horizontal Pod Autoscaler.'],
                ['question' => 'Как удалить deployment?', 'options' => ['kubectl delete deployment', 'kubectl remove deployment', 'kubectl destroy deployment', 'kubectl delete pod'], 'correct' => 0, 'explanation' => 'kubectl delete deployment.'],
                ['question' => 'Как масштабировать?', 'options' => ['kubectl scale', 'kubectl replicas', 'kubectl count', 'kubectl expand'], 'correct' => 0, 'explanation' => 'kubectl scale.'],
                ['question' => 'Как логи Pod?', 'options' => ['kubectl logs', 'kubectl get logs', 'kubectl show logs', 'kubectl view logs'], 'correct' => 0, 'explanation' => 'kubectl logs.'],
                ['question' => 'Как выполнить команду в Pod?', 'options' => ['kubectl exec -it', 'kubectl run', 'kubectl execute', 'kubectl start'], 'correct' => 0, 'explanation' => 'kubectl exec -it.'],
                ['question' => 'Что такое Service Account?', 'options' => ['Учетная запись для Pod', 'Пользователь', 'API', 'Хранилище'], 'correct' => 0, 'explanation' => 'Учетная запись для Pod.'],
                ['question' => 'Как применить манифест?', 'options' => ['kubectl apply -f', 'kubectl create -f', 'kubectl deploy -f', 'kubectl run -f'], 'correct' => 0, 'explanation' => 'kubectl apply -f.'],
                ['question' => 'Что такое readiness probe?', 'options' => ['Проверка готовности', 'Проверка здоровья', 'Проверка сети', 'Проверка хранилища'], 'correct' => 0, 'explanation' => 'Проверка готовности.'],
                ['question' => 'Что такое liveness probe?', 'options' => ['Проверка работоспособности', 'Проверка готовности', 'Проверка сети', 'Проверка хранилища'], 'correct' => 0, 'explanation' => 'Проверка работоспособности.'],
                ['question' => 'Какой тип хранилища самый быстрый?', 'options' => ['emptyDir (RAM)', 'hostPath', 'NFS', 'PersistentVolume'], 'correct' => 0, 'explanation' => 'emptyDir на tmpfs.'],
                ['question' => 'Что такое RBAC?', 'options' => ['Role-Based Access Control', 'Random Binary Access Channel', 'Remote Backup and Cache', 'Resource Balancing and Allocation'], 'correct' => 0, 'explanation' => 'Role-Based Access Control.'],
                ['question' => 'Как обновить без downtime?', 'options' => ['Rolling update', 'Recreate', 'Blue-green', 'Canary'], 'correct' => 0, 'explanation' => 'Rolling update.'],
                ['question' => 'Как посмотреть события?', 'options' => ['kubectl get events', 'kubectl events', 'kubectl show events', 'kubectl list events'], 'correct' => 0, 'explanation' => 'kubectl get events.'],
                ['question' => 'Что такое Taint?', 'options' => ['Отталкивает Pod с ноды', 'Привлекает Pod', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Отталкивает Pod.'],
                ['question' => 'Что такое Node Affinity?', 'options' => ['Правила размещения на нодах', 'Сеть', 'Безопасность', 'Хранилище'], 'correct' => 0, 'explanation' => 'Правила размещения.'],
                ['question' => 'Как копировать файл из Pod?', 'options' => ['kubectl cp', 'kubectl copy', 'kubectl fetch', 'kubectl download'], 'correct' => 0, 'explanation' => 'kubectl cp.'],
                ['question' => 'Что такое Ingress Controller?', 'options' => ['Реализация Ingress', 'Контроллер Pod', 'Сетевой контроллер', 'Контроллер хранилища'], 'correct' => 0, 'explanation' => 'Реализация Ingress.'],
                ['question' => 'Как посмотреть Service?', 'options' => ['kubectl get svc', 'kubectl ports', 'kubectl list ports', 'kubectl show ports'], 'correct' => 0, 'explanation' => 'kubectl get svc.'],
                ['question' => 'Что такое Network Policy?', 'options' => ['Правила сетевого трафика', 'Безопасность', 'Конфигурация', 'Мониторинг'], 'correct' => 0, 'explanation' => 'Правила сетевого трафика.'],
                ['question' => 'Какой объект для cron задач?', 'options' => ['CronJob', 'Job', 'Deployment', 'ReplicaSet'], 'correct' => 0, 'explanation' => 'CronJob.'],
                ['question' => 'Как масштабировать deployment?', 'options' => ['kubectl scale deployment --replicas=3', 'kubectl replicas deployment 3', 'kubectl count deployment 3', 'kubectl expand deployment 3'], 'correct' => 0, 'explanation' => 'kubectl scale --replicas.'],
                ['question' => 'Как посмотреть describe Pod?', 'options' => ['kubectl describe pod name', 'kubectl info pod name', 'kubectl detail pod name', 'kubectl show pod name'], 'correct' => 0, 'explanation' => 'kubectl describe pod.'],
                ['question' => 'Как создать deployment?', 'options' => ['kubectl create deployment', 'kubectl new deployment', 'kubectl init deployment', 'kubectl start deployment'], 'correct' => 0, 'explanation' => 'kubectl create deployment.'],
                ['question' => 'Что такое Namespace?', 'options' => ['Изоляция ресурсов в кластере', 'Сеть', 'Хранилище', 'Мониторинг'], 'correct' => 0, 'explanation' => 'Изоляция ресурсов.'],
                ['question' => 'Как посмотреть Namespace?', 'options' => ['kubectl get namespaces', 'kubectl list namespaces', 'kubectl show namespaces', 'kubectl namespaces'], 'correct' => 0, 'explanation' => 'kubectl get namespaces.'],
                ['question' => 'Как удалить Pod?', 'options' => ['kubectl delete pod name', 'kubectl remove pod name', 'kubectl kill pod name', 'kubectl destroy pod name'], 'correct' => 0, 'explanation' => 'kubectl delete pod.'],
                ['question' => 'Что такое ReplicaSet?', 'options' => ['Поддерживает количество реплик Pod', 'Маршрутизатор', 'Хранилище', 'Сеть'], 'correct' => 0, 'explanation' => 'Поддерживает реплики.'],
                ['question' => 'Что такое Deployment?', 'options' => ['Управляет ReplicaSet и обновлениями', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Управляет ReplicaSet.'],
                ['question' => 'Какой тип Service для внешнего доступа?', 'options' => ['LoadBalancer', 'ClusterIP', 'NodePort', 'ExternalName'], 'correct' => 0, 'explanation' => 'LoadBalancer.'],
                ['question' => 'Какой тип Service через порт ноды?', 'options' => ['NodePort', 'ClusterIP', 'LoadBalancer', 'ExternalName'], 'correct' => 0, 'explanation' => 'NodePort.'],
                ['question' => 'Что такое DaemonSet?', 'options' => ['Запускает Pod на всех нодах', 'Запускает Pod один раз', 'Маршрутизатор', 'Хранилище'], 'correct' => 0, 'explanation' => 'На всех нодах.'],
                ['question' => 'Что такое Job?', 'options' => ['Запускает одноразовые задачи', 'Deployment', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Одноразовые задачи.'],
                ['question' => 'Что такое Label?', 'options' => ['Ключ-значение для организации', 'Имя Pod', 'IP адрес', 'Порт'], 'correct' => 0, 'explanation' => 'Организация объектов.'],
                ['question' => 'Что такое Selector?', 'options' => ['Фильтрация по Labels', 'Имя Pod', 'IP адрес', 'Порт'], 'correct' => 0, 'explanation' => 'Фильтрация по Labels.'],
                ['question' => 'Как посмотреть yaml?', 'options' => ['kubectl get pod -o yaml', 'kubectl yaml pod', 'kubectl show yaml pod', 'kubectl view yaml pod'], 'correct' => 0, 'explanation' => 'kubectl get -o yaml.'],
                ['question' => 'Как посмотреть json?', 'options' => ['kubectl get pod -o json', 'kubectl json pod', 'kubectl show json pod', 'kubectl view json pod'], 'correct' => 0, 'explanation' => 'kubectl get -o json.'],
                ['question' => 'Что такое Helm?', 'options' => ['Менеджер пакетов для K8s', 'Контейнер', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Менеджер пакетов.'],
                ['question' => 'Как установить Helm chart?', 'options' => ['helm install release chart', 'helm deploy release chart', 'helm create release chart', 'helm start release chart'], 'correct' => 0, 'explanation' => 'helm install.'],
                ['question' => 'Как удалить Helm release?', 'options' => ['helm delete release', 'helm remove release', 'helm destroy release', 'helm uninstall release'], 'correct' => 0, 'explanation' => 'helm delete.'],
                ['question' => 'Как посмотреть Helm releases?', 'options' => ['helm list', 'helm releases', 'helm show releases', 'helm get releases'], 'correct' => 0, 'explanation' => 'helm list.'],
                ['question' => 'Что такое StorageClass?', 'options' => ['Определяет класс хранилища', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Класс хранилища.'],
                ['question' => 'Что такое ResourceQuota?', 'options' => ['Лимиты ресурсов в Namespace', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Лимиты ресурсов.'],
                ['question' => 'Что такое LimitRange?', 'options' => ['Лимиты для Pod/Container', 'Pod', 'Service', 'ConfigMap'], 'correct' => 0, 'explanation' => 'Лимиты для Pod.'],
                ['question' => 'Как посмотреть kubectl config?', 'options' => ['kubectl config view', 'kubectl config show', 'kubectl config list', 'kubectl config info'], 'correct' => 0, 'explanation' => 'kubectl config view.'],
                ['question' => 'Как переключить контекст?', 'options' => ['kubectl config use-context', 'kubectl context switch', 'kubectl change context', 'kubectl set context'], 'correct' => 0, 'explanation' => 'kubectl config use-context.'],
                ['question' => 'Что такое Endpoints?', 'options' => ['IP адреса Pod за Service', 'Имена Pod', 'Labels', 'Namespace'], 'correct' => 0, 'explanation' => 'IP адреса Pod.'],
                ['question' => 'Как посмотреть Endpoints?', 'options' => ['kubectl get endpoints', 'kubectl endpoints', 'kubectl show endpoints', 'kubectl list endpoints'], 'correct' => 0, 'explanation' => 'kubectl get endpoints.'],
                ['question' => 'Что такое ClusterRole?', 'options' => ['Роль для всего кластера', 'Роль для Namespace', 'Сеть', 'Хранилище'], 'correct' => 0, 'explanation' => 'Роль для всего кластера.'],
                ['question' => 'Как посмотреть права доступа?', 'options' => ['kubectl auth can-i create pods', 'kubectl permissions pods', 'kubectl access pods', 'kubectl rights pods'], 'correct' => 0, 'explanation' => 'kubectl auth can-i.'],
                ['question' => 'Как посмотреть yaml манифест из URL?', 'options' => ['kubectl apply -f https://...', 'kubectl create -f https://...', 'kubectl deploy -f https://...', 'kubectl run -f https://...'], 'correct' => 0, 'explanation' => 'kubectl apply -f с URL.'],
                ['question' => 'Как создать PVC?', 'options' => ['kubectl apply -f pvc.yaml', 'kubectl create pvc', 'kubectl new pvc', 'kubectl init pvc'], 'correct' => 0, 'explanation' => 'kubectl apply -f pvc.yaml.'],
                ['question' => 'Как посмотреть Container logs с флагом?', 'options' => ['kubectl logs pod -c container', 'kubectl logs container pod', 'kubectl get logs pod', 'kubectl show logs pod'], 'correct' => 0, 'explanation' => 'kubectl logs -c.'],
            ],
        ],
    ],

    19 => [ // Mobile Development
        'quizzes' => [
            ['question' => 'Что такое нативная разработка?', 'options' => ['Разработка для конкретной платформы', 'Кроссплатформенная', 'Веб-разработка', 'Десктоп'], 'correct' => 0, 'explanation' => 'Для конкретной платформы.'],
            ['question' => 'Какой компонент аналог div в React Native?', 'options' => ['View', 'Container', 'Box', 'Layout'], 'correct' => 0, 'explanation' => 'View.'],
            ['question' => 'Как создать стили в React Native?', 'options' => ['StyleSheet.create()', 'CSS файл', 'style атрибут', 'Styled Components'], 'correct' => 0, 'explanation' => 'StyleSheet.create().'],
            ['question' => 'Какая библиотека навигации в React Native?', 'options' => ['React Navigation', 'React Router', 'Vue Router', 'Angular Router'], 'correct' => 0, 'explanation' => 'React Navigation.'],
            ['question' => 'Какой хук для состояния?', 'options' => ['useState', 'useEffect', 'useContext', 'useReducer'], 'correct' => 0, 'explanation' => 'useState.'],
            ['question' => 'Что такое виджет во Flutter?', 'options' => ['Базовый строительный блок UI', 'Компонент React', 'HTML элемент', 'CSS класс'], 'correct' => 0, 'explanation' => 'Базовый строительный блок.'],
            ['question' => 'Какой язык во Flutter?', 'options' => ['Dart', 'JavaScript', 'Kotlin', 'Swift'], 'correct' => 0, 'explanation' => 'Dart.'],
            ['question' => 'Что такое Material Design?', 'options' => ['Дизайн-система от Google', 'от Apple', 'CSS фреймворк', 'JavaScript библиотека'], 'correct' => 0, 'explanation' => 'Дизайн-система от Google.'],
            ['question' => 'Зачем адаптивный дизайн?', 'options' => ['Для разных размеров экранов', 'Для скорости', 'Для безопасности', 'Для хранения'], 'correct' => 0, 'explanation' => 'Для разных размеров экранов.'],
            ['question' => 'Зачем push-уведомления?', 'options' => ['Для доставки сообщений', 'Для хранения', 'Для авторизации', 'Для оплаты'], 'correct' => 0, 'explanation' => 'Для доставки сообщений.'],
            ['question' => 'Что такое deep linking?', 'options' => ['Гиперссылка на контент приложения', 'Ссылка на сайт', 'API вызов', 'Тип навигации'], 'correct' => 0, 'explanation' => 'Гиперссылка на контент.'],
            ['question' => 'Что проверяет App Store Review?', 'options' => ['Качество, безопасность, гайдлайны', 'Только функциональность', 'Только дизайн', 'Только производительность'], 'correct' => 0, 'explanation' => 'Множество аспектов.'],
            ['question' => 'Как оптимизировать производительность?', 'options' => ['Уменьшить размер сборки', 'Увеличить компоненты', 'Больше памяти', 'Больше зависимостей'], 'correct' => 0, 'explanation' => 'Уменьшить размер.'],
            ['question' => 'Какой инструмент для отладки React Native?', 'options' => ['React Native Debugger', 'Chrome DevTools', 'Xcode Debugger', 'Android Studio'], 'correct' => 0, 'explanation' => 'React Native Debugger.'],
            ['question' => 'Какой тип тестирования проверяет UI?', 'options' => ['E2E тестирование', 'Unit тестирование', 'Интеграционное', 'Нагрузочное'], 'correct' => 0, 'explanation' => 'E2E тестирование.'],
            ['question' => 'Какой компонент для списка в React Native?', 'options' => ['FlatList', 'ScrollView', 'List', 'Array'], 'correct' => 0, 'explanation' => 'FlatList.'],
            ['question' => 'Что такое hot reload?', 'options' => ['Обновление кода без перезапуска', 'Перезапуск', 'Компиляция', 'Загрузка данных'], 'correct' => 0, 'explanation' => 'Обновление без перезапуска.'],
            ['question' => 'Какой стейт-менеджер для Flutter?', 'options' => ['Provider', 'Redux', 'Vuex', 'MobX'], 'correct' => 0, 'explanation' => 'Provider.'],
            ['question' => 'Что такое AAB в Android?', 'options' => ['Android App Bundle', 'Android Application Base', 'Android API Builder', 'Android Asset Bundle'], 'correct' => 0, 'explanation' => 'Android App Bundle.'],
            ['question' => 'Какой файл конфигурации React Native?', 'options' => ['package.json', 'config.json', 'settings.json', 'app.json'], 'correct' => 0, 'explanation' => 'package.json.'],
            ['question' => 'Какой файл конфигурации Flutter?', 'options' => ['pubspec.yaml', 'package.json', 'config.yaml', 'settings.yaml'], 'correct' => 0, 'explanation' => 'pubspec.yaml.'],
            ['question' => 'Как посмотреть девайс в React Native?', 'options' => ['adb devices', 'react-native devices', 'rn devices', 'mobile devices'], 'correct' => 0, 'explanation' => 'adb devices.'],
            ['question' => 'Как запустить React Native приложение?', 'options' => ['react-native run-android', 'react-native start', 'react-native build', 'react-native deploy'], 'correct' => 0, 'explanation' => 'react-native run-android.'],
            ['question' => 'Как запустить Flutter приложение?', 'options' => ['flutter run', 'dart run', 'flutter start', 'dart start'], 'correct' => 0, 'explanation' => 'flutter run.'],
            ['question' => 'Что такое Expo?', 'options' => ['Платформа для React Native', 'Библиотека для Flutter', 'Фреймворк для Android', 'Тестирование'], 'correct' => 0, 'explanation' => 'Платформа для React Native.'],
            ['question' => 'Что такое CocoaPods?', 'options' => ['Менеджер зависимостей для iOS', 'Менеджер для Android', 'Менеджер для Flutter', 'Тестирование'], 'correct' => 0, 'explanation' => 'Менеджер зависимостей для iOS.'],
            ['question' => 'Что такое Gradle?', 'options' => ['Система сборки для Android', 'Система для iOS', 'Система для Flutter', 'Тестирование'], 'correct' => 0, 'explanation' => 'Система сборки для Android.'],
            ['question' => 'Какой API для iOS?', 'options' => ['UIKit / SwiftUI', 'Jetpack Compose', 'React Native', 'Flutter'], 'correct' => 0, 'explanation' => 'UIKit / SwiftUI.'],
            ['question' => 'Какой API для Android?', 'options' => ['Jetpack Compose', 'UIKit', 'React Native', 'Flutter'], 'correct' => 0, 'explanation' => 'Jetpack Compose.'],
            ['question' => 'Что такое Code Signing?', 'options' => ['Подпись кода для публикации', 'Шифрование', 'Тестирование', 'Оптимизация'], 'correct' => 0, 'explanation' => 'Подпись кода для публикации.'],
            ['question' => 'Что такое Provisioning Profile?', 'options' => ['Профиль для подписания iOS приложений', 'Профиль для Android', 'Профиль для Flutter', 'Тестирование'], 'correct' => 0, 'explanation' => 'Профиль для iOS.'],
            ['question' => 'Что такое keystore в Android?', 'options' => ['Файл с ключами для подписания APK', 'Файл конфигурации', 'Файл ресурсов', 'Тестирование'], 'correct' => 0, 'explanation' => 'Файл с ключами для подписания.'],
            ['question' => 'Какой формат для Android?', 'options' => ['AAB / APK', 'IPA', 'Dart Package', 'React Bundle'], 'correct' => 0, 'explanation' => 'AAB / APK.'],
            ['question' => 'Какой формат для iOS?', 'options' => ['IPA', 'AAB / APK', 'Dart Package', 'React Bundle'], 'correct' => 0, 'explanation' => 'IPA.'],
            ['question' => 'Что такое TestFlight?', 'options' => ['Бета-тестирование iOS приложений', 'Тестирование Android', 'Тестирование Flutter', 'Отладка'], 'correct' => 0, 'explanation' => 'Бета-тестирование iOS.'],
            ['question' => 'Что такое Firebase?', 'options' => ['Платформа для мобильных приложений', 'Только аналитика', 'Только push-уведомления', 'Только тестирование'], 'correct' => 0, 'explanation' => 'Платформа для мобильных приложений.'],
        ],
        'practices' => [
            ['title' => 'React Native компонент списка', 'instructions' => 'Создайте компонент UserList с FlatList, отображающий имя и email каждого пользователя. Добавьте стили через StyleSheet.', 'starter_code' => "import React from 'react';\nimport { View, Text, FlatList, StyleSheet } from 'react-native';\n\nconst users = [\n  { id: '1', name: 'Анна', email: 'anna@test.com' },\n  { id: '2', name: 'Борис', email: 'boris@test.com' },\n];\n\nexport default function UserList() {\n  // ваш код\n}", 'solution_code' => "import React from 'react';\nimport { View, Text, FlatList, StyleSheet } from 'react-native';\n\nconst users = [\n  { id: '1', name: 'Анна', email: 'anna@test.com' },\n  { id: '2', name: 'Борис', email: 'boris@test.com' },\n];\n\nexport default function UserList() {\n  return (\n    <FlatList\n      data={users}\n      keyExtractor={(item) => item.id}\n      renderItem={({ item }) => (\n        <View style={styles.item}>\n          <Text style={styles.name}>{item.name}</Text>\n          <Text style={styles.email}>{item.email}</Text>\n        </View>\n      )}\n    />\n  );\n}\n\nconst styles = StyleSheet.create({\n  item: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#ccc' },\n  name: { fontSize: 18, fontWeight: 'bold' },\n  email: { fontSize: 14, color: '#666' },\n});", 'tests' => [['input' => 'renderItem', 'expected' => 'View с Text', 'description' => 'Компонент рендерит элемент']]],
            ['title' => 'Flutter виджет карточки', 'instructions' => 'Создайте Flutter виджет ProductCard с изображением, названием и ценой. Используйте Card и Column.', 'starter_code' => "import 'package:flutter/material.dart';\n\nclass ProductCard extends StatelessWidget {\n  final String name;\n  final double price;\n\n  const ProductCard({required this.name, required this.price});\n\n  @override\n  Widget build(BuildContext context) {\n    // ваш код\n  }\n}", 'solution_code' => "import 'package:flutter/material.dart';\n\nclass ProductCard extends StatelessWidget {\n  final String name;\n  final double price;\n\n  const ProductCard({required this.name, required this.price});\n\n  @override\n  Widget build(BuildContext context) {\n    return Card(\n      margin: EdgeInsets.all(8),\n      child: Column(\n        children: [\n          Container(\n            height: 150,\n            color: Colors.grey[300],\n            child: Center(child: Icon(Icons.image, size: 64)),\n          ),\n          Padding(\n            padding: EdgeInsets.all(12),\n            child: Column(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              children: [\n                Text(name, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),\n                SizedBox(height: 4),\n                Text('\${price.toStringAsFixed(2)}', style: TextStyle(fontSize: 16, color: Colors.green)),\n              ],\n            ),\n          ),\n        ],\n      ),\n    );\n  }\n}", 'tests' => [['input' => 'ProductCard(name:"Phone",price:999.99)', 'expected' => 'Card widget', 'description' => 'Карточка создаётся']]],
            ['title' => 'Навигация между экранами', 'instructions' => 'Создайте два экрана: HomeScreen и DetailScreen. На HomeScreen кнопка перехода на DetailScreen с передачей параметра.', 'starter_code' => "import 'package:flutter/material.dart';\n\nvoid main() => runApp(MaterialApp(home: HomeScreen()));\n\nclass HomeScreen extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    // ваш код\n  }\n}\n\nclass DetailScreen extends StatelessWidget {\n  final String title;\n  const DetailScreen({required this.title});\n\n  @override\n  Widget build(BuildContext context) {\n    // ваш код\n  }\n}", 'solution_code' => "import 'package:flutter/material.dart';\n\nvoid main() => runApp(MaterialApp(home: HomeScreen()));\n\nclass HomeScreen extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: Text('Home')),\n      body: Center(\n        child: ElevatedButton(\n          onPressed: () {\n            Navigator.push(\n              context,\n              MaterialPageRoute(builder: (context) => DetailScreen(title: 'Детали')),\n            );\n          },\n          child: Text('Открыть детали'),\n        ),\n      ),\n    );\n  }\n}\n\nclass DetailScreen extends StatelessWidget {\n  final String title;\n  const DetailScreen({required this.title});\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: Text(title)),\n      body: Center(child: Text('Это экран деталей')),\n    );\n  }\n}", 'tests' => [['input' => 'Navigator.push', 'expected' => 'DetailScreen', 'description' => 'Навигация работает']]],
        ],
        'exam' => [
            'title' => 'Экзамен по Mobile Development',
            'time' => 60,
            'pass' => 70,
            'bank' => [
                ['question' => 'Что такое нативная разработка?', 'options' => ['Для конкретной платформы', 'Кроссплатформенная', 'Веб', 'Десктоп'], 'correct' => 0, 'explanation' => 'Для конкретной платформы.'],
                ['question' => 'Аналог div в React Native?', 'options' => ['View', 'Container', 'Box', 'Layout'], 'correct' => 0, 'explanation' => 'View.'],
                ['question' => 'Как создать стили в React Native?', 'options' => ['StyleSheet.create()', 'CSS файл', 'style атрибут', 'Styled Components'], 'correct' => 0, 'explanation' => 'StyleSheet.create().'],
                ['question' => 'Библиотека навигации в React Native?', 'options' => ['React Navigation', 'React Router', 'Vue Router', 'Angular Router'], 'correct' => 0, 'explanation' => 'React Navigation.'],
                ['question' => 'Хук для состояния?', 'options' => ['useState', 'useEffect', 'useContext', 'useReducer'], 'correct' => 0, 'explanation' => 'useState.'],
                ['question' => 'Что такое виджет во Flutter?', 'options' => ['Строительный блок UI', 'Компонент React', 'HTML элемент', 'CSS класс'], 'correct' => 0, 'explanation' => 'Строительный блок UI.'],
                ['question' => 'Язык во Flutter?', 'options' => ['Dart', 'JavaScript', 'Kotlin', 'Swift'], 'correct' => 0, 'explanation' => 'Dart.'],
                ['question' => 'Что такое Material Design?', 'options' => ['Дизайн-система от Google', 'от Apple', 'CSS фреймворк', 'JS библиотека'], 'correct' => 0, 'explanation' => 'Дизайн-система Google.'],
                ['question' => 'Зачем адаптивный дизайн?', 'options' => ['Для разных экранов', 'Для скорости', 'Для безопасности', 'Для хранения'], 'correct' => 0, 'explanation' => 'Для разных размеров экранов.'],
                ['question' => 'Зачем push-уведомления?', 'options' => ['Для доставки сообщений', 'Для хранения', 'Для авторизации', 'Для оплаты'], 'correct' => 0, 'explanation' => 'Для доставки сообщений.'],
                ['question' => 'Что такое deep linking?', 'options' => ['Ссылка на контент приложения', 'Ссылка на сайт', 'API вызов', 'Тип навигации'], 'correct' => 0, 'explanation' => 'Ссылка на контент.'],
                ['question' => 'Как оптимизировать производительность?', 'options' => ['Уменьшить размер сборки', 'Увеличить компоненты', 'Больше памяти', 'Больше зависимостей'], 'correct' => 0, 'explanation' => 'Уменьшить размер.'],
                ['question' => 'Какой инструмент для отладки React Native?', 'options' => ['React Native Debugger', 'Chrome DevTools', 'Xcode Debugger', 'Android Studio'], 'correct' => 0, 'explanation' => 'React Native Debugger.'],
                ['question' => 'Тип тестирования для UI?', 'options' => ['E2E', 'Unit', 'Интеграционное', 'Нагрузочное'], 'correct' => 0, 'explanation' => 'E2E тестирование.'],
                ['question' => 'Компонент для списка в React Native?', 'options' => ['FlatList', 'ScrollView', 'List', 'Array'], 'correct' => 0, 'explanation' => 'FlatList.'],
            ],
        ],
    ],

    20 => [ // English A1
        'quizzes' => [
            ['question' => 'Как сказать "Привет" по-английски?', 'options' => ['Hello', 'Goodbye', 'Please', 'Thank'], 'correct' => 0, 'explanation' => 'Hello.'],
            ['question' => 'Как спросить имя?', 'options' => ['What is your name?', 'Who are you?', 'Where are you?', 'How are you?'], 'correct' => 0, 'explanation' => 'What is your name?'],
            ['question' => 'Число "пять" по-английски?', 'options' => ['Five', 'Four', 'Six', 'Seven'], 'correct' => 0, 'explanation' => 'Five.'],
            ['question' => 'Артикль "the" используется когда?', 'options' => ['Когда предмет известен', 'Всегда', 'Никогда', 'Только с именами'], 'correct' => 0, 'explanation' => 'С определёнными предметами.'],
            ['question' => 'Как сказать "Я из России"?', 'options' => ['I am from Russia', 'I am Russia', 'I from Russia', 'Me am Russia'], 'correct' => 0, 'explanation' => 'I am from Russia.'],
        ],
        'practices' => [
            ['title' => 'Диалог знакомства', 'instructions' => 'Напишите диалог из 6 реплик, где вы представляетесь и спрашиваете имя собеседника.', 'starter_code' => "A: Hello!\nB: ...\nA: ...\nB: ...\nA: ...\nB: ...", 'solution_code' => "A: Hello!\nB: Hi there!\nA: My name is Alex. What is your name?\nB: I am Maria. Nice to meet you!\nA: Nice to meet you too, Maria! Where are you from?\nB: I am from Spain. And you?", 'tests' => [['input' => '6 реплик в диалоге', 'expected' => 'Диалог из 6 реплик', 'description' => 'Диалог содержит 6 реплик']]],
            ['title' => 'Составление предложений', 'instructions' => 'Переведите 5 предложений с русского на английский, используя правильный порядок слов и артикли.', 'starter_code' => "// 1. Я студент.\n// 2. Это мой друг.\n// 3. Мы из Москвы.\n// 4. Она работает в больнице.\n// 5. Они любят музыку.", 'solution_code' => "// 1. I am a student.\n// 2. This is my friend.\n// 3. We are from Moscow.\n// 4. She works in a hospital.\n// 5. They love music.", 'tests' => [['input' => '5 предложений', 'expected' => '5 правильных переводов', 'description' => 'Все предложения переведены']]],
            ['title' => 'Описание.family по-английски', 'instructions' => 'Напишите абзац (5-7 предложений) о своей семье на английском языке.', 'starter_code' => "// Напишите абзац о семье\n// Используйте: father, mother, brother, sister, family\n// Используйте: is, are, has, works, lives", 'solution_code' => "I have a big family. My father is a teacher and my mother is a doctor. I have one brother and two sisters. My brother is 20 years old and he works in a bank. My sisters are students. We live in a big house. I love my family very much.", 'tests' => [['input' => 'Абзац о семье', 'expected' => '5-7 предложений', 'description' => 'Абзац содержит минимум 5 предложений']]],
        ],
        'exam' => [
            'title' => 'Экзамен по английскому A1',
            'time' => 45,
            'pass' => 70,
            'bank' => [
                ['question' => 'Как сказать "Привет"?', 'options' => ['Hello', 'Goodbye', 'Please', 'Thank'], 'correct' => 0, 'explanation' => 'Hello — привет.'],
                ['question' => 'Как спросить имя?', 'options' => ['What is your name?', 'Who are you?', 'Where are you?', 'How are you?'], 'correct' => 0, 'explanation' => 'What is your name?'],
                ['question' => 'Число "пять"?', 'options' => ['Five', 'Four', 'Six', 'Seven'], 'correct' => 0, 'explanation' => 'Five.'],
                ['question' => 'Артикль "the" используется когда?', 'options' => ['Когда предмет известен', 'Всегда', 'Никогда', 'Только с именами'], 'correct' => 0, 'explanation' => 'С определёнными предметами.'],
                ['question' => '"Я из России"?', 'options' => ['I am from Russia', 'I am Russia', 'I from Russia', 'Me am Russia'], 'correct' => 0, 'explanation' => 'I am from Russia.'],
                ['question' => 'Число "десять"?', 'options' => ['Ten', 'Twelve', 'Eleven', 'Nine'], 'correct' => 0, 'explanation' => 'Ten.'],
                ['question' => '"Она работает"?', 'options' => ['She works', 'She work', 'She working', 'She is work'], 'correct' => 0, 'explanation' => 'She works (3-е лицо -s).'],
                ['question' => '"Мой друг" по-английски?', 'options' => ['My friend', 'A friend my', 'The friend my', 'Friend mine'], 'correct' => 0, 'explanation' => 'My friend.'],
                ['question' => '"Спасибо" по-английски?', 'options' => ['Thank you', 'Please', 'Sorry', 'Hello'], 'correct' => 0, 'explanation' => 'Thank you.'],
                ['question' => '"Я люблю музыку"?', 'options' => ['I love music', 'I loves music', 'I am love music', 'I loving music'], 'correct' => 0, 'explanation' => 'I love music (без -s после I).'],
                ['question' => '"Где ты живёшь?"?', 'options' => ['Where do you live?', 'Where you live?', 'Where are you live?', 'Where does you live?'], 'correct' => 0, 'explanation' => 'Where do you live?'],
                ['question' => '"Он из Москвы"?', 'options' => ['He is from Moscow', 'He from Moscow', 'He is Moscow', 'Him from Moscow'], 'correct' => 0, 'explanation' => 'He is from Moscow.'],
                ['question' => '"Это моя книга"?', 'options' => ['This is my book', 'This my book', 'This is me book', 'This mine book'], 'correct' => 0, 'explanation' => 'This is my book.'],
                ['question' => 'Множественное число "child"?', 'options' => ['Children', 'Childs', 'Childes', 'Childen'], 'correct' => 0, 'explanation' => 'Children (неправильное склонение).'],
                ['question' => '"Мы студенты"?', 'options' => ['We are students', 'We is students', 'We am students', 'We students'], 'correct' => 0, 'explanation' => 'We are students.'],
            ],
        ],
    ],
];
