<?php

namespace Database\Seeders;

use App\Models\InterviewPrepTask;
use Illuminate\Database\Seeder;

class InterviewPrepSeeder extends Seeder
{
    public function run(): void
    {
        if (InterviewPrepTask::count() > 0) return;

        $tasks = [
            [
                'title' => 'Two Sum',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
                'input_spec' => 'An array of integers and a target integer.',
                'output_spec' => 'An array of two indices.',
                'starter_cpp' => 'vector<int> twoSum(vector<int>& nums, int target) {\n    \n}',
                'starter_python' => 'def two_sum(nums, target):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[[2,7,11,15],9]', 'expected' => '[0,1]']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Try using a hash map to store complements.',
                'sort_order' => 1,
            ],
            [
                'title' => 'Reverse String',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Write a function that reverses a string. The input string is given as an array of characters s. You must do this by modifying the input array in-place with O(1) extra memory.',
                'input_spec' => 'An array of characters.',
                'output_spec' => 'The reversed array.',
                'starter_cpp' => 'void reverseString(vector<char>& s) {\n    \n}',
                'starter_python' => 'def reverse_string(s):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '["h","e","l","l","o"]', 'expected' => '["o","l","l","e","h"]']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Use two pointers from both ends.',
                'sort_order' => 2,
            ],
            [
                'title' => 'Valid Parentheses',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Given a string s containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid. An input string is valid if open brackets are closed by the same type of brackets and in the correct order.',
                'input_spec' => 'A string of bracket characters.',
                'output_spec' => 'true or false.',
                'starter_cpp' => 'bool isValid(string s) {\n    \n}',
                'starter_python' => 'def is_valid(s):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '"()"', 'expected' => 'true'], ['input' => '"()[]{}"', 'expected' => 'true'], ['input' => '"(]"', 'expected' => 'false']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Use a stack data structure.',
                'sort_order' => 3,
            ],
            [
                'title' => 'Merge Two Sorted Lists',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.',
                'input_spec' => 'Two sorted linked lists.',
                'output_spec' => 'Merged sorted linked list.',
                'starter_cpp' => 'ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {\n    \n}',
                'starter_python' => 'def merge_two_lists(list1, list2):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[[1,2,4],[1,3,4]]', 'expected' => '[1,1,2,3,4,4]']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Use a dummy node and compare heads.',
                'sort_order' => 4,
            ],
            [
                'title' => 'Best Time to Buy and Sell Stock',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.',
                'input_spec' => 'An array of stock prices.',
                'output_spec' => 'Maximum profit (integer).',
                'starter_cpp' => 'int maxProfit(vector<int>& prices) {\n    \n}',
                'starter_python' => 'def max_profit(prices):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[7,1,5,3,6,4]', 'expected' => '5']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Track the minimum price seen so far.',
                'sort_order' => 5,
            ],
            [
                'title' => 'Maximum Subarray',
                'category' => 'algorithms',
                'difficulty' => 'medium',
                'statement' => 'Given an integer array nums, find the subarray with the largest sum, and return its sum.',
                'input_spec' => 'An array of integers.',
                'output_spec' => 'Maximum sum (integer).',
                'starter_cpp' => 'int maxSubArray(vector<int>& nums) {\n    \n}',
                'starter_python' => 'def max_sub_array(nums):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[-2,1,-3,4,-1,2,1,-5,4]', 'expected' => '6']],
                'time_limit_sec' => 3,
                'memory_limit_kb' => 256000,
                'hints' => 'Kadane\'s algorithm: track current and global maximum.',
                'sort_order' => 6,
            ],
            [
                'title' => 'Binary Search',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return -1. You must write an algorithm with O(log n) runtime complexity.',
                'input_spec' => 'A sorted array and a target integer.',
                'output_spec' => 'Index of target or -1.',
                'starter_cpp' => 'int search(vector<int>& nums, int target) {\n    \n}',
                'starter_python' => 'def search(nums, target):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[-1,0,3,5,9,12],9', 'expected' => '4']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Use left and right pointers.',
                'sort_order' => 7,
            ],
            [
                'title' => 'FizzBuzz',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Given an integer n, return a string array answer (1-indexed) where: answer[i] == "FizzBuzz" if i is divisible by 3 and 5. answer[i] == "Fizz" if i is divisible by 3. answer[i] == "Buzz" if i is divisible by 5. answer[i] == i (as a string) if none of the above conditions are true.',
                'input_spec' => 'An integer n.',
                'output_spec' => 'An array of strings.',
                'starter_cpp' => 'vector<string> fizzBuzz(int n) {\n    \n}',
                'starter_python' => 'def fizz_buzz(n):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '15', 'expected' => '["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Check divisibility by 3 and 5 separately.',
                'sort_order' => 8,
            ],
            [
                'title' => 'Climbing Stairs',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
                'input_spec' => 'An integer n (1 <= n <= 45).',
                'output_spec' => 'Number of distinct ways.',
                'starter_cpp' => 'int climbStairs(int n) {\n    \n}',
                'starter_python' => 'def climb_stairs(n):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '2', 'expected' => '2'], ['input' => '3', 'expected' => '3']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'This is a Fibonacci-like sequence.',
                'sort_order' => 9,
            ],
            [
                'title' => 'Contains Duplicate',
                'category' => 'algorithms',
                'difficulty' => 'easy',
                'statement' => 'Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.',
                'input_spec' => 'An array of integers.',
                'output_spec' => 'true or false.',
                'starter_cpp' => 'bool containsDuplicate(vector<int>& nums) {\n    \n}',
                'starter_python' => 'def contains_duplicate(nums):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[1,2,3,1]', 'expected' => 'true'], ['input' => '[1,2,3,4]', 'expected' => 'false']],
                'time_limit_sec' => 2,
                'memory_limit_kb' => 256000,
                'hints' => 'Use a HashSet to track seen elements.',
                'sort_order' => 10,
            ],
            [
                'title' => 'Group Anagrams',
                'category' => 'algorithms',
                'difficulty' => 'medium',
                'statement' => 'Given an array of strings strs, group the anagrams together. You can return the answer in any order. An anagram is a word or phrase formed by rearranging the letters of a different word.',
                'input_spec' => 'An array of strings.',
                'output_spec' => 'A list of groups of anagrams.',
                'starter_cpp' => 'vector<vector<string>> groupAnagrams(vector<string>& strs) {\n    \n}',
                'starter_python' => 'def group_anagrams(strs):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '["eat","tea","tan","ate","nat","bat"]', 'expected' => '[["eat","tea","ate"],["tan","nat"],["bat"]]']],
                'time_limit_sec' => 3,
                'memory_limit_kb' => 256000,
                'hints' => 'Use sorted string as a key in a hash map.',
                'sort_order' => 11,
            ],
            [
                'title' => 'Coin Change',
                'category' => 'algorithms',
                'difficulty' => 'medium',
                'statement' => 'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount.',
                'input_spec' => 'Array of coin denominations and target amount.',
                'output_spec' => 'Minimum number of coins or -1.',
                'starter_cpp' => 'int coinChange(vector<int>& coins, int amount) {\n    \n}',
                'starter_python' => 'def coin_change(coins, amount):\n    pass',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '[[1,2,5],11]', 'expected' => '3']],
                'time_limit_sec' => 3,
                'memory_limit_kb' => 256000,
                'hints' => 'Use dynamic programming bottom-up.',
                'sort_order' => 12,
            ],
            [
                'title' => 'FizzBuzz (SQL)',
                'category' => 'sql',
                'difficulty' => 'easy',
                'statement' => 'Write a SQL query to generate FizzBuzz numbers from 1 to 100.',
                'input_spec' => 'No input, generate numbers 1-100.',
                'output_spec' => 'FizzBuzz output for each number.',
                'starter_cpp' => '',
                'starter_python' => '',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => '', 'expected' => '1, 2, Fizz, 4, Buzz, ...']],
                'time_limit_sec' => 5,
                'memory_limit_kb' => 256000,
                'hints' => 'Use CASE WHEN with MOD function.',
                'sort_order' => 13,
            ],
            [
                'title' => 'SELECT Average Salary',
                'category' => 'sql',
                'difficulty' => 'easy',
                'statement' => 'Write a SQL query to find the average salary of employees from each department.',
                'input_spec' => 'Employees table with id, name, salary, department_id.',
                'output_spec' => 'Department name and average salary.',
                'starter_cpp' => '',
                'starter_python' => '',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => 'employees table', 'expected' => 'department, avg_salary']],
                'time_limit_sec' => 5,
                'memory_limit_kb' => 256000,
                'hints' => 'Use GROUP BY with AVG() aggregate function.',
                'sort_order' => 14,
            ],
            [
                'title' => 'React Counter Component',
                'category' => 'frontend',
                'difficulty' => 'easy',
                'statement' => 'Create a React counter component that increments and decrements a count value. Include a reset button.',
                'input_spec' => 'No input, render the component.',
                'output_spec' => 'A working counter component.',
                'starter_cpp' => '',
                'starter_python' => '',
                'starter_c' => '',
                'starter_csharp' => '',
                'starter_java' => '',
                'tests_json' => [['input' => 'Click increment', 'expected' => 'count increases by 1']],
                'time_limit_sec' => 10,
                'memory_limit_kb' => 256000,
                'hints' => 'Use useState hook for state management.',
                'sort_order' => 15,
            ],
        ];

        foreach ($tasks as $task) {
            InterviewPrepTask::create($task);
        }
    }
}
