<?php

$startCreateUser = "CREATE TABLE users (\n    id SERIAL PRIMARY KEY,\n    username VARCHAR(50) UNIQUE NOT NULL,\n    email VARCHAR(100) NOT NULL,\n    created_at TIMESTAMP DEFAULT NOW()\n);\n\nINSERT INTO users (username, email) VALUES\n    ('alice', 'alice@example.com'),\n    ('bob', 'bob@example.com'),\n    ('charlie', 'charlie@example.com');";

$startWindowFn = "CREATE TABLE sales (\n    id SERIAL PRIMARY KEY,\n    employee VARCHAR(50),\n    department VARCHAR(50),\n    amount DECIMAL(10,2),\n    sale_date DATE\n);\n\nINSERT INTO sales (employee, department, amount, sale_date) VALUES\n    ('Alice', 'Electronics', 1500.00, '2024-01-15'),\n    ('Bob', 'Electronics', 2300.00, '2024-02-20'),\n    ('Alice', 'Electronics', 800.00, '2024-03-10'),\n    ('Charlie', 'Clothing', 1200.00, '2024-01-25'),\n    ('Bob', 'Clothing', 950.00, '2024-04-05'),\n    ('Alice', 'Clothing', 1700.00, '2024-02-14');";

$startJson = "CREATE TABLE products (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100),\n    attributes JSONB\n);\n\nINSERT INTO products (name, attributes) VALUES\n    ('Laptop', '{\"brand\": \"Dell\", \"ram\": 16}'),\n    ('Phone', '{\"brand\": \"Samsung\", \"ram\": 8}'),\n    ('Tablet', '{\"brand\": \"Apple\", \"ram\": 6}');";

$startCppBasics = "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int age = 25;\n    string name = \"Alice\";\n    double salary = 50000.50;\n    cout << \"Name: \" << name << endl;\n    cout << \"Age: \" << age << endl;\n    cout << \"Salary: \" << salary << endl;\n    return 0;\n}";

$startCppMemory = "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int data;\n    Node* next;\n};\n\nint main() {\n    Node* head = new Node;\n    head->data = 10;\n    head->next = nullptr;\n    Node* second = new Node;\n    second->data = 20;\n    second->next = nullptr;\n    head->next = second;\n    return 0;\n}";

$startCppOop = "#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Animal {\npublic:\n    string name;\n    int age;\n    void speak() {\n        cout << name << \" makes a sound\" << endl;\n    }\n};\n\nint main() {\n    Animal a;\n    a.name = \"Dog\";\n    a.age = 3;\n    a.speak();\n    return 0;\n}";

$startCppTemplates = "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\ntemplate <typename T>\nT findMax(T a, T b) {\n    return (a > b) ? a : b;\n}\n\nint main() {\n    cout << findMax(5, 10) << endl;\n    vector<int> nums = {5, 2, 8, 1, 9};\n    sort(nums.begin(), nums.end());\n    for (int n : nums) cout << n << \" \";\n    return 0;\n}";

$startCppFiles = "#include <iostream>\n#include <fstream>\n#include <string>\nusing namespace std;\n\nint main() {\n    ofstream outFile(\"output.txt\");\n    outFile << \"Hello, File!\" << endl;\n    outFile.close();\n    ifstream inFile(\"output.txt\");\n    string line;\n    while (getline(inFile, line)) {\n        cout << line << endl;\n    }\n    inFile.close();\n    return 0;\n}";

$startPyBasics = "# Python basics\nname = \"Alice\"\nage = 25\nheight = 5.6\nis_student = True\nfruits = [\"apple\", \"banana\", \"cherry\"]\nperson = {\"name\": name, \"age\": age}\nprint(f\"Hello, {name}!\")\n# TODO: Add for loop and while loop";

$startPyOop = "class Car:\n    def __init__(self, make, model, year):\n        self.make = make\n        self.model = model\n        self.year = year\n    def drive(self, miles):\n        return f\"Drove {miles} miles\"\n    def get_info(self):\n        return f\"{self.year} {self.make} {self.model}\"\n\nclass ElectricCar(Car):\n    def __init__(self, make, model, year, battery_kwh):\n        super().__init__(make, model, year)\n        self.battery_kwh = battery_kwh\n    def charge(self):\n        return f\"Charging {self.battery_kwh}kWh battery\"";

$startPyModules = "import math\nimport random\nfrom datetime import datetime, timedelta\nfrom collections import Counter\nprint(f\"Pi: {math.pi}\")\nnums = [random.randint(1, 100) for _ in range(10)]\nprint(f\"Random: {nums}\")";

$startPyFiles = "import json\nimport csv\nwith open('diary.txt', 'w') as f:\n    f.write('Day 1: Started learning Python\\n')\nwith open('diary.txt', 'r') as f:\n    print(f.read())\ndata = {\"students\": [{\"name\": \"Alice\", \"grade\": 95}]}\nwith open('students.json', 'w') as f:\n    json.dump(data, f, indent=2)";

$startPyPars = "from bs4 import BeautifulSoup\nhtml = '<div class=\"book-list\"><div class=\"book\"><h2>Python Crash Course</h2><span class=\"author\">Eric Matthes</span></div></div>'\nsoup = BeautifulSoup(html, 'html.parser')\nbooks = soup.find_all('div', class_='book')\nfor book in books:\n    title = book.find('h2').text\n    print(f\"{title}\")";

$startPyDecorators = "import time\nfrom functools import wraps\ndef timer(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f\"{func.__name__} took {time.time()-start:.4f}s\")\n        return result\n    return wrapper\ndef fibonacci(limit):\n    a, b = 0, 1\n    while a < limit:\n        yield a\n        a, b = b, a + b";

$startJavaBasics = "public class Main {\n    public static void main(String[] args) {\n        int age = 25;\n        String name = \"Alice\";\n        int[] numbers = {1, 2, 3, 4, 5};\n        System.out.println(\"Name: \" + name);\n    }\n}";

$startJavaOop = "class Animal {\n    protected String name;\n    protected int age;\n    public Animal(String name, int age) {\n        this.name = name;\n        this.age = age;\n    }\n    public void speak() {\n        System.out.println(name + \" makes a sound\");\n    }\n}\nclass Dog extends Animal {\n    private String breed;\n    public Dog(String name, int age, String breed) {\n        super(name, age);\n        this.breed = breed;\n    }\n    @Override\n    public void speak() {\n        System.out.println(name + \" barks\");\n    }\n}";

$startJavaCollections = "import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        List<String> names = new ArrayList<>();\n        names.add(\"Alice\");\n        names.add(\"Bob\");\n        Map<String, Integer> scores = new HashMap<>();\n        scores.put(\"Alice\", 95);\n    }\n}";

$startJavaThreads = "class Counter {\n    private int count = 0;\n    public synchronized void increment() { count++; }\n    public int getCount() { return count; }\n}\nclass Worker extends Thread {\n    private Counter counter;\n    public Worker(Counter c) { this.counter = c; }\n    @Override\n    public void run() {\n        for (int i = 0; i < 1000; i++) counter.increment();\n    }\n}";

$startCSharpBasics = "using System;\nusing System.Collections.Generic;\nclass Program {\n    static void Main() {\n        int age = 25;\n        string name = \"Alice\";\n        int[] numbers = {1, 2, 3, 4, 5};\n        List<string> names = new List<string> {\"Alice\", \"Bob\"};\n        Console.WriteLine($\"Name: {name}\");\n    }\n}";

$startCSharpOop = "using System;\nabstract class Shape {\n    public string Name { get; set; }\n    protected Shape(string n) { Name = n; }\n    public abstract double Area();\n    public abstract double Perimeter();\n}\nclass Circle : Shape {\n    public double Radius { get; set; }\n    public Circle(double r) : base(\"Circle\") { Radius = r; }\n    public override double Area() => Math.PI * Radius * Radius;\n    public override double Perimeter() => 2 * Math.PI * Radius;\n}\nclass Rectangle : Shape {\n    public double Width { get; set; }\n    public double Height { get; set; }\n    public Rectangle(double w, double h) : base(\"Rectangle\") { Width = w; Height = h; }\n    public override double Area() => Width * Height;\n    public override double Perimeter() => 2 * (Width + Height);\n}";

$startCSharpLinq = "using System;\nusing System.Linq;\nusing System.Collections.Generic;\nclass Student {\n    public string Name { get; set; }\n    public int Grade { get; set; }\n    public string Department { get; set; }\n}\nclass Program {\n    static void Main() {\n        List<Student> students = new List<Student> {\n            new Student { Name = \"Alice\", Grade = 95, Department = \"CS\" },\n            new Student { Name = \"Bob\", Grade = 87, Department = \"Math\" }\n        };\n        var csStudents = students.Where(s => s.Department == \"CS\");\n        foreach (var s in csStudents) Console.WriteLine($\"{s.Name}: {s.Grade}\");\n    }\n}";

$startCSharpDelegates = "using System;\ndelegate void LogHandler(string message);\nclass OrderEventArgs : EventArgs {\n    public string Product { get; set; }\n    public decimal Amount { get; set; }\n}\nclass OrderService {\n    public event EventHandler<OrderEventArgs> OrderPlaced;\n    public void PlaceOrder(string product, decimal amount) {\n        OrderPlaced?.Invoke(this, new OrderEventArgs { Product = product, Amount = amount });\n    }\n}";
return [
    6 => [
        'lessons' => [
            'Установка и настройка PostgreSQL' => '<h2>Установка и настройка PostgreSQL</h2><p>PostgreSQL — мощная объектно-реляционная СУБД с открытым исходным кодом.</p><h3>Установка</h3><h4>Windows</h4><pre><code># Скачайте установщик с postgresql.org\n# Запустите postgresql-x.x.x-windows.exe\n# Укажите порт 5432\n# Задайте пароль postgres\n# Установите pgAdmin</code></pre><h4>Linux</h4><pre><code>sudo apt update\nsudo apt install postgresql postgresql-contrib\nsudo systemctl start postgresql\nsudo systemctl enable postgresql</code></pre><h4>macOS</h4><pre><code>brew install postgresql\nbrew services start postgresql</code></pre><h3>Команды psql</h3><pre><code>psql -U postgres\nCREATE DATABASE mydb;\n\\c mydb\n\\dt\n\\d table_name\n\\q</code></pre><h3>Настройка</h3><pre><code># postgresql.conf\nlisten_addresses = \'*\'\nport = 5432\nmax_connections = 100\nshared_buffers = 128MB</code></pre><h3>Роли</h3><pre><code>CREATE ROLE admin WITH LOGIN PASSWORD \'secret\' CREATEDB;\nGRANT ALL PRIVILEGES ON DATABASE mydb TO admin;\n\\du</code></pre><h3>Бэкап</h3><pre><code>pg_dump -U postgres mydb > backup.sql\npsql -U postgres mydb < backup.sql\npg_dump -U postgres -Fc mydb > backup.dump</code></pre>',
            'Расширенные типы данных' => '<h2>Расширенные типы данных PostgreSQL</h2><h3>Составные типы</h3><pre><code>CREATE TYPE address AS (\n    street VARCHAR(100),\n    city VARCHAR(50),\n    zip VARCHAR(10)\n);\nCREATE TABLE customers (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100),\n    home_address address\n);</code></pre><h3>Массивы</h3><pre><code>CREATE TABLE products (\n    id SERIAL PRIMARY KEY,\n    tags TEXT[],\n    prices NUMERIC(10,2)[]\n);\nINSERT INTO products (tags, prices)\nVALUES (ARRAY[\'electronics\', \'portable\'], ARRAY[999.99, 899.99]);\nSELECT tags[1] FROM products;\nSELECT * FROM products WHERE \'electronics\' = ANY(tags);</code></pre><h3>Диапазоны</h3><pre><code>CREATE TABLE reservations (\n    id SERIAL PRIMARY KEY,\n    during TSRANGE,\n    EXCLUDE USING GIST (duration WITH &&)\n);</code></pre><h3>JSONB</h3><pre><code>CREATE TABLE events (\n    id SERIAL PRIMARY KEY,\n    data JSONB\n);\nINSERT INTO events (data) VALUES (\'{"type": "click", "x": 100}\');\nSELECT data->>\'type\' FROM events;\nSELECT * FROM events WHERE data @>\'{"type": "click"}\';</code></pre><h3>Полнотекстовый поиск</h3><pre><code>ALTER TABLE products ADD COLUMN search_vector TSVECTOR;\nUPDATE products SET search_vector = to_tsvector(\'english\', name);\nCREATE INDEX idx_search ON products USING GIN (search_vector);\nSELECT * FROM products WHERE search_vector @@ to_tsquery(\'english\', \'laptop\');</code></pre>',
            'CTE и оконные функции' => '<h2>CTE и оконные функции</h2><h3>CTE</h3><pre><code>WITH RECURSIVE numbers AS (\n    SELECT 1 AS n\n    UNION ALL\n    SELECT n + 1 FROM numbers WHERE n < 10\n)\nSELECT n FROM numbers;</code></pre><h3>Оконные функции</h3><pre><code>SELECT name, department, salary,\n    ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS row_num,\n    RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS rank\nFROM employees;</code></pre><h3>LAG и LEAD</h3><pre><code>SELECT month, revenue,\n    LAG(revenue, 1) OVER (ORDER BY month) AS prev_month,\n    LEAD(revenue, 1) OVER (ORDER BY month) AS next_month\nFROM monthly_revenue;</code></pre><h3>Накопительный итог</h3><pre><code>SELECT sale_date, amount,\n    SUM(amount) OVER (ORDER BY sale_date) AS cumulative_sum\nFROM sales;</code></pre>',
            'JSON и полнотекстовый поиск' => '<h2>JSON и полнотекстовый поиск</h2><h3>Операторы JSONB</h3><pre><code>SELECT response->>\'status\' FROM api_logs;\nSELECT response->\'data\'->>\'name\' FROM api_logs;\nSELECT * FROM api_logs WHERE response ? \'status\';\nSELECT * FROM api_logs WHERE response @>\'{"status": 200}\';\nUPDATE api_logs SET response = jsonb_set(response, \'{status}\', \'404\');</code></pre><h3>Индексы</h3><pre><code>CREATE INDEX idx_logs ON api_logs USING GIN (response);\nCREATE INDEX idx_status ON api_logs USING BTREE ((response->>\'status\'));</code></pre><h3>Полнотекстовый поиск</h3><pre><code>ALTER TABLE articles ADD COLUMN search_vector TSVECTOR;\nUPDATE articles SET search_vector =\n    setweight(to_tsvector(\'english\', coalesce(title, \'\')), \'A\') ||\n    setweight(to_tsvector(\'english\', coalesce(content, \'\')), \'B\');\nCREATE INDEX idx_search ON articles USING GIN (search_vector);\nSELECT title, ts_rank(search_vector, query) AS rank\nFROM articles, to_tsquery(\'english\', \'postgresql & performance\') query\nWHERE search_vector @@ query ORDER BY rank DESC;</code></pre>',
            'Тест по PostgreSQL' => '<h2>Тест по PostgreSQL</h2><p>Проверьте знания PostgreSQL: установка, типы данных, CTE, оконные функции, JSON, полнотекстовый поиск.</p>',
        ],
        'quizzes' => [
            'Установка и настройка PostgreSQL' => [
                ['q' => 'Какой порт по умолчанию использует PostgreSQL?', 'o' => ['3306', '5432', '8080', '27017', '1433'], 'c' => 1, 'e' => 'PostgreSQL использует порт 5432.'],
                ['q' => 'Какой файл управляет аутентификацией?', 'o' => ['postgresql.conf', 'pg_hba.conf', 'pg_ident.conf', 'pg_pass.conf', 'pg_auth.conf'], 'c' => 1, 'e' => 'pg_hba.conf определяет аутентификацию клиентов.'],
                ['q' => 'Как показать список таблиц в psql?', 'o' => ['\\l', '\\dt', '\\du', '\\ds', '\\d'], 'c' => 1, 'e' => '\\dt показывает список таблиц.'],
                ['q' => 'Как создать бэкап базы?', 'o' => ['pg_backup mydb', 'pg_dump -U postgres mydb > backup.sql', 'pg_copy mydb backup.sql', 'pgsave mydb', 'backup-db mydb'], 'c' => 1, 'e' => 'pg_dump создаёт резервную копию.'],
                ['q' => 'Какой параметр задаёт буферы общей памяти?', 'o' => ['work_mem', 'shared_buffers', 'effective_cache_size', 'maintenance_work_mem', 'wal_buffers'], 'c' => 1, 'e' => 'shared_buffers определяет размер кэша.'],
            ],
            'Расширенные типы данных' => [
                ['q' => 'Какой тип лучше для JSON с запросами?', 'o' => ['JSON', 'JSONB', 'TEXT', 'XML', 'JSONB и TEXT'], 'c' => 1, 'e' => 'JSONB — бинарный формат с поддержкой индексов.'],
                ['q' => 'Как добавить элемент в массив?', 'o' => ['array_append()', 'array_add()', 'push()', 'insert()', 'append()'], 'c' => 0, 'e' => 'array_append() добавляет элемент в конец.'],
                ['q' => 'Какой оператор проверяет ключ в JSONB?', 'o' => ['->', '->>', '?', '@>', '#>'], 'c' => 2, 'e' => 'Оператор ? проверяет наличие ключа.'],
                ['q' => 'Какой тип диапазона для временных меток?', 'o' => ['NUMRANGE', 'DATERANGE', 'TSRANGE', 'INT4RANGE', 'TSTZRANGE'], 'c' => 2, 'e' => 'TSRANGE для интервалов без часового пояса.'],
                ['q' => 'Как создать составной тип?', 'o' => ['CREATE COMPOSITE TYPE', 'CREATE TYPE', 'CREATE STRUCT', 'DEFINE TYPE', 'NEW TYPE'], 'c' => 1, 'e' => 'CREATE TYPE ... AS (...).'],
            ],
            'CTE и оконные функции' => [
                ['q' => 'Какое ключевое слово делает CTE рекурсивным?', 'o' => ['LOOP', 'RECURSIVE', 'REPEAT', 'ITERATE', 'CYCLE'], 'c' => 1, 'e' => 'WITH RECURSIVE.'],
                ['q' => 'Какая функция присваивает уникальный номер?', 'o' => ['RANK()', 'DENSE_RANK()', 'ROW_NUMBER()', 'NTILE()', 'PERCENT_RANK()'], 'c' => 2, 'e' => 'ROW_NUMBER() — уникальный номер без пропусков.'],
                ['q' => 'Что делает LAG() без второго аргумента?', 'o' => ['Текущую строку', 'NULL', 'Первую строку', 'Последнюю строку', 'Ошибку'], 'c' => 1, 'e' => 'Возвращает NULL по умолчанию.'],
                ['q' => 'Какое предложение задаёт набор строк?', 'o' => ['WHERE', 'GROUP BY', 'PARTITION BY', 'ORDER BY', 'HAVING'], 'c' => 2, 'e' => 'PARTITION BY разделяет строки на группы.'],
                ['q' => 'Как получить накопительный итог?', 'o' => ['SUM() OVER (ORDER BY date)', 'COUNT(*) OVER ()', 'MAX() OVER ()', 'AVG() OVER ()', 'FIRST_VALUE()'], 'c' => 0, 'e' => 'SUM() OVER (ORDER BY ...) — running total.'],
            ],
            'JSON и полнотекстовый поиск' => [
                ['q' => 'Какой оператор извлекает текст из JSONB?', 'o' => ['->', '->>', '#>', '#>>', '@>'], 'c' => 1, 'e' => '->> извлекает как текст.'],
                ['q' => 'Какой индекс лучше для полнотекстового поиска?', 'o' => ['B-tree', 'Hash', 'GIN', 'GiST', 'BRIN'], 'c' => 2, 'e' => 'GIN оптимален для полнотекстовых запросов.'],
                ['q' => 'Какая функция создаёт tsvector?', 'o' => ['to_tsquery()', 'to_tsvector()', 'plainto_tsquery()', 'phraseto_tsquery()', 'ts_rank()'], 'c' => 1, 'e' => 'to_tsvector() разбивает текст на токены.'],
                ['q' => 'Что делает @> для JSONB?', 'o' => ['Извлекает', 'Удаляет', 'Проверяет вхождение подобъекта', 'Обновляет', 'Сортирует'], 'c' => 2, 'e' => '@> проверяет вхождение подмножества.'],
                ['q' => 'Как задать веса для поиска?', 'o' => ['setweight()', 'weight()', 'priority()', 'rank()', 'score()'], 'c' => 0, 'e' => 'setweight() назначает вес A-D.'],
            ],
        ],
        'practice' => [
            'Установка и настройка PostgreSQL' => [
                ['lang' => 'sql', 'title' => 'Создание базы данных и ролей', 'prompt' => 'Создайте базу данных school, роль teacher с паролем teacher123 и grants.', 'out' => 'Database and role created.', 'start' => $startCreateUser, 'tests' => [['contains', 'CREATE ROLE'], ['contains', 'GRANT']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'sql', 'title' => 'Таблица студентов', 'prompt' => 'В базе school создайте таблицу students: id serial, name varchar 100, grade integer, enrollment_date date.', 'out' => 'Table created.', 'start' => 'CREATE DATABASE school;\n\\c school\n\n-- Create students table', 'tests' => [['contains', 'CREATE TABLE'], ['contains', 'serial'], ['contains', 'PRIMARY KEY']], 'diff' => 'easy', 'time' => 10],
                ['lang' => 'sql', 'title' => 'Экспорт через pg_dump', 'prompt' => 'Напишите команду экспорта mydb в формате custom (-Fc).', 'out' => 'pg_dump -U postgres -Fc mydb > backup.dump', 'start' => '# Write pg_dump command', 'tests' => [['contains', 'pg_dump'], ['-Fc']], 'diff' => 'easy', 'time' => 5],
            ],
            'Расширенные типы данных' => [
                ['lang' => 'sql', 'title' => 'Таблица с JSONB', 'prompt' => 'Создайте таблицу events: id, event_type varchar 50, payload jsonb, created_at timestamp. Вставьте 3 записи.', 'out' => 'Table created with 3 rows.', 'start' => 'CREATE TABLE events (\n    id SERIAL PRIMARY KEY,\n    event_type VARCHAR(50),\n    payload JSONB,\n    created_at TIMESTAMP DEFAULT NOW()\n);\n\n-- Insert 3 events', 'tests' => [['contains', 'INSERT INTO'], ['contains', 'payload']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'sql', 'title' => 'Составные типы', 'prompt' => 'Создайте тип address (street, city, zip). Таблицу stores с address. Вставьте 2 записи.', 'out' => 'Type and table created.', 'start' => '-- Create address type\n-- Create stores table\n-- Insert 2 records', 'tests' => [['contains', 'CREATE TYPE'], ['contains', 'AS']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'sql', 'title' => 'Запросы JSONB', 'prompt' => 'Извлеките тип события как текст, найдите с ключом user_id, добавьте processed field.', 'out' => 'Three JSONB queries.', 'start' => $startJson, 'tests' => [['contains', '->>'], ['contains', '?'], ['contains', 'jsonb_set']], 'diff' => 'hard', 'time' => 25],
            ],
            'CTE и оконные функции' => [
                ['lang' => 'sql', 'title' => 'Рекурсивный CTE', 'prompt' => 'Генерация чисел 1-20, выведите чётные.', 'out' => 'Even numbers generated.', 'start' => 'WITH RECURSIVE numbers AS (\n    SELECT 1 AS n\n    UNION ALL\n    SELECT n + 1 FROM numbers WHERE n < 20\n)\nSELECT n FROM numbers WHERE n % 2 = 0;', 'tests' => [['contains', 'RECURSIVE'], ['contains', 'UNION ALL']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'sql', 'title' => 'Оконные функции продаж', 'prompt' => 'Используйте ROW_NUMBER, RANK и LAG для анализа продаж.', 'out' => 'Window functions applied.', 'start' => $startWindowFn, 'tests' => [['contains', 'ROW_NUMBER()'], ['contains', 'RANK()'], ['contains', 'LAG()']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'sql', 'title' => 'Иерархия сотрудников', 'prompt' => 'Найдите всех подчинённых руководителя id=1.', 'out' => 'Subordinates found.', 'start' => 'CREATE TABLE employees (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(50),\n    manager_id INT REFERENCES employees(id)\n);\nINSERT INTO employees (name, manager_id) VALUES\n    (\'Director\', NULL),\n    (\'Manager A\', 1),\n    (\'Manager B\', 1),\n    (\'Worker 1\', 2),\n    (\'Worker 2\', 3);', 'tests' => [['contains', 'WITH RECURSIVE'], ['contains', 'JOIN']], 'diff' => 'hard', 'time' => 20],
            ],
            'JSON и полнотекстовый поиск' => [
                ['lang' => 'sql', 'title' => 'Индексация JSONB', 'prompt' => 'Создайте GIN индекс для attrs и индекс для brand.', 'out' => 'Indexes created.', 'start' => 'CREATE TABLE products (\n    id SERIAL PRIMARY KEY,\n    name VARCHAR(100),\n    attrs JSONB\n);\n\n-- Create GIN index\n-- Create index for brand', 'tests' => [['contains', 'GIN'], ['contains', 'USING']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'sql', 'title' => 'Полнотекстовый поиск', 'prompt' => 'Добавьте search_vector, заполните с весами A/B, создайте GIN индекс и запрос.', 'out' => 'Full-text search setup.', 'start' => 'CREATE TABLE articles (\n    id SERIAL PRIMARY KEY,\n    title VARCHAR(200),\n    body TEXT\n);\nINSERT INTO articles (title, body) VALUES\n    (\'PostgreSQL Tips\', \'Learn advanced features\'),\n    (\'SQL Performance\', \'Optimize queries\');\n\n-- Add search_vector\n-- Update with weights\n-- Create GIN index\n-- Search query', 'tests' => [['contains', 'TSVECTOR'], ['contains', 'setweight'], ['contains', 'GIN']], 'diff' => 'hard', 'time' => 30],
                ['lang' => 'sql', 'title' => 'JSONB запросы', 'prompt' => 'Найдите brand=Dell, ram>8, и продукты с ключом cpu.', 'out' => 'Three JSONB queries.', 'start' => $startJson, 'tests' => [['contains', '->>'], ['contains', '#>>']], 'diff' => 'medium', 'time' => 20],
            ],
        ],
    ],
    7 => [
        'lessons' => [
            'Основы C++' => '<h2>Основы C++</h2><p>C++ — компилируемый статически типизированный язык общего назначения.</p><h3>Структура</h3><pre><code>#include &lt;iostream&gt;\n#include &lt;string&gt;\nusing namespace std;\nint main() {\n    int age = 25;\n    string name = \"Alice\";\n    double pi = 3.14159;\n    cout &lt;&lt; \"Hello, \" &lt;&lt; name &lt;&lt; endl;\n    return 0;\n}</code></pre><h3>Управление</h3><pre><code>if (age &gt;= 18) { cout &lt;&lt; \"Adult\"; }\nswitch (grade) { case \'A\': break; default: break; }\nfor (int i = 0; i &lt; 10; i++) { cout &lt;&lt; i; }\nwhile (count &lt; 5) { count++; }</code></pre><h3>Функции</h3><pre><code>int add(int a, int b) { return a + b; }\ntemplate &lt;typename T&gt;\nT getMax(T a, T b) { return (a &gt; b) ? a : b; }</code></pre><h3>Ссылки и указатели</h3><pre><code>int x = 10;\nint&amp; ref = x;\nint* ptr = &amp;x;\nconst int MAX = 100;</code></pre>',
            'Управление памятью' => '<h2>Управление памятью</h2><h3>Стек и куча</h3><pre><code>void stackExample() { int local = 42; }\nvoid heapExample() {\n    int* dynamic = new int(42);\n    int* arr = new int[10];\n    delete dynamic;\n    delete[] arr;\n}</code></pre><h3>Умные указатели</h3><pre><code>#include &lt;memory&gt;\nauto ptr = make_unique&lt;int&gt;(42);\nauto shared = make_shared&lt;int&gt;(42);\nweak_ptr&lt;int&gt; weak = shared;</code></pre><h3>RAII</h3><pre><code>class FileHandle {\n    FILE* file;\npublic:\n    FileHandle(const char* path) { file = fopen(path, \"r\"); }\n    ~FileHandle() { if (file) fclose(file); }\n    FileHandle(const FileHandle&amp;) = delete;\n};</code></pre>',
            'ООП в C++' => '<h2>ООП в C++</h2><h3>Классы</h3><pre><code>class Animal {\nprivate:\n    string name;\npublic:\n    Animal(string n) : name(n) {}\n    virtual void speak() const { cout &lt;&lt; name &lt;&lt; \" makes a sound\"; }\n    virtual double getSpeed() const = 0;\n};</code></pre><h3>Наследование</h3><pre><code>class Dog : public Animal {\n    string breed;\npublic:\n    Dog(string n, string b) : Animal(n), breed(b) {}\n    void speak() const override { cout &lt;&lt; \"barks\"; }\n};</code></pre><h3>Полиморфизм</h3><pre><code>void makeAnimalSpeak(const Animal* a) { a-&gt;speak(); }\nDog dog(\"Rex\", \"Husky\");\nmakeAnimalSpeak(&amp;dog);</code></pre>',
            'Шаблоны и STL' => '<h2>Шаблоны и STL</h2><h3>Шаблоны</h3><pre><code>template &lt;typename T&gt;\nT findMax(T a, T b) { return (a &gt; b) ? a : b; }</code></pre><h3>STL контейнеры</h3><pre><code>vector&lt;int&gt; v = {5, 2, 8};\nsort(v.begin(), v.end());\nlist&lt;string&gt; lst = {\"a\", \"b\"};\nmap&lt;string, int&gt; m = {{\"Alice\", 95}};\nset&lt;int&gt; s = {1, 2, 3, 3};</code></pre><h3>Алгоритмы</h3><pre><code>#include &lt;algorithm&gt;\nsort(v.begin(), v.end(), greater&lt;int&gt;());\nauto it = find(v.begin(), v.end(), 8);\ntransform(v.begin(), v.end(), v.begin(), [](int x) { return x * 2; });</code></pre>',
            'Работа с файлами' => '<h2>Работа с файлами</h2><h3>Запись</h3><pre><code>#include &lt;fstream&gt;\nofstream outFile(\"output.txt\");\noutFile &lt;&lt; \"Hello\" &lt;&lt; endl;\noutFile.close();</code></pre><h3>Чтение</h3><pre><code>ifstream inFile(\"input.txt\");\nstring line;\nwhile (getline(inFile, line)) {\n    cout &lt;&lt; line &lt;&lt; endl;\n}</code></pre><h3>Бинарные</h3><pre><code>Record r = {1, \"Alice\", 99.9};\nofstream binOut(\"data.bin\", ios::binary);\nbinOut.write(reinterpret_cast&lt;char*&gt;(&amp;r), sizeof(Record));</code></pre>',
            'Тест по C++' => '<h2>Тест по C++</h2><p>Проверьте знания: основы, управление памятью, ООП, шаблоны/STL, файлы.</p>',
        ],
        'quizzes' => [
            'Основы C++' => [
                ['q' => 'Какой оператор выделяет память?', 'o' => ['malloc()', 'new', 'alloc()', 'create()', 'new[]'], 'c' => 1, 'e' => 'new выделяет память в куче и вызывает конструктор.'],
                ['q' => 'Что делает оператор &?', 'o' => ['Побитовое И', 'Адрес операнда', 'Ссылка', 'ИЛИ', 'Разыменование'], 'c' => 1, 'e' => '& получает адрес переменной.'],
                ['q' => 'Как объявить константу?', 'o' => ['var x = 10', 'const int x = 10', 'final int x = 10', 'define x = 10', 'let x = 10'], 'c' => 1, 'e' => 'const создаёт константу.'],
                ['q' => 'Какой заголовок для ввода-вывода?', 'o' => ['stdio.h', 'iostream', 'io.h', 'input.h', 'console.h'], 'c' => 1, 'e' => 'iostream определяет cin, cout.'],
                ['q' => 'Что такое inline-функция?', 'o' => ['Без тела', 'Подставляемая компилятором', 'В main', 'Только чтение', 'Без аргументов'], 'c' => 1, 'e' => 'Inline подставляет тело вместо вызова.'],
            ],
            'Управление памятью' => [
                ['q' => 'Какой умный указатель для единственного владельца?', 'o' => ['shared_ptr', 'weak_ptr', 'unique_ptr', 'auto_ptr', 'raw_ptr'], 'c' => 2, 'e' => 'unique_ptr гарантирует единственность.'],
                ['q' => 'Что такое утечка памяти?', 'o' => ['Неинициализированная память', 'Освобождение дважды', 'Неосвобождённая память', 'Запись за границы', 'Деление на ноль'], 'c' => 2, 'e' => 'Утечка — выделенная память не освобождена.'],
                ['q' => 'Как освободить массив?', 'o' => ['delete', 'free()', 'delete[]', 'release()', 'dealloc()'], 'c' => 2, 'e' => 'Для new[] используется delete[].'],
                ['q' => 'Что делает weak_ptr?', 'o' => ['Увеличивает счётчик', 'Не увеличивает счётчик', 'Удаляет объект', 'Копирует', 'Запрещает копирование'], 'c' => 1, 'e' => 'weak_ptr не увеличивает счётчик shared_ptr.'],
                ['q' => 'Где локальные переменные?', 'o' => ['Куча', 'Стек', 'Глобальная память', 'Регистр', 'Файл'], 'c' => 1, 'e' => 'Локальные переменные хранятся в стеке.'],
            ],
            'ООП в C++' => [
                ['q' => 'Какое ключевое слово для виртуального метода?', 'o' => ['static', 'virtual', 'abstract', 'override', 'friend'], 'c' => 1, 'e' => 'virtual позволяет переопределять метод.'],
                ['q' => 'Что такое чисто виртуальный метод?', 'o' => ['Без реализации', 'С override', 'Статический', 'Константный', 'Приватный'], 'c' => 0, 'e' => '= 0 делает метод чисто виртуальным.'],
                ['q' => 'Как запретить наследование?', 'o' => ['private конструктор', 'final', 'static класс', 'abstract', 'protected'], 'c' => 1, 'e' => 'final запрещает наследование.'],
                ['q' => 'Что такое перегрузка оператора?', 'o' => ['Новый оператор', 'Изменение поведения для класса', 'Удаление', 'Приведение', 'Макрос'], 'c' => 1, 'e' => 'Перегрузка определяет поведение операторов для типов.'],
                ['q' => 'Какой конструктор вызывается первым?', 'o' => ['Наследника', 'Базового', 'Оба', 'Деструктор', 'Копирования'], 'c' => 1, 'e' => 'Сначала базового класса.'],
            ],
            'Шаблоны и STL' => [
                ['q' => 'Что такое шаблон?', 'o' => ['Готовый код', 'Generic-код', 'Компилятор', 'Библиотека', 'Макрос'], 'c' => 1, 'e' => 'Шаблоны — параметризованный generic-код.'],
                ['q' => 'Какой контейнер для O(1) доступа по индексу?', 'o' => ['list', 'vector', 'set', 'map', 'deque'], 'c' => 1, 'e' => 'vector обеспечивает O(1) доступ.'],
                ['q' => 'Что такое итератор?', 'o' => ['Указатель', 'Объект для обхода контейнера', 'Алгоритм', 'Контейнер', 'Функция'], 'c' => 1, 'e' => 'Итератор обходит элементы контейнера.'],
                ['q' => 'Как сортировать vector?', 'o' => ['std::sort', 'std::list', 'std::find', 'std::copy', 'std::for_each'], 'c' => 0, 'e' => 'std::sort сортирует диапазон.'],
                ['q' => 'Что такое lambda?', 'o' => ['Именованная функция', 'Анонимная функция', 'Шаблонная', 'Статическая', 'Виртуальная'], 'c' => 1, 'e' => 'Lambda — анонимная функция [].'],
            ],
            'Работа с файлами' => [
                ['q' => 'Какой класс для записи?', 'o' => ['ifstream', 'ofstream', 'fstream', 'iostream', 'fstream'], 'c' => 1, 'e' => 'ofstream для записи.'],
                ['q' => 'Как открыть для дозаписи?', 'o' => ['ofstream(\"f.txt\")', 'ofstream(\"f.txt\", ios::app)', 'ofstream(\"f.txt\", ios::in)', 'ofstream(\"f.txt\", ios::binary)', 'ofstream(\"f.txt\", ios::trunc)'], 'c' => 1, 'e' => 'ios::app для дозаписи.'],
                ['q' => 'Проверка открытия файла?', 'o' => ['file.exists()', 'file.is_open()', 'file.good()', 'file.open()', 'file.valid()'], 'c' => 1, 'e' => 'is_open() проверяет открытие.'],
                ['q' => 'Построчное чтение?', 'o' => ['file.read()', 'getline(file, line)', 'file.nextLine()', 'file.readLine()', 'cin >> file'], 'c' => 1, 'e' => 'getline(file, line).'],
                ['q' => 'Бинарный режим?', 'o' => ['ios::text', 'ios::binary', 'ios::raw', 'ios::byte', 'ios::bin'], 'c' => 1, 'e' => 'ios::binary.'],
            ],
        ],
        'practice' => [
            'Основы C++' => [
                ['lang' => 'cpp', 'title' => 'Калькулятор', 'prompt' => 'Создайте калькулятор: два числа и операция, обработка деления на ноль.', 'out' => 'Calculator with operations.', 'start' => $startCppBasics, 'tests' => [['contains', 'switch'], ['contains', 'case']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'cpp', 'title' => 'Факториал и Фибоначчи', 'prompt' => 'Функции факториала и Фибоначчи.', 'out' => 'Factorial and Fibonacci.', 'start' => '#include <iostream>\nusing namespace std;\n\n// TODO: Factorial\n// TODO: Fibonacci\n\nint main() {\n    cout << factorial(5) << endl;\n    cout << fibonacci(10) << endl;\n    return 0;\n}', 'tests' => [['contains', 'factorial'], ['contains', 'fibonacci']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'cpp', 'title' => 'Пузырьковая сортировка', 'prompt' => 'Массив 10 чисел, пузырьковая сортировка.', 'out' => 'Bubble sort.', 'start' => '#include <iostream>\n#include <cstdlib>\nusing namespace std;\n\nint main() {\n    int arr[10];\n    // TODO: Fill, sort, print\n    return 0;\n}', 'tests' => [['contains', 'for'], ['contains', 'swap']], 'diff' => 'medium', 'time' => 20],
            ],
            'Управление памятью' => [
                ['lang' => 'cpp', 'title' => 'Динамический массив', 'prompt' => 'Динамический массив new, заполнение 1..N, вывод, освобождение.', 'out' => 'Dynamic array managed.', 'start' => '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // TODO: Allocate, fill, print, free\n    return 0;\n}', 'tests' => [['contains', 'new int[]'], ['contains', 'delete[]']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'cpp', 'title' => 'Связный список', 'prompt' => 'Односвязный список: добавление, вывод, освобождение.', 'out' => 'Linked list.', 'start' => '#include <iostream>\nusing namespace std;\n\nstruct Node { int data; Node* next; };\n\n// TODO: insert, print, free\n\nint main() {\n    Node* head = nullptr;\n    return 0;\n}', 'tests' => [['contains', 'head->next'], ['contains', 'nullptr']], 'diff' => 'medium', 'time' => 25],
                ['lang' => 'cpp', 'title' => 'Умные указатели', 'prompt' => 'Демонстрация unique_ptr и shared_ptr.', 'out' => 'Smart pointers demo.', 'start' => '#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    // TODO: unique_ptr\n    // TODO: shared_ptr\n    return 0;\n}', 'tests' => [['contains', 'make_unique'], ['contains', 'make_shared']], 'diff' => 'hard', 'time' => 20],
            ],
            'ООП в C++' => [
                ['lang' => 'cpp', 'title' => 'Абстрактный класс Shape', 'prompt' => 'Абстрактный Shape с area()/perimeter(). Circle и Rectangle.', 'out' => 'Shape hierarchy.', 'start' => $startCppOop, 'tests' => [['contains', 'virtual'], ['contains', '= 0']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'cpp', 'title' => 'Перегрузка операторов', 'prompt' => 'Vector2D с +, -, ==, <<.', 'out' => 'Vector2D with operators.', 'start' => '#include <iostream>\nusing namespace std;\n\nclass Vector2D {\n    double x, y;\npublic:\n    Vector2D(double x=0, double y=0) : x(x), y(y) {}\n    // TODO: operators\n};\n\nint main() {\n    Vector2D v1(3,4), v2(1,2);\n    cout << v1 + v2 << endl;\n    return 0;\n}', 'tests' => [['contains', 'operator+'], ['contains', 'friend']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'cpp', 'title' => 'Полиморфизм', 'prompt' => 'Массив указателей на Animal, Dog, Cat, Bird. Вызов speak().', 'out' => 'Polymorphism demo.', 'start' => '#include <iostream>\n#include <vector>\nusing namespace std;\n\nclass Animal { public: virtual void speak() const = 0; virtual ~Animal() {} };\n\n// TODO: Dog, Cat, Bird\n\nint main() {\n    vector<Animal*> zoo;\n    // TODO: add, speak, cleanup\n    return 0;\n}', 'tests' => [['contains', 'virtual void speak'], ['contains', 'delete']], 'diff' => 'hard', 'time' => 25],
            ],
            'Шаблоны и STL' => [
                ['lang' => 'cpp', 'title' => 'Шаблонный бинарный поиск', 'prompt' => 'Шаблонная binarySearch.', 'out' => 'Template binary search.', 'start' => '#include <iostream>\nusing namespace std;\n\n// TODO: template binarySearch\n\nint main() {\n    int arr[] = {1,3,5,7,9};\n    cout << binarySearch(arr, 5, 7) << endl;\n    return 0;\n}', 'tests' => [['contains', 'template'], ['contains', 'mid']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'cpp', 'title' => 'STL контейнеры', 'prompt' => 'Vector, map, set для студентов.', 'out' => 'STL containers demo.', 'start' => '#include <iostream>\n#include <vector>\n#include <map>\n#include <set>\nusing namespace std;\n\nint main() {\n    // TODO: vector, map, set\n    return 0;\n}', 'tests' => [['contains', 'vector'], ['contains', 'map'], ['contains', 'set']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'cpp', 'title' => 'Лямбды и алгоритмы', 'prompt' => 'Сортировка, find_if, transform с лямбдами.', 'out' => 'Lambdas and algorithms.', 'start' => '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> nums = {3,1,4,1,5,9,2,6};\n    // TODO: sort, find_if, transform\n    return 0;\n}', 'tests' => [['contains', 'sort'], ['contains', 'find_if']], 'diff' => 'hard', 'time' => 25],
            ],
            'Работа с файлами' => [
                ['lang' => 'cpp', 'title' => 'Копирование файла', 'prompt' => 'Копирование файла с обработкой ошибок.', 'out' => 'File copy.', 'start' => '#include <iostream>\n#include <fstream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string src, dst;\n    // TODO: copy file\n    return 0;\n}', 'tests' => [['contains', 'ifstream'], ['contains', 'ofstream']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'cpp', 'title' => 'Подсчёт слов', 'prompt' => 'Подсчёт слов, строк, символов в файле.', 'out' => 'Word counter.', 'start' => '#include <iostream>\n#include <fstream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string filename;\n    // TODO: count\n    return 0;\n}', 'tests' => [['contains', 'getline'], ['contains', 'words++']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'cpp', 'title' => 'Бинарная запись', 'prompt' => 'Структура Student, запись 3 студентов в бинарный файл.', 'out' => 'Binary file ops.', 'start' => '#include <iostream>\n#include <fstream>\nusing namespace std;\n\nstruct Student { int id; char name[50]; double gpa; };\n\nint main() {\n    // TODO: write, read\n    return 0;\n}', 'tests' => [['contains', 'ios::binary'], ['contains', 'write'], ['contains', 'read']], 'diff' => 'hard', 'time' => 25],
            ],
        ],
    ],
    8 => [
        'lessons' => [
            'Основы Python' => '<h2>Основы Python</h2><p>Python — интерпретируемый высокоуровневый язык с динамической типизацией.</p><h3>Переменные</h3><pre><code>name = \"Alice\"\nage = 25\nheight = 5.6\nis_student = True\nfruits = [\"apple\", \"banana\", \"cherry\"]\nperson = {\"name\": name, \"age\": age}</code></pre><h3>Условия и циклы</h3><pre><code>if x &gt; 0:\n    print(\"Positive\")\nfor i in range(5):\n    print(i)\nsquares = [x**2 for x in range(10)]</code></pre><h3>Функции</h3><pre><code>def greet(name, greeting=\"Hello\"):\n    return f\"{greeting}, {name}!\"\nadd = lambda a, b: a + b</code></pre>',
            'ООП в Python' => '<h2>ООП в Python</h2><h3>Классы</h3><pre><code>class Dog:\n    species = \"Canis\"\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def speak(self):\n        return f\"{self.name} barks\"\n    def __str__(self):\n        return f\"{self.name}, age {self.age}\"</code></pre><h3>Наследование</h3><pre><code>class Cat(Animal):\n    def __init__(self, name, indoor=True):\n        super().__init__(name, \"Meow\")\n        self.indoor = indoor</code></pre><h3>@property</h3><pre><code>class Circle:\n    def __init__(self, radius):\n        self._radius = radius\n    @property\n    def area(self):\n        import math\n        return math.pi * self._radius ** 2</code></pre>',
            'Модули и пакеты' => '<h2>Модули и пакеты</h2><h3>Создание модуля</h3><pre><code># math_utils.py\ndef add(a, b): return a + b\nPI = 3.14159</code></pre><h3>Импорт</h3><pre><code>import math\nfrom datetime import datetime\nfrom mypackage.module import func</code></pre><h3>pip</h3><pre><code>pip install requests\npip freeze &gt; requirements.txt\npip install -r requirements.txt</code></pre>',
            'Работа с файлами' => '<h2>Работа с файлами</h2><h3>Текст</h3><pre><code>with open(\'f.txt\', \'w\') as f:\n    f.write(\'Hello\\n\')\nwith open(\'f.txt\', \'r\') as f:\n    print(f.read())</code></pre><h3>JSON</h3><pre><code>import json\njson.dump(data, f, indent=2)\ndata = json.load(f)</code></pre><h3>CSV</h3><pre><code>import csv\nwriter = csv.writer(f)\nreader = csv.DictReader(f)</code></pre>',
            'Веб-парсинг' => '<h2>Веб-парсинг</h2><h3>BeautifulSoup</h3><pre><code>from bs4 import BeautifulSoup\nsoup = BeautifulSoup(html, \"html.parser\")\ntitle = soup.find(\"h1\").text\nlinks = soup.find_all(\"a\")</code></pre><h3>Requests</h3><pre><code>import requests\nresponse = requests.get(url)\ndata = response.json()</code></pre><h3>Regex</h3><pre><code>import re\nurls = re.findall(r\'href=\"(https?://[^\"]+)\"\', html)</code></pre>',
            'Декораторы и генераторы' => '<h2>Декораторы и генераторы</h2><h3>Декораторы</h3><pre><code>def timer(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f\"{func.__name__} took {time.time()-start:.4f}s\")\n        return result\n    return wrapper</code></pre><h3>Генераторы</h3><pre><code>def fibonacci(limit):\n    a, b = 0, 1\n    while a &lt; limit:\n        yield a\n        a, b = b, a + b</code></pre>',
            'Тест по Python' => '<h2>Тест по Python</h2><p>Проверьте знания: основы, ООП, модули, файлы, парсинг, декораторы, генераторы.</p>',
        ],
        'quizzes' => [
            'Основы Python' => [
                ['q' => 'Оператор степени?', 'o' => ['^', '**', 'pow()', '%%', '//'], 'c' => 1, 'e' => '** — возведение в степень.'],
                ['q' => 'Что такое list comprehension?', 'o' => ['Цикл for', 'Сокращённое создание списков', 'Сортировка', 'Чтение файлов', 'Присваивание'], 'c' => 1, 'e' => '[expr for x in iterable if condition].'],
                ['q' => 'Неизменяемый тип?', 'o' => ['list', 'dict', 'set', 'tuple', 'bytearray'], 'c' => 3, 'e' => 'tuple неизменяемый.'],
                ['q' => 'Что делает is?', 'o' => ['Сравнивает значения', 'Проверяет тот же объект', 'Копирует', 'Приводит типы', 'Импортирует'], 'c' => 1, 'e' => 'is проверяет идентичность объекта.'],
                ['q' => 'Как закрыть файл?', 'o' => ['f.close()', 'with statement', 'f.quit()', 'f.end()', 'f.done()'], 'c' => 1, 'e' => 'with автоматически закрывает.'],
            ],
            'ООП в Python' => [
                ['q' => 'Что такое self?', 'o' => ['Глобальная переменная', 'Ссылка на экземпляр', 'Имя класса', 'Аргумент по умолчанию', 'Ключевое слово'], 'c' => 1, 'e' => 'self — ссылка на текущий экземпляр.'],
                ['q' => 'Как вызвать метод родителя?', 'o' => ['super().method()', 'parent.method()', 'base.method()', 'this.method()', 'ClassName.method()'], 'c' => 0, 'e' => 'super() для вызова метода родителя.'],
                ['q' => 'Что делает @property?', 'o' => ['Создаёт атрибут', 'Превращает метод в свойство', 'Скрывает метод', 'Делает статическим', 'Запрещает изменение'], 'c' => 1, 'e' => '@property для свойств с геттером/сеттером.'],
                ['q' => 'Что такое __init__?', 'o' => ['Удаление', 'Конструктор экземпляра', 'Инициализатор модуля', 'Глобальная функция', 'Деструктор'], 'c' => 1, 'e' => '__init__ — конструктор экземпляра.'],
                ['q' => 'Как запретить наследование?', 'o' => ['final', 'Нельзя в Python', 'private', 'abstract', 'static'], 'c' => 1, 'e' => 'Python не поддерживает запрет наследования.'],
            ],
            'Модули и пакеты' => [
                ['q' => 'Как импортировать функцию?', 'o' => ['import mod.func', 'from mod import func', 'include func', 'using func', 'require func'], 'c' => 1, 'e' => 'from mod import func.'],
                ['q' => 'Файл пакета?', 'o' => ['package.json', '__init__.py', 'setup.py', 'config.py', '__main__.py'], 'c' => 1, 'e' => '__init__.py делает пакетом.'],
                ['q' => 'requirements.txt?', 'o' => ['pip list > req.txt', 'pip freeze > req.txt', 'pip save > req.txt', 'pip export > req.txt', 'pip backup > req.txt'], 'c' => 1, 'e' => 'pip freeze > requirements.txt.'],
                ['q' => 'Что такое __all__?', 'o' => ['Список файлов', 'Экспортируемые имена', 'Глобальные переменные', 'Настройки', 'Версия'], 'c' => 1, 'e' => '__all__ определяет экспортируемые имена.'],
                ['q' => 'Текущая директория?', 'o' => ['os.getcwd()', 'Path.cwd()', 'Все варианты', 'sys.path[0]', 'os.path.getcwd()'], 'c' => 2, 'e' => 'os.getcwd() и Path.cwd().'],
            ],
            'Работа с файлами' => [
                ['q' => 'Режим чтения+записи?', 'o' => ['r', 'w', 'a', 'r+', 'w+'], 'c' => 3, 'e' => 'r+ для чтения и записи.'],
                ['q' => 'Что делает json.dump()?', 'o' => ['Читает JSON', 'Записывает как JSON', 'Конвертирует', 'Валидирует', 'Форматирует'], 'c' => 1, 'e' => 'json.dump() записывает объект в файл.'],
                ['q' => 'CSV как словари?', 'o' => ['csv.reader()', 'csv.DictReader()', 'csv.load()', 'csv.parse()', 'csv.readlines()'], 'c' => 1, 'e' => 'csv.DictReader.'],
                ['q' => 'Модуль для путей?', 'o' => ['os.path', 'pathlib', 'Оба', 'fileutils', 'pathmanager'], 'c' => 2, 'e' => 'И os.path, и pathlib.'],
                ['q' => 'Создать директорию?', 'o' => ['os.mkdir()', 'os.makedirs()', 'Path.mkdir(exist_ok=True)', 'Все кроме os.mkdir', 'Все варианты'], 'c' => 4, 'e' => 'Все варианты создания директорий.'],
            ],
            'Веб-парсинг' => [
                ['q' => 'Библиотека HTTP?', 'o' => ['urllib', 'requests', 'httpx', 'Все перечисленные', 'АиБ'], 'c' => 3, 'e' => 'Все три библиотеки для HTTP.'],
                ['q' => 'Что делает BeautifulSoup?', 'o' => ['HTTP-запросы', 'Парсит HTML/XML', 'Записывает в БД', 'Генерирует HTML', 'Кэширует'], 'c' => 1, 'e' => 'Парсит HTML/XML для извлечения данных.'],
                ['q' => 'Найти все ссылки?', 'o' => ['find(\"a\")', 'find_all(\"a\")', 'select(\"a\")', 'links()', 'get_links()'], 'c' => 1, 'e' => 'find_all(\"a\").'],
                ['q' => 'Статический контент?', 'o' => ['JavaScript', 'HTML в ответе', 'API', 'Кэш', 'БД'], 'c' => 1, 'e' => 'HTML ответ сервера.'],
                ['q' => 'Для динамического контента?', 'o' => ['BeautifulSoup', 'requests', 'Selenium', 'lxml', 're'], 'c' => 2, 'e' => 'Selenium для JS-рендеринга.'],
            ],
            'Декораторы и генераторы' => [
                ['q' => 'Что делает @wraps?', 'o' => ['Копирует атрибуты', 'Вызывает функцию', 'Удаляет', 'Создаёт декоратор', 'Импортирует'], 'c' => 0, 'e' => '@wraps копирует __name__, __doc__.'],
                ['q' => 'Что такое yield?', 'o' => ['Возвращает', 'Приостанавливает и возвращает', 'Завершает', 'Исключение', 'Останавливает цикл'], 'c' => 1, 'e' => 'yield приостанавливает и возвращает.'],
                ['q' => 'Делегирование генератора?', 'o' => ['return', 'yield from', 'yield*', 'delegate', 'send()'], 'c' => 1, 'e' => 'yield from.'],
                ['q' => 'Генераторное выражение?', 'o' => ['Список', 'Выражение в скобках', 'Кортеж', 'Словарь', 'Множество'], 'c' => 1, 'e' => '(expr for x in iter).'],
                ['q' => 'Декоратор с параметрами?', 'o' => ['Возвращает обёртку', 'Напрямую', 'Функция вызывает', 'Компилятор', 'Автоматически'], 'c' => 0, 'e' => 'Декоратор -> decorator -> wrapper -> функция.'],
            ],
        ],
        'practice' => [
            'Основы Python' => [
                ['lang' => 'python', 'title' => 'Калькулятор с историей', 'prompt' => 'Калькулятор с историей в списке. +, -, *, /, команда history.', 'out' => 'Calculator with history.', 'start' => $startPyBasics, 'tests' => [['contains', 'history.append'], ['contains', 'def calculate']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'python', 'title' => 'Фильтрация списка', 'prompt' => 'Функция filter_list с лямбда-условием.', 'out' => 'Filter function.', 'start' => 'def filter_list(lst, condition):\n    # TODO\n    pass\n\nnumbers = [1,2,3,4,5,6,7,8,9,10]\nevens = filter_list(numbers, lambda x: x % 2 == 0)\nprint(evens)', 'tests' => [['contains', 'def filter_list'], ['contains', 'lambda']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'python', 'title' => 'Частоты символов', 'prompt' => 'Частота символов в строке, сортировка по убыванию.', 'out' => 'Char frequency counter.', 'start' => 'text = \"hello world\"\n# TODO: count frequencies\n# TODO: sort by freq\n# TODO: print', 'tests' => [['contains', 'Counter'], ['contains', 'most_common']], 'diff' => 'medium', 'time' => 20],
            ],
            'ООП в Python' => [
                ['lang' => 'python', 'title' => 'Банковский счёт', 'prompt' => 'Класс BankAccount: deposit, withdraw, get_balance.', 'out' => 'BankAccount class.', 'start' => 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        # TODO\n        pass\n    def deposit(self, amount):\n        # TODO\n        pass\n    def withdraw(self, amount):\n        # TODO\n        pass', 'tests' => [['contains', 'def deposit'], ['contains', 'def withdraw']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Иерархия транспорта', 'prompt' => 'Базовый Transport, наследники Car, Bicycle, Train.', 'out' => 'Transport hierarchy.', 'start' => 'class Transport:\n    def __init__(self, name, speed):\n        # TODO\n        pass\n    def move(self):\n        # TODO\n        pass\n\n# TODO: Car, Bicycle, Train', 'tests' => [['contains', 'class Car'], ['contains', 'def move'], ['contains', 'super()']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Магические методы', 'prompt' => 'Vector с __add__, __mul__, __eq__, __len__, __getitem__.', 'out' => 'Vector with magic methods.', 'start' => 'class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    # TODO: __add__, __mul__, __eq__, __len__, __getitem__\n\nv1 = Vector(3, 4)\nv2 = Vector(1, 2)\nprint(v1 + v2)', 'tests' => [['contains', '__add__'], ['contains', '__mul__']], 'diff' => 'hard', 'time' => 25],
            ],
            'Модули и пакеты' => [
                ['lang' => 'python', 'title' => 'Создание модуля', 'prompt' => 'Модуль math_helpers с add, subtract, PI. Импорт.', 'out' => 'Custom module.', 'start' => '# math_helpers.py\ndef add(a, b): return a + b\ndef subtract(a, b): return a - b\nPI = 3.14159\n\n# main.py\n# TODO: import and use', 'tests' => [['contains', 'import'], ['contains', 'math_helpers']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'python', 'title' => 'pathlib операции', 'prompt' => 'Найти .py файлы, создать output, записать список.', 'out' => 'Pathlib operations.', 'start' => 'from pathlib import Path\n\n# TODO: find .py files\n# TODO: create output dir\n# TODO: write file list', 'tests' => [['contains', 'Path'], ['contains', 'glob']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'pip команды', 'prompt' => 'Команды: venv, activate, install, requirements, deactivate.', 'out' => 'pip commands.', 'start' => '# Write commands for:\n# 1. Create venv\n# 2. Activate\n# 3. Install requests\n# 4. Requirements\n# 5. Deactivate', 'tests' => [['contains', 'venv'], ['contains', 'pip install']], 'diff' => 'easy', 'time' => 10],
            ],
            'Работа с файлами' => [
                ['lang' => 'python', 'title' => 'Дневник', 'prompt' => 'Дневник: запись с датой, просмотр, поиск.', 'out' => 'Diary app.', 'start' => 'from datetime import datetime\n\ndef add_entry(text):\n    # TODO\n    pass\ndef view_entries():\n    # TODO\n    pass', 'tests' => [['contains', 'def add_entry'], ['contains', 'open']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Обработка CSV', 'prompt' => 'CSV студентов, средний балл, лучшие по предметам.', 'out' => 'CSV processing.', 'start' => 'import csv\nfrom collections import defaultdict\n\n# TODO: create CSV\n# TODO: average grade\n# TODO: best per subject', 'tests' => [['contains', 'csv'], ['contains', 'DictReader']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'JSON конфигурация', 'prompt' => 'Система конфигурации: чтение, создание, валидация.', 'out' => 'JSON config system.', 'start' => 'import json\nfrom pathlib import Path\n\ndef load_config(path):\n    # TODO\n    pass\ndef validate_config(config, fields):\n    # TODO\n    pass', 'tests' => [['contains', 'json.load'], ['contains', 'json.dump']], 'diff' => 'hard', 'time' => 25],
            ],
            'Веб-парсинг' => [
                ['lang' => 'python', 'title' => 'Парсинг HTML', 'prompt' => 'Разбор HTML таблицы с продуктами.', 'out' => 'HTML table parsed.', 'start' => 'from bs4 import BeautifulSoup\nhtml = \"<table><tr><th>Name</th><th>Price</th></tr><tr><td>Laptop</td><td>$999</td></tr></table>\"\n# TODO: parse', 'tests' => [['contains', 'BeautifulSoup'], ['contains', 'find_all']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'python', 'title' => 'HTTP запросы', 'prompt' => 'GET запрос, обработка статус-кодов.', 'out' => 'HTTP handling.', 'start' => 'import requests\n\ndef fetch_data(url):\n    # TODO\n    pass', 'tests' => [['contains', 'requests.get'], ['contains', 'status_code']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Regex', 'prompt' => 'Извлечение email, телефонов, URL.', 'out' => 'Regex extraction.', 'start' => 'import re\n\ndef extract_emails(text):\n    # TODO\n    pass\ndef extract_phones(text):\n    # TODO\n    pass', 'tests' => [['contains', 're.findall'], ['contains', 'extract_emails']], 'diff' => 'hard', 'time' => 25],
            ],
            'Декораторы и генераторы' => [
                ['lang' => 'python', 'title' => 'Кэширующий декоратор', 'prompt' => 'Декоратор @cache для кэширования результатов.', 'out' => 'Cache decorator.', 'start' => 'from functools import wraps\n\ndef cache(func):\n    # TODO\n    pass\n\n@cache\ndef expensive_calc(n):\n    return sum(i**2 for i in range(n))', 'tests' => [['contains', '@wraps'], ['contains', 'dict']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Простые числа', 'prompt' => 'Генератор prime_numbers(limit).', 'out' => 'Prime generator.', 'start' => 'def prime_numbers(limit):\n    # TODO\n    pass\n\nfor p in prime_numbers(50):\n    print(p, end=\" \")', 'tests' => [['contains', 'yield'], ['contains', 'def prime_numbers']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'python', 'title' => 'Retry декоратор', 'prompt' => 'Декоратор @retry(times=3) для повтора при ошибке.', 'out' => 'Retry decorator.', 'start' => 'from functools import wraps\n\ndef retry(times=3):\n    def decorator(func):\n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            # TODO\n            pass\n        return wrapper\n    return decorator', 'tests' => [['contains', 'def retry'], ['contains', 'except']], 'diff' => 'hard', 'time' => 25],
            ],
        ],
    ],
    9 => [
        'lessons' => [
            'Основы Java' => '<h2>Основы Java</h2><p>Java — объектно-ориентированный компилируемый язык на JVM.</p><h3>Структура</h3><pre><code>public class Main {\n    public static void main(String[] args) {\n        int age = 25;\n        String name = \"Alice\";\n        int[] numbers = {1, 2, 3};\n        System.out.println(\"Name: \" + name);\n    }\n}</code></pre><h3>Управление</h3><pre><code>if (age &gt;= 18) { }\nswitch (grade) { case \'A\': break; }\nfor (int i = 0; i &lt; 10; i++) { }\nwhile (count &lt; 5) { count++; }</code></pre>',
            'ООП в Java' => '<h2>ООП в Java</h2><h3>Классы</h3><pre><code>class Animal {\n    protected String name;\n    public Animal(String name) { this.name = name; }\n    public void speak() { System.out.println(name + \" makes a sound\"); }\n}</code></pre><h3>Наследование</h3><pre><code>class Dog extends Animal {\n    public Dog(String name) { super(name); }\n    @Override\n    public void speak() { System.out.println(name + \" barks\"); }\n}</code></pre><h3>Интерфейсы</h3><pre><code>interface Drawable {\n    void draw();\n    default void fill() { System.out.println(\"Filling\"); }\n}\nclass Circle implements Drawable {\n    public void draw() { System.out.println(\"Drawing circle\"); }\n}</code></pre>',
            'Коллекции Java' => '<h2>Коллекции Java</h2><h3>List, Set, Map</h3><pre><code>List&lt;String&gt; names = new ArrayList&lt;&gt;();\nnames.add(\"Alice\");\nSet&lt;Integer&gt; unique = new HashSet&lt;&gt;();\nunique.add(1);\nMap&lt;String, Integer&gt; scores = new HashMap&lt;&gt;();\nscores.put(\"Alice\", 95);</code></pre><h3>Итераторы</h3><pre><code>Iterator&lt;String&gt; it = names.iterator();\nwhile (it.hasNext()) { System.out.println(it.next()); }</code></pre>',
            'Многопоточность' => '<h2>Многопоточность</h2><h3>Создание потоков</h3><pre><code>class MyThread extends Thread {\n    public void run() { System.out.println(getName() + \" running\"); }\n}\nnew MyThread().start();\n\nRunnable task = () -&gt; System.out.println(\"Running\");\nnew Thread(task).start();</code></pre><h3>Synchronized</h3><pre><code>class Counter {\n    private int count = 0;\n    public synchronized void increment() { count++; }\n}</code></pre>',
            'Тест по Java' => '<h2>Тест по Java</h2><p>Проверьте знания: основы, ООП, коллекции, многопоточность.</p>',
        ],
        'quizzes' => [
            'Основы Java' => [
                ['q' => 'Тип по умолчанию для целых?', 'o' => ['byte', 'short', 'int', 'long', 'Integer'], 'c' => 2, 'e' => 'int — 32-битное целое.'],
                ['q' => 'Точка входа?', 'o' => ['start()', 'init()', 'main()', 'run()', 'entry()'], 'c' => 2, 'e' => 'public static void main(String[] args).'],
                ['q' => 'Что такое JVM?', 'o' => ['Java Virtual Machine', 'Java Variable Manager', 'Java Vector Module', 'Java Visual Menu', 'Java Version Manager'], 'c' => 0, 'e' => 'JVM — виртуальная машина для байткода.'],
                ['q' => 'Массив из 10 элементов?', 'o' => ['new int(10)', 'new int[10]', 'int arr[10]', 'int[] arr = int[10]', 'Array(10)'], 'c' => 1, 'e' => 'new int[10].'],
                ['q' => 'Package — это?', 'o' => ['Папка классов', 'Библиотека', 'Тип данных', 'Модификатор', 'Конструктор'], 'c' => 0, 'e' => 'Package группирует классы.'],
            ],
            'ООП в Java' => [
                ['q' => 'Что делает extends?', 'o' => ['Интерфейс', 'Наследует от класса', 'Импорт', 'Константу', 'Объект'], 'c' => 1, 'e' => 'extends — наследование класса.'],
                ['q' => 'Что такое интерфейс?', 'o' => ['Абстрактный класс', 'Контракт методов', 'Конкретный класс', 'Структура', 'Тип переменной'], 'c' => 1, 'e' => 'Интерфейс — контракт методов.'],
                ['q' => 'Что делает @Override?', 'o' => ['Новый метод', 'Указывает переопределение', 'Скрывает', 'Static', 'Запрещает'], 'c' => 1, 'e' => 'Указывает переопределение метода родителя.'],
                ['q' => 'Полиморфизм в Java?', 'o' => ['Несколько конструкторов', 'Вызов правильного метода через базовый тип', 'Несколько наследников', 'Приведение', 'Создание объектов'], 'c' => 1, 'e' => 'Разные реализации через ссылку базового типа.'],
                ['q' => 'Видимость public?', 'o' => ['private', 'protected', 'default', 'public', 'static'], 'c' => 3, 'e' => 'public — доступен везде.'],
            ],
            'Коллекции Java' => [
                ['q' => 'Без дубликатов?', 'o' => ['ArrayList', 'LinkedList', 'HashSet', 'Vector', 'Stack'], 'c' => 2, 'e' => 'HashSet — только уникальные.'],
                ['q' => 'Ключ-значение?', 'o' => ['List', 'Set', 'Map', 'Queue', 'Deque'], 'c' => 2, 'e' => 'Map хранит пары ключ-значение.'],
                ['q' => 'Iterator — это?', 'o' => ['Тип данных', 'Объект для обхода', 'Метод сортировки', 'Класс поиска', 'Контейнер'], 'c' => 1, 'e' => 'Iterator обходит элементы коллекции.'],
                ['q' => 'Добавление в ArrayList?', 'o' => ['insert()', 'add()', 'put()', 'push()', 'append()'], 'c' => 1, 'e' => 'add().'],
                ['q' => 'Сортировка ArrayList?', 'o' => ['Collections.sort()', 'Arrays.sort()', 'list.sort()', 'Все перечисленные', 'Ни один'], 'c' => 3, 'e' => 'Все три варианта.'],
            ],
            'Многопоточность' => [
                ['q' => 'Запуск потока?', 'o' => ['run()', 'start()', 'execute()', 'begin()', 'launch()'], 'c' => 1, 'e' => 'start() создаёт и запускает поток.'],
                ['q' => 'Что делает synchronized?', 'o' => ['Создаёт поток', 'Блокирует ресурс', 'Останавливает', 'Приоритет', 'Планирование'], 'c' => 1, 'e' => 'Блокирует доступ к ресурсу.'],
                ['q' => 'Что делает join()?', 'o' => ['Объединяет', 'Ожидает завершения', 'Останавливает', 'Создаёт', 'Приоритет'], 'c' => 1, 'e' => 'Ожидает завершения потока.'],
                ['q' => 'Race condition?', 'o' => ['Гонка потоков', 'Состояние гонки данных', 'Конфликт памяти', 'Ошибка компиляции', 'Блокировка'], 'c' => 1, 'e' => 'Зависимость от порядка выполнения.'],
                ['q' => 'Создание через Runnable?', 'o' => ['new Thread(runnable).start()', 'new Runnable().start()', 'Thread.create()', 'runnable.run()', 'Thread.run()'], 'c' => 0, 'e' => 'new Thread(runnable).start().'],
            ],
        ],
        'practice' => [
            'Основы Java' => [
                ['lang' => 'java', 'title' => 'Калькулятор', 'prompt' => 'Калькулятор: два числа, операция, результат.', 'out' => 'Calculator.', 'start' => $startJavaBasics, 'tests' => [['contains', 'switch'], ['contains', 'case']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'java', 'title' => 'Факториал', 'prompt' => 'Метод factorial(int n).', 'out' => 'Factorial method.', 'start' => 'public class Main {\n    public static void main(String[] args) {\n        // TODO: call factorial\n    }\n    // TODO: factorial method\n}', 'tests' => [['contains', 'factorial'], ['contains', 'return']], 'diff' => 'easy', 'time' => 10],
                ['lang' => 'java', 'title' => 'Сортировка массива', 'prompt' => 'Сортировка пузырьком.', 'out' => 'Bubble sort.', 'start' => 'public class Main {\n    public static void main(String[] args) {\n        int[] arr = {5,2,8,1,9};\n        // TODO: bubble sort\n    }\n}', 'tests' => [['contains', 'for'], ['contains', 'swap']], 'diff' => 'medium', 'time' => 20],
            ],
            'ООП в Java' => [
                ['lang' => 'java', 'title' => 'Иерархия фигур', 'prompt' => 'Абстрактный Shape, Circle, Rectangle с area() и perimeter().', 'out' => 'Shape hierarchy.', 'start' => 'abstract class Shape {\n    // TODO\n}\n\nclass Circle extends Shape {\n    // TODO\n}\n\nclass Rectangle extends Shape {\n    // TODO\n}', 'tests' => [['contains', 'abstract class'], ['contains', 'area']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'java', 'title' => 'Интерфейс Comparable', 'prompt' => 'Реализуйте Comparable<Student> для сортировки по оценке.', 'out' => 'Comparable implementation.', 'start' => 'class Student implements Comparable<Student> {\n    String name;\n    int grade;\n    // TODO: implement compareTo\n}', 'tests' => [['contains', 'Comparable'], ['contains', 'compareTo']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'java', 'title' => 'Полиморфизм', 'prompt' => 'Массив Animal с Dog, Cat, Bird. Вызовите speak().', 'out' => 'Polymorphism demo.', 'start' => 'class Animal { public void speak() {} }\n// TODO: Dog, Cat, Bird\n\npublic class Main {\n    public static void main(String[] args) {\n        Animal[] zoo = {};\n        // TODO: add, speak\n    }\n}', 'tests' => [['contains', 'Animal'], ['contains', 'speak']], 'diff' => 'hard', 'time' => 25],
            ],
            'Коллекции Java' => [
                ['lang' => 'java', 'title' => 'Управление студентами', 'prompt' => 'ArrayList студентов, HashMap оценок, HashSet уникальных предметов.', 'out' => 'Collections demo.', 'start' => 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        // TODO: ArrayList, HashMap, HashSet\n    }\n}', 'tests' => [['contains', 'ArrayList'], ['contains', 'HashMap'], ['contains', 'HashSet']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'java', 'title' => 'Сортировка и поиск', 'prompt' => 'Сортировка по оценке, бинарный поиск, подсчёт оценок.', 'out' => 'Sort and search.', 'start' => 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        List<Integer> grades = new ArrayList<>(Arrays.asList(95, 87, 92, 78, 88));\n        // TODO: sort, binary search, count\n    }\n}', 'tests' => [['contains', 'Collections.sort'], ['contains', 'binarySearch']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'java', 'title' => 'Stream API', 'prompt' => 'Используйте Stream API для фильтрации, маппинга, агрегации.', 'out' => 'Stream API demo.', 'start' => 'import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        List<String> names = Arrays.asList(\"Alice\", \"Bob\", \"Charlie\", \"Diana\");\n        // TODO: filter, map, collect\n    }\n}', 'tests' => [['contains', 'stream'], ['contains', 'filter'], ['contains', 'map']], 'diff' => 'hard', 'time' => 25],
            ],
            'Многопоточность' => [
                ['lang' => 'java', 'title' => 'Счётчик потоков', 'prompt' => 'Потокобезопасный счётчик с synchronized. 3 потока по 1000 инкрементов.', 'out' => 'Thread-safe counter.', 'start' => $startJavaThreads, 'tests' => [['contains', 'synchronized'], ['contains', 'Thread']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'java', 'title' => 'Callable и Future', 'prompt' => 'Используйте Callable для вычисления в отдельном потоке и Future для получения результата.', 'out' => 'Callable and Future demo.', 'start' => 'import java.util.concurrent.*;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        // TODO: Callable, ExecutorService, Future\n    }\n}', 'tests' => [['contains', 'Callable'], ['contains', 'Future'], ['contains', 'ExecutorService']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'java', 'title' => '生产和 потребитель', 'prompt' => 'Реализуйте паттерн Producer-Consumer с BlockingQueue.', 'out' => 'Producer-Consumer pattern.', 'start' => 'import java.util.concurrent.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        BlockingQueue<Integer> queue = new LinkedBlockingQueue<>(10);\n        // TODO: Producer and Consumer threads\n    }\n}', 'tests' => [['contains', 'BlockingQueue'], ['contains', 'put'], ['contains', 'take']], 'diff' => 'hard', 'time' => 30],
            ],
        ],
    ],
    10 => [
        'lessons' => [
            'Основы C#' => '<h2>Основы C#</h2><p>C# — объектно-ориентированный язык программирования от Microsoft на платформе .NET.</p><h3>Структура</h3><pre><code>using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        int age = 25;\n        string name = \"Alice\";\n        int[] numbers = {1, 2, 3, 4, 5};\n        List&lt;string&gt; names = new List&lt;string&gt; {\"Alice\", \"Bob\"};\n        Console.WriteLine($\"Name: {name}\");\n    }\n}</code></pre><h3>Управление</h3><pre><code>if (age &gt;= 18) { }\nswitch (grade) { case \'A\': break; }\nfor (int i = 0; i &lt; 10; i++) { }\nwhile (count &lt; 5) { count++; }\nforeach (var item in collection) { }</code></pre>',
            'ООП в C#' => '<h2>ООП в C#</h2><h3>Классы</h3><pre><code>abstract class Shape {\n    public string Name { get; set; }\n    protected Shape(string name) { Name = name; }\n    public abstract double Area();\n    public abstract double Perimeter();\n}</code></pre><h3>Наследование</h3><pre><code>class Circle : Shape {\n    public double Radius { get; set; }\n    public Circle(double r) : base(\"Circle\") { Radius = r; }\n    public override double Area() =&gt; Math.PI * Radius * Radius;\n    public override double Perimeter() =&gt; 2 * Math.PI * Radius;\n}</code></pre><h3>Свойства</h3><pre><code>class Person {\n    public string Name { get; set; }\n    public int Age { get; private set; }\n}</code></pre>',
            'LINQ и коллекции' => '<h2>LINQ и коллекции</h2><h3>LINQ запросы</h3><pre><code>var csStudents = students.Where(s =&gt; s.Department == \"CS\");\nvar sorted = students.OrderByDescending(s =&gt; s.Grade);\nvar grouped = students.GroupBy(s =&gt; s.Department);\ndouble avg = students.Average(s =&gt; s.Grade);</code></pre><h3>Коллекции</h3><pre><code>List&lt;string&gt; names = new List&lt;string&gt;();\nDictionary&lt;string, int&gt; scores = new Dictionary&lt;string, int&gt;();\nHashSet&lt;int&gt; unique = new HashSet&lt;int&gt;();\nQueue&lt;string&gt; queue = new Queue&lt;string&gt;();\nStack&lt;string&gt; stack = new Stack&lt;string&gt;();</code></pre>',
            'Delegates и события' => '<h2>Delegates и события</h2><h3>Delegates</h3><pre><code>delegate void LogHandler(string message);\nLogHandler log = Console.WriteLine;\nlog(\"Hello\");</code></pre><h3>События</h3><pre><code>class OrderService {\n    public event EventHandler&lt;OrderEventArgs&gt; OrderPlaced;\n    public void PlaceOrder(string product, decimal amount) {\n        OrderPlaced?.Invoke(this, new OrderEventArgs { Product = product });\n    }\n}</code></pre><h3>Лямбды</h3><pre><code>Func&lt;int, int, int&gt; add = (a, b) =&gt; a + b;\nAction&lt;string&gt; print = msg =&gt; Console.WriteLine(msg);\nPredicate&lt;int&gt; isEven = n =&gt; n % 2 == 0;</code></pre>',
            'Тест по C#' => '<h2>Тест по C#</h2><p>Проверьте знания: основы, ООП, LINQ, delegates, события.</p>',
        ],
        'quizzes' => [
            'Основы C#' => [
                ['q' => 'Какой тип для десятичных?', 'o' => ['int', 'float', 'double', 'decimal', 'long'], 'c' => 3, 'e' => 'decimal для точных десятичных значений.'],
                ['q' => 'String interpolation?', 'o' => ['\"Name: \" + name', '$\"Name: {name}\"', 'String.format(\"Name: {0}\", name)', 'printf', 'None'], 'c' => 1, 'e' => '$\"...{variable}...\" — string interpolation.'],
                ['q' => 'Точка входа?', 'o' => ['start()', 'main()', 'Main()', 'Init()', 'Run()'], 'c' => 2, 'e' => 'static void Main().'],
                ['q' => 'Nullable тип?', 'o' => ['int?', 'nullable int', 'Optional<int>', 'Maybe<int>', 'int|null'], 'c' => 0, 'e' => 'int? — nullable value type.'],
                ['q' => 'Оператор null-conditional?', 'o' => ['?.', '??', '!', '??=', '?.='], 'c' => 0, 'e' => '?. — null-conditional operator.'],
            ],
            'ООП в C#' => [
                ['q' => 'Что делает abstract?', 'o' => ['Создаёт экземпляр', 'Делает класс абстрактным', 'Скрывает класс', 'Делает static', 'Запрещает наследование'], 'c' => 1, 'e' => 'abstract класс нельзя инстанцировать.'],
                ['q' => 'Что такое property?', 'o' => ['Поле', 'Метод доступа к полю', 'Тип данных', 'Интерфейс', 'Конструктор'], 'c' => 1, 'e' => 'Property — инкапсуляция доступа к полям.'],
                ['q' => 'Что делает override?', 'o' => ['Новый метод', 'Переопределяет виртуальный метод', 'Скрывает метод', 'Static метод', 'Абстрактный метод'], 'c' => 1, 'e' => 'override переопределяет виртуальный/абстрактный метод.'],
                ['q' => 'Интерфейс vs абстрактный класс?', 'o' => ['Одинаковые', 'Интерфейс — контракт, класс — реализация', 'Интерфейс имеет конструкторы', 'Класс не может реализовать интерфейс', 'Нет различий'], 'c' => 1, 'e' => 'Интерфейс определяет контракт без реализации.'],
                ['q' => 'Что такое readonly?', 'o' => ['Только чтение после конструктора', 'Только чтение всегда', 'Константа', 'Static поле', 'Приватное поле'], 'c' => 0, 'e' => 'readonly можно задать только в конструкторе.'],
            ],
            'LINQ и коллекции' => [
                ['q' => 'Что такое LINQ?', 'o' => ['Language Integrated Query', 'Library for Internet Queries', 'Linear Query', 'Linked Index Query', 'Local Input Query'], 'c' => 0, 'e' => 'Language Integrated Query — встроенные запросы в C#.'],
                ['q' => 'Какой метод фильтрует?', 'o' => ['Select()', 'Where()', 'OrderBy()', 'GroupBy()', 'Aggregate()'], 'c' => 1, 'e' => 'Where() фильтрует элементы.'],
                ['q' => 'Что такое extension method?', 'o' => ['Расширяет класс', 'Новый конструктор', 'Static класс для добавления методов', 'Интерфейс', 'Приватный метод'], 'c' => 2, 'e' => 'Extension method — static метод для добавления методов к типам.'],
                ['q' => 'Как отсортировать по убыванию?', 'o' => ['OrderBy()', 'OrderByDescending()', 'Sort()', 'Reverse()', 'Descending()'], 'c' => 1, 'e' => 'OrderByDescending().'],
                ['q' => 'Что такое IEnumerable?', 'o' => ['Коллекция', 'Интерфейс перечисления', 'Массив', 'Список', 'Словарь'], 'c' => 1, 'e' => 'IEnumerable — интерфейс для перечисления элементов.'],
            ],
            'Delegates и события' => [
                ['q' => 'Что такое delegate?', 'o' => ['Тип данных', 'Указатель на метод', 'Интерфейс', 'Класс', 'Конструктор'], 'c' => 1, 'e' => 'Delegate — тип указателя на метод.'],
                ['q' => 'Что такое event?', 'o' => ['Метод', 'Публикация delegate', 'Поле', 'Свойство', 'Конструктор'], 'c' => 1, 'e' => 'Event — обёртка над delegate для безопасной публикации.'],
                ['q' => 'Что такое lambda?', 'o' => ['Анонимный метод', 'Именованный метод', 'Класс', 'Интерфейс', 'Конструктор'], 'c' => 0, 'e' => 'Lambda — анонимная функция (a, b) => a + b.'],
                ['q' => 'Что такое Func<>?', 'o' => ['Делегат с возвращаемым значением', 'Действие без возврата', 'Предикат', 'Событие', 'Интерфейс'], 'c' => 0, 'e' => 'Func<> — делегат с возвращаемым значением.'],
                ['q' => 'Что такое Action<>?', 'o' => ['Делегат с возвратом', 'Действие без возвращаемого значения', 'Предикат', 'Событие', 'Интерфейс'], 'c' => 1, 'e' => 'Action<> — делегат без возвращаемого значения.'],
            ],
        ],
        'practice' => [
            'Основы C#' => [
                ['lang' => 'csharp', 'title' => 'Калькулятор', 'prompt' => 'Калькулятор: два числа, операция switch, вывод.', 'out' => 'Calculator in C#.', 'start' => $startCSharpBasics, 'tests' => [['contains', 'switch'], ['contains', 'case']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'csharp', 'title' => 'Факториал и Фибоначчи', 'prompt' => 'Методы Factorial и Fibonacci.', 'out' => 'Factorial and Fibonacci.', 'start' => 'using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine(Factorial(5));\n        Console.WriteLine(Fibonacci(10));\n    }\n    // TODO: Factorial method\n    // TODO: Fibonacci method\n}', 'tests' => [['contains', 'Factorial'], ['contains', 'Fibonacci']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'csharp', 'title' => 'Лямбда-выражения', 'prompt' => 'Используйте Func, Action, Predicate лямбды.', 'out' => 'Lambda expressions.', 'start' => 'using System;\n\nclass Program {\n    static void Main() {\n        Func<int, int, int> add = (a, b) => a + b;\n        // TODO: Action, Predicate\n    }\n}', 'tests' => [['contains', 'Func'], ['contains', 'Action'], ['contains', 'Predicate']], 'diff' => 'medium', 'time' => 20],
            ],
            'ООП в C#' => [
                ['lang' => 'csharp', 'title' => 'Иерархия фигур', 'prompt' => 'Абстрактный Shape, Circle, Rectangle.', 'out' => 'Shape hierarchy.', 'start' => $startCSharpOop, 'tests' => [['contains', 'abstract class'], ['contains', 'override']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'Интерфейс IComparable', 'prompt' => 'Реализуйте IComparable<Student>.', 'out' => 'IComparable implementation.', 'start' => 'using System;\n\nclass Student : IComparable<Student> {\n    public string Name { get; set; }\n    public int Grade { get; set; }\n    // TODO: CompareTo\n}', 'tests' => [['contains', 'IComparable'], ['contains', 'CompareTo']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'Полиморфизм', 'prompt' => 'Массив Shape с Circle, Rectangle, Triangle. Выведите площади.', 'out' => 'Polymorphism demo.', 'start' => 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        List<Shape> shapes = new List<Shape> {};\n        // TODO: add shapes, print areas\n    }\n}', 'tests' => [['contains', 'Shape'], ['contains', 'Area']], 'diff' => 'hard', 'time' => 25],
            ],
            'LINQ и коллекции' => [
                ['lang' => 'csharp', 'title' => 'LINQ запросы', 'prompt' => 'Фильтрация, сортировка, группировка студентов через LINQ.', 'out' => 'LINQ queries.', 'start' => $startCSharpLinq, 'tests' => [['contains', 'Where'], ['contains', 'OrderBy'], ['contains', 'GroupBy']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'Коллекции', 'prompt' => 'Используйте List, Dictionary, HashSet, Queue, Stack.', 'out' => 'Collections demo.', 'start' => 'using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        // TODO: List, Dictionary, HashSet, Queue, Stack\n    }\n}', 'tests' => [['contains', 'List<'], ['contains', 'Dictionary<'], ['contains', 'HashSet<']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'LINQ агрегаты', 'prompt' => 'Sum, Average, Min, Max, Count через LINQ.', 'out' => 'LINQ aggregates.', 'start' => 'using System;\nusing System.Linq;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        List<int> numbers = new List<int> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};\n        // TODO: Sum, Average, Min, Max, Count\n    }\n}', 'tests' => [['contains', 'Sum()'], ['contains', 'Average()'], ['contains', 'Min()']], 'diff' => 'hard', 'time' => 20],
            ],
            'Delegates и события' => [
                ['lang' => 'csharp', 'title' => 'Delegate и event', 'prompt' => 'Создайте OrderService с событием OrderPlaced, EmailService и InventoryService как подписчики.', 'out' => 'Event handling demo.', 'start' => $startCSharpDelegates, 'tests' => [['contains', 'event'], ['contains', '+='], ['contains', 'Invoke']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'Func и Action', 'prompt' => 'Используйте Func для вычислений, Action для вывода, Predicate для фильтрации.', 'out' => 'Func and Action demo.', 'start' => 'using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        List<int> numbers = new List<int> {1,2,3,4,5,6,7,8,9,10};\n        // TODO: Func, Action, Predicate\n    }\n}', 'tests' => [['contains', 'Func<'], ['contains', 'Action<'], ['contains', 'Predicate<']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'csharp', 'title' => 'Система уведомлений', 'prompt' => 'Создайте систему уведомлений: Email, SMS, Push как подписчики на событие NewMessage.', 'out' => 'Notification system.', 'start' => 'using System;\n\nclass MessageEventArgs : EventArgs {\n    public string Message { get; set; }\n    public string Recipient { get; set; }\n}\n\nclass MessageService {\n    public event EventHandler<MessageEventArgs> NewMessage;\n    public void Send(string message, string recipient) {\n        NewMessage?.Invoke(this, new MessageEventArgs { Message = message, Recipient = recipient });\n    }\n}\n\n// TODO: EmailService, SMSService, PushService\n\nclass Program {\n    static void Main() {\n        // TODO: subscribe and test\n    }\n}', 'tests' => [['contains', 'event'], ['contains', 'EventHandler'], ['contains', '+=']], 'diff' => 'hard', 'time' => 25],
            ],
        ],
    ],
];
