<?php

$startGit1 = "git init\ngit add .\ngit commit -m 'Initial commit'\ngit status";
$startGit2 = "git checkout -b feature/my-branch\ngit add .\ngit commit -m 'feat: add new feature'\ngit push origin feature/my-branch";
$startGit3 = "git checkout main\ngit pull origin main\ngit merge feature/my-branch";
$startGit4 = "git log --oneline --graph --all\ngit branch -a";
$startGit5 = "git reset HEAD~1\ngit stash\ngit stash pop";
$startGit6 = "git remote add origin https://github.com/user/repo.git\ngit push -u origin main";
$startGit7 = "git clone https://github.com/user/repo.git\ncd repo\ngit checkout -b new-branch";
$startGit8 = "git diff HEAD~1 HEAD\ngit show HEAD:filename";
$startGit9 = "git tag -a v1.0.0 -m 'Release version 1.0.0'\ngit push origin v1.0.0";
$startGit10 = "git rebase main\ngit push --force-with-lease";

$startDevOps1 = "docker build -t myapp .\ndocker run -d -p 8080:80 myapp";
$startDevOps2 = "kubectl apply -f deployment.yaml\nkubectl get pods";
$startDevOps3 = "ansible-playbook -i inventory deploy.yml";
$startDevOps4 = "terraform init\nterraform plan\nterraform apply";
$startDevOps5 = "prometheus --config.file=prometheus.yml\ngrafana-server --homepath=/usr/share/grafana";

$startDockerfile = 'FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]';

$startGitlabCI = 'stages:
  - build
  - test
  - deploy
build:
  stage: build
  script: npm run build';

$startReact1 = "npm create vite@latest my-app -- --template react\ncd my-app\nnpm run dev";
$startReact2 = "npx create-react-app my-app\ncd my-app\nnpm start";

$startReactRouter = "npm install react-router-dom";
$startReactRedux = "npm install @reduxjs/toolkit react-redux";
$startNode1 = "npm init -y\nnpm install express";
$startNode2 = "mkdir my-api && cd my-api\nnpm init -y\nnpm install express cors dotenv";
$startNodeAuth = "npm install jsonwebtoken bcryptjs";

return [
    11 => [
        'lessons' => [
            'Основы Git: установка и базовые команды' => '<h2>Основы Git: установка и базовые команды</h2><p>Git — это распределённая система контроля версий, разработанная Линусом Торвальдом в 2005 году для разработки ядра Linux. Сегодня Git является стандартом управления версиями в мире программирования.</p><h3>Установка Git</h3><p>Windows: скачайте установщик с <code>git-scm.com</code>. macOS: <code>brew install git</code>. Linux: <code>sudo apt install git</code> или <code>sudo yum install git</code>.</p><h3>Настройка</h3><pre><code>git config --global user.name "Your Name"\ngit config --global user.email "your@email.com"</code></pre><h3>Базовые команды</h3><p><strong>git init</strong> — создаёт новый репозиторий в текущей директории.</p><p><strong>git add</strong> — добавляет файлы в индекс (staging area): <code>git add filename</code> или <code>git add .</code> для всех файлов.</p><p><strong>git commit -m "message"</strong> — фиксирует изменения в репозитории с описанием.</p><p><strong>git status</strong> — показывает текущее состояние рабочей директории.</p><p><strong>git log</strong> — выводит историю коммитов. Полезные флаги: <code>--oneline</code>, <code>--graph</code>, <code>--all</code>.</p><h3>.gitignore</h3><p>Создайте файл <code>.gitignore</code> в корне проекта, чтобы Git игнорировал ненужные файлы:</p><pre><code>node_modules/\n.env\n*.log\ndist/</code></pre>',
            'Ветвление и слияние' => '<h2>Ветвление и слияние</h2><p>Ветки в Git позволяют вести параллельную разработку, не мешая основной кодовой базе. Это ключевой концепт, обеспечивающий безопасную работу нескольких разработчиков одновременно.</p><h3>Создание и переключение веток</h3><pre><code>git branch feature-login    # создание ветки\ngit checkout feature-login  # переключение\ngit checkout -b bugfix-123  # создание + переключение</code></pre><h3>Просмотр веток</h3><p><code>git branch</code> — список локальных веток. <code>git branch -a</code> — все ветки (включая удалённые). <code>git branch -v</code> — с последними коммитами.</p><h3>Слияние (merge)</h3><p>Для слияния изменений из одной ветки в другую:</p><pre><code>git checkout main\ngit merge feature-login</code></pre><p>Типы слияний: <strong>fast-forward</strong> (прямое перемещение указателя) и <strong>three-way merge</strong> (с созданием merge-коммита).</p><h3>Решение конфликтов</h3><p>При конфликтах Git помечает конфликтные файлы. Откройте файлы, найдите маркеры <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>, <code>=======</code>, <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code>, выберите нужные изменения и сделайте коммит.</p><h3>Удаление веток</h3><pre><code>git branch -d feature-login   # удаление (безопасное)\ngit branch -D feature-login   # принудительное удаление</code></pre>',
            'Удалённые репозитории и работа в команде' => '<h2>Удалённые репозитории и работа в команде</h2><p>Работа в команде требует понимания удалённых репозиториев и синхронизации изменений между разработчиками.</p><h3>Клонирование</h3><pre><code>git clone https://github.com/user/repo.git\ngit clone git@github.com:user/repo.git</code></pre><h3>Удалённые репозитории</h3><p><code>git remote -v</code> — список удалённых репозиториев. <code>git remote add origin URL</code> — добавление нового удалённого репозитория.</p><h3>Получение и отправка изменений</h3><pre><code>git pull origin main       # получить и слить\ngit fetch origin           # только получить\ngit push origin main       # отправить изменения</code></pre><p>Перед <code>git pull</code> рекомендуется делать <code>git fetch</code>, чтобы избежать нежиданных слияний.</p><h3>Форк (fork)</h3><p>Форк — это копия чужого репозитория на вашем аккаунте. Рабочий процесс:</p><ol><li>Сфоркните репозиторий на GitHub</li><li>Клонируйте свой форк: <code>git clone https://github.com/YOU/repo.git</code></li><li>Создайте ветку для изменений</li><li>Внесите изменения и отправьте: <code>git push origin feature</code></li><li>Создайте Pull Request на GitHub</li></ol><h3>Pull Request (MR)</h3><p>Pull Request — это способ предложения изменений в основную ветку. Через PR проводят code review, обсуждают архитектурные решения и тестируют изменения.</p>',
            'Продвинутые техники Git' => '<h2>Продвинутые техники Git</h2><p>Эти техники помогут работать с Git эффективнее и решать сложные задачи.</p><h3>Stash (откладывание)</h3><p>Если нужно временно отложить незаконченные изменения:</p><pre><code>git stash                # сохранить изменения\ngit stash list           # список сохранений\ngit stash pop            # восстановить и удалить\ngit stash apply          # восстановить без удаления</code></pre><h3>Cherry-pick</h3><p>Применение конкретного коммита из другой ветки:</p><pre><code>git cherry-pick abc1234\ngit cherry-pick abc1234..def5678  # диапазон коммитов</code></pre><h3>Rebase</h3><p>Перенос коммитов на новую базу (переписывает историю):</p><pre><code>git checkout feature\ngit rebase main</code></pre><p>Не делайте rebase уже запушенных веток — это сломает историю для коллег.</p><h3>Большие файлы (LFS)</h3><p>Git LFS хранит большие файлы отдельно:</p><pre><code>git lfs install\ngit lfs track "*.psd"\ngit add .gitattributes</code></pre><h3>Бисект (bisect)</h3><p>Бинарный поиск коммита,引进ившего баг:</p><pre><code>git bisect start\ngit bisect bad          # текущий коммит сломан\ngit bisect good v1.0    # этот коммит был рабочим\n# Git переключится на коммит для проверки\n# После проверки:\ngit bisect good  или  git bisect bad</code></pre><h3>Aliases</h3><pre><code>git config --global alias.co checkout\ngit config --global alias.br branch\ngit config --global alias.st status\ngit config --global alias.last "log -1 HEAD"</code></pre>',
            'Тест по Git' => '<h2>Тест по Git</h2><p>Проверьте свои знания по основам Git, ветвлению, работе с удалёнными репозиториями и продвинутым техникам.</p>'
        ],
        'quizzes' => [
            'Основы Git: установка и базовые команды' => [
                ['q' => 'Какая команда инициализирует новый Git-репозиторий?', 'o' => ['git start', 'git init', 'git create', 'git new'], 'c' => 1, 'e' => 'git init создаёт новый пустой репозиторий в текущей директории, создавая скрытую папку .git.'],
                ['q' => 'Что делает команда git add . ?', 'o' => ['Удаляет все файлы', 'Добавляет все изменённые файлы в staging area', 'Коммитит все изменения', 'Показывает статус'], 'c' => 1, 'e' => 'git add . добавляет все новые и изменённые файлы в индекс (staging area) для следующего коммита.'],
                ['q' => 'Как добавить описание к коммиту?', 'o' => ['git commit -m "message"', 'git commit --message "message"', 'git commit "message"', 'Оба первых варианта верны'], 'c' => 3, 'e' => 'Оба флага -m и --message позволяют указать сообщение коммита. Третий вариант неверен.'],
                ['q' => 'Какая команда показывает статус репозитория?', 'o' => ['git info', 'git state', 'git status', 'git log'], 'c' => 2, 'e' => 'git status показывает текущее состояние: какие файлы изменены, добавлены в staging, неп追踪аемые файлы.'],
                ['q' => 'Что такое .gitignore файл?', 'o' => ['Файл с коммитами', 'Файл, указывающий какие файлы Git должен игнорировать', 'Настройки удалённого репозитория', 'Файл с паролями'], 'c' => 1, 'e' => '.gitignore содержит паттерны файлов и папок, которые Git должен игнорировать (node_modules, .env и т.д.).']
            ],
            'Ветвление и слияние' => [
                ['q' => 'Как создать новую ветку и сразу переключиться на неё?', 'o' => ['git branch feature', 'git checkout -b feature', 'git switch -c feature', 'git new feature'], 'c' => 1, 'e' => 'git checkout -b feature создаёт новую ветку и сразу переключается на неё. git switch -c — современная альтернатива.'],
                ['q' => 'Что такое fast-forward merge?', 'o' => ['Быстрое удаление ветки', 'Прямое перемещение указателя ветки без создания merge-коммита', 'Слияние с конфликтами', 'Откат коммитов'], 'c' => 1, 'e' => 'Fast-forward merge происходит, когда целевая ветка не имеет уникальных коммитов — указатель просто перемещается.'],
                ['q' => 'Как разрешить конфликт слияния?', 'o' => ['Удалить файл', 'Отредактировать файл, удалив маркеры конфликта, затем сделать коммит', 'Использовать git force', 'Перезапустить компьютер'], 'c' => 1, 'e' => 'Нужно вручную отредактировать конфликтные файлы, выбрать нужные изменения, удалить маркеры и сделать коммит.'],
                ['q' => 'Какая команда показывает все ветки (локальные и удалённые)?', 'o' => ['git branch', 'git branch -a', 'git branch --all', 'Все варианты'], 'c' => 3, 'e' => 'git branch показывает только локальные. Флаг -a или --all добавляет удалённые ветки.'],
                ['q' => 'Что делает git merge feature в ветке main?', 'o' => ['Удаляет ветку feature', 'Переключается на feature', 'Вливает изменения из feature в main', 'Создаёт новый коммит без изменений'], 'c' => 2, 'e' => 'git merge берёт все коммиты из feature, которых нет в main, и применяет их, создавая merge-коммит.']
            ],
            'Удалённые репозитории и работа в команде' => [
                ['q' => 'Как клонировать удалённый репозиторий?', 'o' => ['git pull URL', 'git clone URL', 'git fetch URL', 'git copy URL'], 'c' => 1, 'e' => 'git clone создаёт полную копию удалённого репозитория на вашем компьютере, включая всю историю.'],
                ['q' => 'Что делает git push -u origin feature?', 'o' => ['Удаляет ветку feature', 'Отправляет ветку feature в удалённый репозиторий и связывает её', 'Получает изменения', 'Создаёт новый удалённый репозиторий'], 'c' => 1, 'e' => 'Флаг -u связывает локальную ветку с удалённой, позволяя в будущем просто писать git push.'],
                ['q' => 'Что такое Pull Request?', 'o' => ['Запрос на удаление кода', 'Предложение изменений для review и слияния в основную ветку', 'Команда для получения изменений', 'Тип ветки'], 'c' => 1, 'e' => 'Pull Request — это способ предложить изменения в основную ветку через интерфейс GitHub/GitLab с code review.'],
                ['q' => 'В чём разница между git pull и git fetch?', 'o' => ['Нет разницы', 'pull = fetch + merge, fetch только скачивает', 'pull скачивает, fetch скачивает и сливает', 'fetch работает быстрее'], 'c' => 1, 'e' => 'git fetch только скачивает изменения из удалённого репозитория, git pull автоматически делает merge после fetch.'],
                ['q' => 'Как добавить удалённый репозиторий?', 'o' => ['git add remote URL', 'git remote add origin URL', 'git connect URL', 'git set remote URL'], 'c' => 1, 'e' => 'git remote add добавляет новый удалённый репозиторий. origin — стандартное имя для основного удалённого репозитория.']
            ],
            'Продвинутые техники Git' => [
                ['q' => 'Что такое git stash?', 'o' => ['Удаление коммитов', 'Временное сохранение изменений без коммита', 'Копирование репозитория', 'Откат изменений'], 'c' => 1, 'e' => 'git stash временно сохраняет незаконченные изменения, очищая рабочую директорию. Позже можно восстановить stash.'],
                ['q' => 'Для чего используется git rebase?', 'o' => ['Для слияния веток', 'Для переноса коммитов на новую базу (переписывания истории)', 'Для удаления файлов', 'Для создания тегов'], 'c' => 1, 'e' => 'rebase перемещает коммиты из одной ветки на другую, создавая чистую линейную историю.'],
                ['q' => 'Что такое cherry-pick?', 'o' => ['Выбор ветки', 'Применение конкретного коммита из другой ветки', 'Удаление коммита', 'Поиск багов'], 'c' => 1, 'e' => 'git cherry-pick позволяет применить отдельный коммит (или диапазон) из другой ветки в текущую ветку.'],
                ['q' => 'Для чего нужен git bisect?', 'o' => ['Для разделения файлов', 'Для бинарного поиска коммита,引进ившего баг', 'Для слияния', 'Для создания веток'], 'c' => 1, 'e' => 'git bisect автоматически переключается между коммитами, позволяя найти тот, который引进ил баг, за O(log n) проверок.'],
                ['q' => 'Что такое Git LFS?', 'o' => ['Large File System — хранение больших файлов отдельно от основного репозитория', 'Large File Sharing', 'Live File Sync', 'Local File Storage'], 'c' => 0, 'e' => 'Git LFS заменяет большие файлы ссылками, храня сами файлы на отдельном сервере.']
            ],
            'Тест по Git' => [
                ['q' => 'Какая команда покажет только уникальные коммиты в feature, которых нет в main?', 'o' => ['git log main..feature', 'git log feature --not main', 'git diff main feature', 'Оба первых варианта'], 'c' => 3, 'e' => 'И git log main..feature, и git log feature --not main показывают коммиты, которые есть в feature, но отсутствуют в main.'],
                ['q' => 'Что произойдёт при git reset --soft HEAD~1 ?', 'o' => ['Удалится последний коммит и все изменения', 'Удалится коммит, но изменения останутся в staging area', 'Изменения отменятся, коммит останется', 'Ничего не произойдёт'], 'c' => 1, 'e' => '--soft отменяет коммит, но оставляет все изменения в staging area. Можно сразу сделать новый коммит.'],
                ['q' => 'Как отправить тег в удалённый репозиторий?', 'o' => ['git push tags', 'git push origin v1.0.0', 'git tag push v1.0.0', 'git push --tags'], 'c' => 3, 'e' => 'git push --tags отправляет все локальные теги. Можно отправить конкретный: git push origin v1.0.0.'],
                ['q' => 'Для чего используется git revert?', 'o' => ['Полное удаление коммита из истории', 'Создание нового коммита, отменяющего изменения указанного коммита', 'Удаление файла', 'Откат к предыдущему коммиту'], 'c' => 1, 'e' => 'git revert создаёт новый коммит, который является обратным к указанному. Безопасно для уже запушенных коммитов.'],
                ['q' => 'Какое правило работает с git pull --rebase?', 'o' => ['Всегда используйте rebase', 'Используйте, когда хотите отменить pull', 'Используйте для линейной истории, когда нет локальных коммитов', 'Никогда не используйте'], 'c' => 2, 'e' => 'git pull --rebase применяет fetch и делает rebase вместо merge. Полезно для чистой истории.']
            ]
        ],
        'practice' => [
            'Основы Git: установка и базовые команды' => [
                ['lang' => 'bash', 'title' => 'Инициализация репозитория', 'prompt' => 'Инициализируйте Git-репозиторий, добавьте файлы и сделайте первый коммит.', 'out' => '', 'start' => $startGit1, 'tests' => [['contains', 'git init'], ['contains', 'git add'], ['contains', 'git commit']], 'diff' => 'easy', 'time' => 10],
                ['lang' => 'bash', 'title' => 'Просмотр статуса', 'prompt' => 'Проверьте статус репозитория и посмотрите историю коммитов в компактном формате.', 'out' => '', 'start' => $startGit4, 'tests' => [['contains', 'git status'], ['contains', 'git log']], 'diff' => 'easy', 'time' => 10],
                ['lang' => 'bash', 'title' => 'Настройка .gitignore', 'prompt' => 'Создайте .gitignore файл, который игнорирует node_modules и .env файлы.', 'out' => '', 'start' => '', 'tests' => [['contains', '.gitignore'], ['contains', 'node_modules'], ['contains', '.env']], 'diff' => 'easy', 'time' => 10]
            ],
            'Ветвление и слияние' => [
                ['lang' => 'bash', 'title' => 'Создание и слияние веток', 'prompt' => 'Создайте ветку feature, сделайте коммит и слейте с main.', 'out' => '', 'start' => $startGit2, 'tests' => [['contains', 'git branch'], ['contains', 'git checkout'], ['contains', 'git merge']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Решение конфликтов', 'prompt' => 'Получите изменения из удалённого репозитория и слейте с локальными изменениями.', 'out' => '', 'start' => $startGit3, 'tests' => [['contains', 'git pull'], ['contains', 'git merge']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Работа с ветками', 'prompt' => 'Посмотрите список всех веток и удалите отработанную feature-ветку.', 'out' => '', 'start' => $startGit4, 'tests' => [['contains', 'git branch'], ['contains', '-d']], 'diff' => 'easy', 'time' => 10]
            ],
            'Удалённые репозитории и работа в команде' => [
                ['lang' => 'bash', 'title' => 'Клонирование репозитория', 'prompt' => 'Клонируйте удалённый репозиторий и создайте новую ветку для работы.', 'out' => '', 'start' => $startGit7, 'tests' => [['contains', 'git clone'], ['contains', 'git checkout -b']], 'diff' => 'easy', 'time' => 10],
                ['lang' => 'bash', 'title' => 'Отправка изменений', 'prompt' => 'Добавьте удалённый репозиторий и отправьте свои изменения.', 'out' => '', 'start' => $startGit6, 'tests' => [['contains', 'git remote add'], ['contains', 'git push']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Просмотр diff', 'prompt' => 'Посмотрите разницу между последними двумя коммитами.', 'out' => '', 'start' => $startGit8, 'tests' => [['contains', 'git diff'], ['contains', 'git show']], 'diff' => 'easy', 'time' => 10]
            ],
            'Продвинутые техники Git' => [
                ['lang' => 'bash', 'title' => 'Stash изменений', 'prompt' => 'Сохраните текущие изменения в stash, затем восстановите их.', 'out' => '', 'start' => $startGit5, 'tests' => [['contains', 'git stash'], ['contains', 'git stash pop']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Cherry-pick коммита', 'prompt' => 'Примените конкретный коммит из другой ветки в текущую ветку.', 'out' => '', 'start' => $startGit10, 'tests' => [['contains', 'git cherry-pick']], 'diff' => 'hard', 'time' => 20],
                ['lang' => 'bash', 'title' => 'Rebase ветки', 'prompt' => 'Перенесите коммиты из feature-ветки на обновлённую main.', 'out' => '', 'start' => $startGit10, 'tests' => [['contains', 'git rebase']], 'diff' => 'hard', 'time' => 20]
            ],
            'Тест по Git' => [
                ['lang' => 'bash', 'title' => 'Создание и отправка тега', 'prompt' => 'Создайте аннотированный тег с описанием для релиза и отправьте его в удалённый репозиторий.', 'out' => '', 'start' => $startGit9, 'tests' => [['contains', 'git tag'], ['contains', 'git push']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Откат коммита', 'prompt' => 'Откатите последний коммит, сохранив изменения, и сделайте новый коммит.', 'out' => '', 'start' => $startGit5, 'tests' => [['contains', 'git reset'], ['contains', 'git commit']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'bash', 'title' => 'Бисект для поиска бага', 'prompt' => 'Используйте git bisect для нахождения коммита,引进ившего проблему.', 'out' => '', 'start' => '', 'tests' => [['contains', 'git bisect start'], ['contains', 'git bisect bad'], ['contains', 'git bisect good']], 'diff' => 'hard', 'time' => 20]
            ]
        ]
    ],

    12 => [
        'lessons' => [
            'Основы DevOps' => '<h2>Основы DevOps</h2><p>DevOps — это культура, объединяющая разработку (Development) и эксплуатацию (Operations) для ускорения доставки программного обеспечения.</p><h3>Принципы DevOps</h3><ul><li><strong>Автоматизация</strong> — всё должно быть автоматизировано: сборка, тестирование, развёртывание</li><li><strong>Непрерывная доставка</strong> — изменения доставляются пользователям как можно чаще</li><li><strong>Обратная связь</strong> — быстрые петли обратной связи между разработкой и эксплуатацией</li><li><strong>Совместная ответственность</strong> — разработчики отвечают за работу кода в продакшене</li></ul><h3>Инструменты DevOps</h3><ul><li><strong>Контроль версий:</strong> Git, GitHub, GitLab</li><li><strong>CI/CD:</strong> Jenkins, GitHub Actions, GitLab CI, CircleCI</li><li><strong>Контейнеризация:</strong> Docker, Podman</li><li><strong>Оркестрация:</strong> Kubernetes, Docker Swarm</li><li><strong>IaC:</strong> Terraform, Ansible, Pulumi</li><li><strong>Мониторинг:</strong> Prometheus, Grafana, ELK Stack</li></ul><h3>Поток DevOps</h3><p>Классический DevOps-цикл: Планирование - Код - Сборка - Тестирование - Релиз - Развёртывание - Эксплуатация - Мониторинг - Планирование...</p><p>DevOps — это не должность, а набор практик. Однако сейчас существуют DevOps-инженеры, которые специализируются на этих практиках.</p>',
            'CI/CD пайплайны' => '<h2>CI/CD пайплайны</h2><p>CI/CD (Continuous Integration / Continuous Delivery) — это практики автоматизации сборки, тестирования и развёртывания приложений.</p><h3>Continuous Integration (CI)</h3><p>При CI разработчики часто коммитят код в общую ветку. Каждый коммит автоматически:</p><ol><li>Компилируется</li><li>Запускаются тесты</li><li>Анализируется качество кода</li></ol><p>Преимущества: раннее обнаружение багов, уменьшение конфликтов слияния.</p><h3>Continuous Delivery / Deployment (CD)</h3><p><strong>Continuous Delivery</strong> — код готов к деплою вручную. <strong>Continuous Deployment</strong> — деплой происходит автоматически после прохождения всех проверок.</p><h3>GitHub Actions</h3><p>Пример простого CI/CD пайплайна:</p><pre><code>name: CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  build-and-test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - uses: actions/setup-node@v3\n        with:\n          node-version: 18\n      - run: npm ci\n      - run: npm test\n      - run: npm run build</code></pre><h3>Стадии пайплайна</h3><ul><li>Build — сборка артефактов</li><li>Test — unit, интеграционные, e2e тесты</li><li>Security — проверка безопасности (SAST, DAST)</li><li>Deploy — развёртывание в staging/production</li><li>Notify — уведомления в Slack/Email</li></ul>',
            'Мониторинг и логирование' => '<h2>Мониторинг и логирование</h2><p>Мониторинг и логирование критически важны для поддержания здоровья приложений в продакшене.</p><h3>Метрики</h3><p>Основные метрики (метод Four Golden Signals):</p><ul><li><strong>Latency</strong> — время отклика</li><li><strong>Traffic</strong> — нагрузка (запросы в секунду)</li><li><strong>Errors</strong> — доля ошибок</li><li><strong>Saturation</strong> — загрузка ресурсов</li></ul><h3>Prometheus + Grafana</h3><p>Prometheus собирает метрики, Grafana визуализирует их на дашбордах.</p><pre><code># Пример Prometheus конфигурации\nglobal:\n  scrape_interval: 15s\nscrape_configs:\n  - job_name: "node"\n    static_configs:\n      - targets: ["localhost:9100"]</code></pre><h3>Логирование</h3><p>Уровни логов: DEBUG - INFO - WARN - ERROR - FATAL</p><p>Структурированные логи (JSON) предпочтительнее текстовых для парсинга.</p><h3>ELK Stack</h3><p><strong>E</strong>lasticsearch — поиск и хранение. <strong>L</strong>ogstash — обработка логов. <strong>K</strong>ibana — визуализация.</p><h3>Алертинг</h3><p>Настройте алерты на критические метрики: высокий error rate, длительное время отклика, нехватка диска/памяти.</p>',
            'Infrastructure as Code' => '<h2>Infrastructure as Code (IaC)</h2><p>IaC — это практика управления инфраструктурой через код, а не через ручные процессы.</p><h3>Преимущества IaC</h3><ul><li>Воспроизводимость — одна и та же инфраструктура в dev, staging, production</li><li>Версионирование — история изменений инфраструктуры в Git</li><li>Автоматизация — уменьшение человеческих ошибок</li><li>Тестируемость — проверка инфраструктуры перед применением</li></ul><h3>Terraform</h3><p>Terraform от HashiCorp — декларативный IaC-инструмент:</p><pre><code>resource "aws_instance" "web" {\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "t2.micro"\n  tags = {\n    Name = "WebServer"\n  }\n}</code></pre><h3>Ansible</h3><p>Ansible — инструмент для конфигурационного управления:</p><pre><code>- hosts: web\n  become: yes\n  tasks:\n    - name: Install nginx\n      apt:\n        name: nginx\n        state: present\n    - name: Start nginx\n      service:\n        name: nginx\n        state: started</code></pre><h3>Декларативный vs Императивный подход</h3><p>Декларативный: описываете желаемое состояние (Terraform, Kubernetes). Императивный: описываете шаги для достижения состояния (Bash-скрипты, Ansible).</p>'
        ],
        'quizzes' => [
            'Основы DevOps' => [
                ['q' => 'Что такое DevOps?', 'o' => ['Язык программирования', 'Культура, объединяющая разработку и эксплуатацию', 'Тип базы данных', 'Фреймворк для тестирования'], 'c' => 1, 'e' => 'DevOps — это набор практик и культур, объединяющих разработку и эксплуатацию для ускорения доставки ПО.'],
                ['q' => 'Какой инструмент используется для контейнеризации?', 'o' => ['Jenkins', 'Docker', 'Terraform', 'Prometheus'], 'c' => 1, 'e' => 'Docker — самый популярный инструмент для создания и запуска контейнеров с приложениями.'],
                ['q' => 'Что такое Infrastructure as Code?', 'o' => ['Код, написанный на инфраструктурном языке', 'Управление инфраструктурой через код', 'Инфраструктура, работающая как код', 'Программирование сетей'], 'c' => 1, 'e' => 'IaC — это практика управления инфраструктурой (серверы, сети, БД) через машинно-читаемые файлы.'],
                ['q' => 'Какой инструмент оркестрации контейнеров наиболее популярен?', 'o' => ['Docker', 'Docker Swarm', 'Kubernetes', 'Podman'], 'c' => 2, 'e' => 'Kubernetes (K8s) — стандарт оркестрации контейнеров, используемый для управления кластерами.'],
                ['q' => 'Что такое CI/CD?', 'o' => ['Continuous Integration / Continuous Deployment', 'Code Integration / Code Delivery', 'Central Infrastructure / Central Database', 'Continuous Improvement / Continuous Development'], 'c' => 0, 'e' => 'CI/CD — это практики непрерывной интеграции и доставки для автоматизации сборки, тестирования и деплоя.']
            ],
            'CI/CD пайплайны' => [
                ['q' => 'Какая первая стадия типичного CI/CD пайплайна?', 'o' => ['Тестирование', 'Деплой', 'Сборка (Build)', 'Мониторинг'], 'c' => 2, 'e' => 'Первая стадия — сборка (build): компиляция, подготовка артефактов. Без успешной сборки тестирование невозможно.'],
                ['q' => 'Чем Continuous Delivery отличается от Continuous Deployment?', 'o' => ['Ничем', 'Delivery требует ручного деплоя, Deployment автоматизирует его', 'Delivery быстрее', 'Deployment использует Docker'], 'c' => 1, 'e' => 'Continuous Delivery означает, что код готов к деплою, но деплой происходит вручную. Continuous Deployment автоматизирует весь процесс.'],
                ['q' => 'Какой файл конфигурации используется в GitHub Actions?', 'o' => ['.github/workflows/ci.yml', '.gitlab-ci.yml', 'Jenkinsfile', '.circleci/config.yml'], 'c' => 0, 'e' => 'GitHub Actions использует YAML-файлы в папке .github/workflows/.'],
                ['q' => 'Какая команда устанавливает зависимости в npm для CI?', 'o' => ['npm install', 'npm ci', 'npm update', 'npm start'], 'c' => 1, 'e' => 'npm ci — команда для CI/CD, которая устанавливает зависимости строго по package-lock.json.'],
                ['q' => 'Зачем запускать тесты в CI/CD пайплайне?', 'o' => ['Для красоты', 'Для автоматической проверки качества кода перед деплоем', 'Для нагружения серверов', 'Это необязательно'], 'c' => 1, 'e' => 'Тесты в CI/CD ловят баги до деплоя, предотвращая падение продакшена.']
            ],
            'Мониторинг и логирование' => [
                ['q' => 'Какие 4 золотых сигнала мониторинга (Golden Signals)?', 'o' => ['Latency, Traffic, Errors, Saturation', 'CPU, RAM, Disk, Network', 'Logs, Metrics, Traces, Alerts', 'Build, Test, Deploy, Rollback'], 'c' => 0, 'e' => 'Google определил 4 ключевых сигнала: Latency, Traffic, Errors, Saturation.'],
                ['q' => 'Для чего используется Grafana?', 'o' => ['Хранение логов', 'Визуализация метрик и создание дашбордов', 'Контейнеризация', 'Управление Git'], 'c' => 1, 'e' => 'Grafana — инструмент для визуализации метрик из Prometheus, InfluxBD и других источников через дашборды.'],
                ['q' => 'Какой стек инструментов включает Elasticsearch, Logstash и Kibana?', 'o' => ['ELK Stack', 'Docker Stack', 'CI/CD Stack', 'DevOps Stack'], 'c' => 0, 'e' => 'ELK Stack (Elasticsearch + Logstash + Kibana) — популярное решение для сбора, обработки и визуализации логов.'],
                ['q' => 'Какой уровень логирования используется для диагностики проблем в продакшене?', 'o' => ['DEBUG', 'INFO', 'WARN и ERROR', 'TRACE'], 'c' => 2, 'e' => 'WARN и ERROR логи указывают на проблемы. DEBUG слишком подробный для продакшена.'],
                ['q' => 'Что такое алертинг?', 'o' => ['Ручная проверка серверов', 'Автоматические уведомления при нарушении пороговых значений', 'Тип логирования', 'Метод тестирования'], 'c' => 1, 'e' => 'Алертинг — автоматическая отправка уведомлений когда метрики превышают заданные пороги.']
            ],
            'Infrastructure as Code' => [
                ['q' => 'Какой инструмент IaC использует HCL (HashiCorp Configuration Language)?', 'o' => ['Ansible', 'Terraform', 'Pulumi', 'CloudFormation'], 'c' => 1, 'e' => 'Terraform от HashiCorp использует HCL — декларативный язык конфигурации.'],
                ['q' => 'Чем декларативный подход отличается от императивного?', 'o' => ['Ничем', 'Декларативный описывает желаемое состояние, императивный — шаги', 'Декларативный быстрее', 'Императивный проще'], 'c' => 1, 'e' => 'Декларативный: "Хочу 3 сервера с nginx". Императивный: "Создай сервер, установи nginx, повтори 3 раза".'],
                ['q' => 'Какой инструмент IaC позволяет использовать TypeScript/Python вместо YAML?', 'o' => ['Terraform', 'Ansible', 'Pulumi', 'Chef'], 'c' => 2, 'e' => 'Pulumi позволяет писать IaC на familiarных языках программирования вместо DSL.'],
                ['q' => 'Для чего используется ansible-playbook?', 'o' => ['Для запуска Ansible', 'Для выполнения сценариев конфигурационного управления', 'Для создания контейнеров', 'Для мониторинга'], 'c' => 1, 'e' => 'ansible-playbook выполняет YAML-сценарии (playbooks) для автоматической настройки серверов.'],
                ['q' => 'Какое главное преимущество IaC?', 'o' => ['Ускорение разработки', 'Воспроизводимость и версионирование инфраструктуры', 'Уменьшение стоимости серверов', 'Отсутствие необходимости в документации'], 'c' => 1, 'e' => 'IaC обеспечивает воспроизводимость и версионирование инфраструктуры в Git.']
            ],
            'Тест по DevOps' => [
                ['q' => 'Какой инструмент наиболее подходит для автоматической настройки 100 серверов?', 'o' => ['Ручная настройка', 'Ansible/Terraform', 'Bash-скрипты', 'PowerShell'], 'c' => 1, 'e' => 'Для автоматической настройки множества серверов IaC-инструменты незаменимы и масштабируемы.'],
                ['q' => 'Что такое артефакт сборки (build artifact)?', 'o' => ['Код программы', 'Скомпилированный/упакованный результат сборки (Docker image, JAR, ZIP)', 'Лог ошибок', 'Тестовый отчёт'], 'c' => 1, 'e' => 'Артефакт сборки — это результат CI: Docker-образ, JAR-файл, ZIP-архив, который деплоится на серверы.'],
                ['q' => 'Какой шаг пайплайна должен идти сразу после сборки?', 'o' => ['Деплой', 'Тестирование', 'Код-ревью', 'Мониторинг'], 'c' => 1, 'e' => 'После сборки (build) обычно идёт тестирование (test), чтобы проверить качество кода до деплоя.'],
                ['q' => 'Какое свойство микросервисной архитектуры критично для DevOps?', 'o' => ['Монолитность', 'Независимость деплоя сервисов', 'Общая база данных', 'Централизованная логика'], 'c' => 1, 'e' => 'Независимость деплоя — ключевое свойство микросервисов, позволяющее обновлять сервисы отдельно.'],
                ['q' => 'Что такое canary deployment?', 'o' => ['Полная остановка сервиса', 'Развёртывание новой версии на малой части серверов перед основным релизом', 'Откат к предыдущей версии', 'Тестирование на staging'], 'c' => 1, 'e' => 'Canary deployment — постепенное развёртывание: сначала на 1-5% серверов, мониторинг, затем на остальные.']
            ]
        ],
        'practice' => [
            'Основы DevOps' => [
                ['lang' => 'bash', 'title' => 'Запуск контейнера Docker', 'prompt' => 'Запустите Docker-контейнер с веб-приложением на порту 8080.', 'out' => '', 'start' => $startDevOps1, 'tests' => [['contains', 'docker build'], ['contains', 'docker run']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'yaml', 'title' => 'Docker Compose', 'prompt' => 'Создайте docker-compose.yml для запуска Node.js приложения с PostgreSQL.', 'out' => '', 'start' => '', 'tests' => [['contains', 'version'], ['contains', 'services'], ['contains', 'postgres']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'bash', 'title' => 'Просмотр логов Docker', 'prompt' => 'Просмотрите логи запущенного контейнера и найдите ошибки.', 'out' => '', 'start' => $startDevOps1, 'tests' => [['contains', 'docker logs']], 'diff' => 'easy', 'time' => 10]
            ],
            'CI/CD пайплайны' => [
                ['lang' => 'yaml', 'title' => 'GitHub Actions workflow', 'prompt' => 'Создайте файл .github/workflows/ci.yml для автоматического тестирования при каждом push.', 'out' => '', 'start' => $startGitlabCI, 'tests' => [['contains', 'on:'], ['contains', 'push:'], ['contains', 'npm test']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'yaml', 'title' => 'GitLab CI конфигурация', 'prompt' => 'Настройте .gitlab-ci.yml с тремя стадиями: build, test, deploy.', 'out' => '', 'start' => $startGitlabCI, 'tests' => [['contains', 'stages:'], ['contains', 'build:'], ['contains', 'test:'], ['contains', 'deploy:']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'dockerfile', 'title' => 'Dockerfile для Node.js', 'prompt' => 'Создайте Dockerfile для Node.js приложения с multi-stage build.', 'out' => '', 'start' => $startDockerfile, 'tests' => [['contains', 'FROM'], ['contains', 'WORKDIR'], ['contains', 'COPY'], ['contains', 'RUN']], 'diff' => 'medium', 'time' => 20]
            ],
            'Мониторинг и логирование' => [
                ['lang' => 'yaml', 'title' => 'Prometheus конфигурация', 'prompt' => 'Настройте Prometheus для сбора метрик с вашего приложения.', 'out' => '', 'start' => $startDevOps5, 'tests' => [['contains', 'scrape_configs'], ['contains', 'job_name']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'javascript', 'title' => 'Structured logging', 'prompt' => 'Настройте структурированные логи (JSON) в Node.js приложении.', 'out' => '', 'start' => '', 'tests' => [['contains', 'JSON'], ['contains', 'level'], ['contains', 'message']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'yaml', 'title' => 'ALERTS для мониторинга', 'prompt' => 'Создайте алерт-правило для Prometheus при error rate > 5%.', 'out' => '', 'start' => '', 'tests' => [['contains', 'alert:'], ['contains', 'expr:'], ['contains', 'error']], 'diff' => 'hard', 'time' => 25]
            ],
            'Infrastructure as Code' => [
                ['lang' => 'hcl', 'title' => 'Terraform для AWS', 'prompt' => 'Создайте Terraform-конфигурацию для запуска EC2-инстанса.', 'out' => '', 'start' => $startDevOps4, 'tests' => [['contains', 'resource'], ['contains', 'aws_instance'], ['contains', 'instance_type']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'yaml', 'title' => 'Ansible playbook', 'prompt' => 'Напишите Ansible playbook для установки и настройки Nginx на Ubuntu.', 'out' => '', 'start' => $startDevOps3, 'tests' => [['contains', 'hosts:'], ['contains', 'tasks:'], ['contains', 'nginx']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'yaml', 'title' => 'Kubernetes deployment', 'prompt' => 'Создайте манифест Kubernetes для развертывания приложения с 3 репликами.', 'out' => '', 'start' => $startDevOps2, 'tests' => [['contains', 'apiVersion'], ['contains', 'kind: Deployment'], ['contains', 'replicas: 3']], 'diff' => 'hard', 'time' => 25]
            ],
            'Тест по DevOps' => [
                ['lang' => 'dockerfile', 'title' => 'Docker healthcheck', 'prompt' => 'Добавьте healthcheck в Dockerfile для проверки доступности приложения.', 'out' => '', 'start' => $startDockerfile, 'tests' => [['contains', 'HEALTHCHECK'], ['contains', 'curl']], 'diff' => 'medium', 'time' => 15],
                ['lang' => 'yaml', 'title' => 'Environment variables', 'prompt' => 'Настройте переменные окружения для разных стадий (dev, staging, production).', 'out' => '', 'start' => '', 'tests' => [['contains', 'environment'], ['contains', 'NODE_ENV']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'yaml', 'title' => 'Rollback стратегия', 'prompt' => 'Настройте автоматический откат при неудачном деплое в Kubernetes.', 'out' => '', 'start' => '', 'tests' => [['contains', 'strategy:'], ['contains', 'RollingUpdate'], ['contains', 'maxSurge']], 'diff' => 'hard', 'time' => 25]
            ]
        ]
    ],

    13 => [
        'lessons' => [
            'Основы UI/UX дизайна' => '<h2>Основы UI/UX дизайна</h2><p>UI (User Interface) — это то, как выглядит интерфейс. UX (User Experience) — это то, как пользователь взаимодействует с продуктом.</p><h3>Разница между UI и UX</h3><p><strong>UI-дизайнер</strong> занимается визуальным оформлением: цвета, типографика, иконки, компоновка.</p><p><strong>UX-дизайнер</strong> исследует потребности пользователей, создаёт пользовательские сценарии, проектирует потоки.</p><h3>Принципы хорошего UX</h3><ul><li><strong>Видимость системы</strong> — пользователь должен понимать, что происходит</li><li><strong>Соответствие ожиданиям</strong> — поведение системы должно соответствовать ожиданиям</li><li><strong>Контроль и свобода</strong> — возможность отменить действие</li><li><strong>Последовательность</strong> — одинаковые элементы ведут себя одинаково</li><li><strong>Предотвращение ошибок</strong> — лучше предотвратить ошибку, чем показать сообщение</li></ul><h3>Цветовая палитра</h3><p>Основные принципы цвета в UI: контрастность (минимум 4.5:1 для текста), иерархия (primary, secondary, accent), семантика (красный — ошибка, зелёный — успех).</p><h3>Типографика</h3><p>Иерархия шрифтов: заголовки (H1-H6), подзаголовки, основной текст, мелкий текст. Рекомендация: максимум 2-3 шрифта в проекте.</p>',
            'Исследование пользователей' => '<h2>Исследование пользователей</h2><p>Исследование пользователей помогает понять потребности, проблемы и поведение целевой аудитории.</p><h3>Типы исследований</h3><ul><li><strong>Количественные</strong> — опросы, аналитика, A/B тесты (что происходит)</li><li><strong>Качественные</strong> — интервью, наблюдения, usability-тестирование (почему происходит)</li></ul><h3>Персоны</h3><p>Персоны — это вымышленные профили типичных пользователей:</p><pre><code>Имя: Алексей, 28 лет\nДолжность: Frontend-разработчик\nЦели: Быстро учиться новым технологиям\nБоли: Мало времени, сложно найти качественные курсы\nТехники: MacBook, VS Code, Chrome</code></pre><h3>Интервью с пользователями</h3><p>Правила проведения:</p><ol><li>Задавайте открытые вопросы (как? почему? что?)</li><li>Не ведущие вопросы (не "Вам нравится наш продукт?", а "Расскажите о вашем опыте")</li><li>Слушайте 80%, говорите 20%</li><li>Записывайте (с разрешения)</li></ol><h3>Jobs to Be Done (JTBD)</h3><p>Фреймворк JTBD фокусируется на задачах, которые пользователь пытается выполнить: "Когда [ситуация], я хочу [мотивация], чтобы [результат]".</p>',
            'Прототипирование в Figma' => '<h2>Прототипирование в Figma</h2><p>Figma — ведущий инструмент для UI/UX дизайна с поддержкой совместной работы в реальном времени.</p><h3>Основы Figma</h3><ul><li><strong>Frame</strong> — контейнер для макетов (аналог артборда)</li><li><strong>Auto Layout</strong> — автоматическая компоновка элементов (аналог Flexbox)</li><li><strong>Component</strong> — переиспользуемый элемент с вариантами (variants)</li><li><strong>Prototype</strong> — интерактивные связи между экранами</li></ul><h3>Создание прототипа</h3><ol><li>Создайте Frame нужного размера (Desktop: 1440x900, Mobile: 375x812)</li><li>Добавьте базовые элементы: текст, кнопки, изображения</li><li>Настройте Auto Layout для адаптивности</li><li>Создайте компоненты (кнопки, инпуты, карточки)</li><li>Добавьте Prototype-связи между экранами</li></ol><h3>Дизайн-система в Figma</h3><p>Создайте библиотеку компонентов с вариантами: кнопки (primary, secondary, ghost), инпуты (default, error, disabled), карточки (product, article, user).</p><h3>Совместная работа</h3><p>Figma позволяет нескольким дизайнерам работать одновременно. Используйте: обзоры (Reviews), комментарии, версионирование (Branching).</p>',
            'Дизайн-системы' => '<h2>Дизайн-системы</h2><p>Дизайн-система — это набор стандартов, компонентов и правил для создания консистентного пользовательского опыта.</p><h3>Структура дизайн-системы</h3><ul><li><strong>Design Tokens</strong> — базовые переменные: цвета, типографика, отступы, тени</li><li><strong>Компоненты</strong> — кнопки, инпуты, карточки, модалки</li><li><strong>Паттерны</strong> — типовые решения: форма регистрации, корзина, навигация</li><li><strong>Документация</strong> — инструкции по использованию</li></ul><h3>Design Tokens</h3><pre><code>// Цвета\n--color-primary: #3B82F6;\n--color-error: #EF4444;\n--color-success: #10B981;\n\n// Типографика\n--font-size-sm: 14px;\n--font-size-base: 16px;\n--font-size-lg: 20px;\n\n// Отступы\n--spacing-xs: 4px;\n--spacing-sm: 8px;\n--spacing-md: 16px;\n--spacing-lg: 24px;</code></pre><h3>Примеры дизайн-систем</h3><ul><li><strong>Material Design</strong> (Google) — для Android и веба</li><li><strong>Human Interface Guidelines</strong> (Apple) — для iOS/macOS</li><li><strong>Ant Design</strong> — для enterprise-приложений</li><li><strong>Chakra UI</strong> — для React</li></ul><h3>Создание дизайн-системы</h3><p>Начните с аудита существующего интерфейса, выделите повторяющиеся паттерны, создайте базовые компоненты, документируйте каждый элемент.</p>',
            'Тест по UI/UX' => '<h2>Тест по UI/UX</h2><p>Проверьте свои знания по основам UI/UX дизайна, исследованию пользователей, прототипированию и дизайн-системам.</p>'
        ],
        'quizzes' => [
            'Основы UI/UX дизайна' => [
                ['q' => 'Чем отличается UI от UX?', 'o' => ['Ничем', 'UI — визуал, UX — взаимодействие', 'UI проще, UX сложнее', 'UI для мобильных, UX для веба'], 'c' => 1, 'e' => 'UI (User Interface) — визуальный дизайн, UX (User Experience) — как пользователь чувствует себя в продукте.'],
                ['q' => 'Какой минимум контрастности текста рекомендуется (WCAG)?', 'o' => ['2:1', '3:1', '4.5:1', '7:1'], 'c' => 2, 'e' => 'WCAG рекомендует минимум 4.5:1 для обычного текста и 3:1 для крупного текста (18px+).'],
                ['q' => 'Какой принцип UX гласит "Лучше предотвратить ошибку, чем сообщить о ней"?', 'o' => ['Видимость системы', 'Предотвращение ошибок', 'Контроль и свобода', 'Последовательность'], 'c' => 1, 'e' => 'Принцип предотвращения ошибок: дизайнер должен спроектировать интерфейс так, чтобы пользователь не мог ошибиться.'],
                ['q' => 'Сколько шрифтов рекомендуется использовать в проекте?', 'o' => ['1', '2-3', '5-6', 'Сколько угодно'], 'c' => 1, 'e' => 'Рекомендуется 2-3 шрифта: один для заголовков, один для основного текста, возможно третий для акцентов.'],
                ['q' => 'Что такое "affordance" в дизайне?', 'o' => ['Стоимость дизайна', 'Свойство объекта, подсказывающее как его использовать', 'Яркость цвета', 'Размер элемента'], 'c' => 1, 'e' => 'Affordance (предлагаемое действие) — свойство объекта, которое подсказывает пользователю, как с ним взаимодействовать.']
            ],
            'Исследование пользователей' => [
                ['q' => 'Какой тип исследования отвечает на вопрос "почему"?', 'o' => ['Количественное', 'Качественное', 'A/B тест', 'Аналитика'], 'c' => 1, 'e' => 'Качественные исследования (интервью, наблюдения) помогают понять причины поведения пользователей.'],
                ['q' => 'Что такое персона в UX?', 'o' => ['Реальный пользователь', 'Вымышленный профиль типичного пользователя', 'Дизайнер интерфейсов', 'Разработчик'], 'c' => 1, 'e' => 'Персона — это выдуманный профиль на основе данных: имя, возраст, цели, боли, техники.'],
                ['q' => 'Какой формат вопросов лучше использовать в интервью?', 'o' => ['Закрытые (да/нет)', 'Открытые (как? почему? что?)', 'Ведущие', 'Множественный выбор'], 'c' => 1, 'e' => 'Открытые вопросы раскрывают мысли и опыт пользователя: "Расскажите о вашем опыте...".'],
                ['q' => 'Что такое JTBD (Jobs to Be Done)?', 'o' => ['Вакансии в IT', 'Фреймворк, описывающий задачи, которые пользователь пытается выполнить', 'Тип исследования', 'Инструмент прототипирования'], 'c' => 1, 'e' => 'JTBD фокусируется на "работе", которую продукт выполняет для пользователя.'],
                ['q' => 'Какой процент времени должен слушать исследователь в интервью?', 'o' => ['50%', '80%', '20%', '100%'], 'c' => 1, 'e' => 'Исследователь должен слушать ~80% времени, говорить ~20%.']
            ],
            'Прототипирование в Figma' => [
                ['q' => 'Что такое Frame в Figma?', 'o' => ['Текстовый блок', 'Контейнер для макета (аналог артборда)', 'Кнопка', 'Изображение'], 'c' => 1, 'e' => 'Frame — это контейнер для создания экранов. Стандартные размеры: Desktop 1440x900, Mobile 375x812.'],
                ['q' => 'Чем Auto Layout похож на CSS?', 'o' => ['Grid', 'Flexbox', 'Float', 'Position'], 'c' => 1, 'e' => 'Auto Layout в Figma работает аналогично CSS Flexbox: направление, выравнивание, отступы.'],
                ['q' => 'Как создать переиспользуемый компонент в Figma?', 'o' => ['Ctrl+C / Ctrl+V', 'Выделить элемент - Create Component (Ctrl+Alt+K)', 'Дублировать', 'Импортировать'], 'c' => 1, 'e' => 'Компонент создаётся через Ctrl+Alt+K или кнопку в панели. Компоненты имеют варианты (Variants).'],
                ['q' => 'Что такое Prototype в Figma?', 'o' => ['Финальный дизайн', 'Интерактивные связи между экранами', 'Исходный код', 'Документация'], 'c' => 1, 'e' => 'Prototype — это интерактивная модель, где можно кликать по элементам и переходить между экранами.'],
                ['q' => 'Какой стандартный размер Frame для десктопа в Figma?', 'o' => ['1920x1080', '1440x900', '1280x720', '1024x768'], 'c' => 1, 'e' => 'Стандартный размер для десктопного дизайна — 1440x900 пикселей.']
            ],
            'Дизайн-системы' => [
                ['q' => 'Что такое Design Tokens?', 'o' => ['Иконки', 'Базовые переменные дизайна: цвета, типографика, отступы', 'Компоненты', 'Паттерны'], 'c' => 1, 'e' => 'Design Tokens — это переменные (цвета, размеры шрифтов, отступы), которые обеспечивают консистентность.'],
                ['q' => 'Какой пример дизайн-системы от Google?', 'o' => ['Human Interface Guidelines', 'Material Design', 'Ant Design', 'Chakra UI'], 'c' => 1, 'e' => 'Material Design — дизайн-система Google для Android и веб-приложений.'],
                ['q' => 'Из чего состоит хорошая дизайн-система?', 'o' => ['Только из компонентов', 'Токены + компоненты + паттерны + документация', 'Только из документации', 'Только из цветов'], 'c' => 1, 'e' => 'Дизайн-система включает: Design Tokens, компоненты, паттерны и документацию.'],
                ['q' => 'Зачем нужна документация в дизайн-системе?', 'o' => ['Для красоты', 'Чтобы разработчики знали как использовать компоненты', 'Для SEO', 'Для маркетинга'], 'c' => 1, 'e' => 'Документация описывает как, когда и зачем использовать каждый компонент.'],
                ['q' => 'Какой компонент есть в большинстве дизайн-систем?', 'o' => ['Карусель', 'Кнопка (Button)', 'Чат', 'Видео-плеер'], 'c' => 1, 'e' => 'Кнопка — базовый компонент любой дизайн-системы с вариантами: primary, secondary, ghost, danger.']
            ],
            'Тест по UI/UX' => [
                ['q' => 'Какой первый шаг в UX-дизайне?', 'o' => ['Нарисовать макет', 'Провести исследование пользователей', 'Написать код', 'Выбрать цвета'], 'c' => 1, 'e' => 'UX-дизайн начинается с исследования: понять потребности пользователей, прежде чем проектировать решение.'],
                ['q' => 'Что такое "user flow"?', 'o' => ['Поток пользователей — путь пользователя через продукт для выполнения задачи', 'Тип исследования', 'Дизайн-компонент', 'Протокол тестирования'], 'c' => 0, 'e' => 'User flow — это визуализация шагов, которые пользователь совершает для достижения цели.'],
                ['q' => 'Какой метод лучше для тестирования usability?', 'o' => ['Опрос', 'Usability тестирование с реальными пользователями', 'A/B тест', 'Аналитика'], 'c' => 1, 'e' => 'Usability тестирование (наблюдение за реальными пользователями) лучше всего выявляет проблемы.'],
                ['q' => 'Что такое "responsive design"?', 'o' => ['Быстрый дизайн', 'Адаптивный дизайн под разные размеры экранов', 'Красивый дизайн', 'Медленный дизайн'], 'c' => 1, 'e' => 'Responsive design — адаптивная верстка, при которой интерфейс корректно отображается на любых устройствах.'],
                ['q' => 'Какой принцип гласит "Одинаковые элементы должны вести себя одинаково"?', 'o' => ['Видимость системы', 'Последовательность (Consistency)', 'Обратная связь', 'Предотвращение ошибок'], 'c' => 1, 'e' => 'Consistency (последовательность) — если кнопка работает как ссылка в одном месте, она должна работать так везде.']
            ]
        ],
        'practice' => [
            'Основы UI/UX дизайна' => [
                ['lang' => 'css', 'title' => 'Цветовая палитра', 'prompt' => 'Создайте CSS-переменные для дизайн-системы с основными, вторичными и акцентными цветами.', 'out' => '', 'start' => '', 'tests' => [['contains', ':root'], ['contains', '--color-primary'], ['contains', '--color-secondary']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'css', 'title' => 'Типографическая шкала', 'prompt' => 'Создайте типографическую шкалу с заголовками H1-H6 и базовым текстом.', 'out' => '', 'start' => '', 'tests' => [['contains', 'font-size'], ['contains', 'h1'], ['contains', 'h2']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'html', 'title' => 'Доступность (a11y)', 'prompt' => 'Добавьте ARIA-атрибуты и alt-тексты для улучшения доступности страницы.', 'out' => '', 'start' => '<button>Click</button>\n<img src="photo.jpg">\n<nav></nav>', 'tests' => [['contains', 'aria-label'], ['contains', 'alt='], ['contains', 'role=']], 'diff' => 'medium', 'time' => 20]
            ],
            'Исследование пользователей' => [
                ['lang' => 'markdown', 'title' => 'Персона пользователя', 'prompt' => 'Создайте детальную персону для образовательной платформы.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Имя'], ['contains', 'Цели'], ['contains', 'Боли'], ['contains', 'Техники']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'markdown', 'title' => 'Сценарий JTBD', 'prompt' => 'Напишите 3 JTBD сценария для онлайн-курсов.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Когда'], ['contains', 'я хочу'], ['contains', 'чтобы']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'markdown', 'title' => 'Протокол интервью', 'prompt' => 'Составьте протокол интервью из 10 вопросов для исследования пользователей курсов.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Расскажите'], ['contains', 'Как вы'], ['contains', 'Почему']], 'diff' => 'medium', 'time' => 20]
            ],
            'Прототипирование в Figma' => [
                ['lang' => 'text', 'title' => 'Структура Frame', 'prompt' => 'Опишите структуру макета главной страницы образовательной платформы.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Header'], ['contains', 'Sidebar'], ['contains', 'Content'], ['contains', 'Footer']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'text', 'title' => 'Auto Layout карточки', 'prompt' => 'Создайте описание карточки курса с Auto Layout.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Image'], ['contains', 'Title'], ['contains', 'Description'], ['contains', 'Button']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'text', 'title' => 'Prototype связи', 'prompt' => 'Опишите Prototype-связи между экранами формы регистрации.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Screen 1'], ['contains', 'Screen 2'], ['contains', 'On Click'], ['contains', 'Navigate']], 'diff' => 'medium', 'time' => 20]
            ],
            'Дизайн-системы' => [
                ['lang' => 'css', 'title' => 'Design Tokens', 'prompt' => 'Создайте CSS-переменные (Design Tokens) для дизайн-системы.', 'out' => '', 'start' => '', 'tests' => [['contains', '--spacing-'], ['contains', '--font-'], ['contains', '--color-'], ['contains', '--shadow-']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'css', 'title' => 'Компонент кнопки', 'prompt' => 'Создайте CSS для кнопки с вариантами: primary, secondary, ghost.', 'out' => '', 'start' => '', 'tests' => [['contains', '.btn'], ['contains', '.btn-primary'], ['contains', '.btn-secondary'], ['contains', '.btn-ghost']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'markdown', 'title' => 'Документация компонента', 'prompt' => 'Напишите документацию для компонента "Карточка курса".', 'out' => '', 'start' => '', 'tests' => [['contains', 'Описание'], ['contains', 'Пропсы'], ['contains', 'Пример использования']], 'diff' => 'medium', 'time' => 20]
            ],
            'Тест по UI/UX' => [
                ['lang' => 'css', 'title' => 'Адаптивный дизайн', 'prompt' => 'Создайте медиа-запросы для адаптивной верстки (мобильная, планшет, десктоп).', 'out' => '', 'start' => '', 'tests' => [['contains', '@media'], ['contains', 'max-width'], ['contains', 'min-width']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'html', 'title' => 'Форма с валидацией', 'prompt' => 'Создайте HTML-форму регистрации с валидацией и сообщениями об ошибках.', 'out' => '', 'start' => '', 'tests' => [['contains', 'required'], ['contains', 'pattern'], ['contains', 'error-message']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'css', 'title' => 'Анимации интерфейса', 'prompt' => 'Добавьте CSS-анимации для кнопок и переходов между состояниями.', 'out' => '', 'start' => '', 'tests' => [['contains', 'transition'], ['contains', ':hover'], ['contains', 'transform']], 'diff' => 'hard', 'time' => 25]
            ]
        ]
    ],

    14 => [
        'lessons' => [
            'Основы React' => '<h2>Основы React</h2><p>React — JavaScript-библиотека для построения пользовательских интерфейсов, разработана Facebook (Meta) в 2013 году.</p><h3>JSX (JavaScript XML)</h3><p>JSX позволяет писать HTML-подобный синтаксис в JavaScript:</p><pre><code>const element = &lt;h1&gt;Привет, {name}!&lt;/h1&gt;;\nconst list = (\n  &lt;ul&gt;\n    {items.map(item =&gt; &lt;li key={item.id}&gt;{item.text}&lt;/li&gt;)}\n  &lt;/ul&gt;\n);</code></pre><h3>Компоненты</h3><p>Компоненты — строительные блоки React-приложения:</p><pre><code>// Функциональный компонент\nfunction Welcome({ name }) {\n  return &lt;h1&gt;Привет, {name}!&lt;/h1&gt;;\n}\n\n// Использование\n&lt;Welcome name="Алексей" /&gt;</code></pre><h3>Пропсы (Props)</h3><p>Props — это входные данные компонента, передаваемые родителем. Props доступны через аргумент функции.</p><h3>Условный рендеринг</h3><pre><code>{isLoggedIn ? &lt;Dashboard /&gt; : &lt;LoginForm /&gt;}\n{items.length &gt; 0 && &lt;ItemList items={items} /&gt;}</code></pre><h3>Списки и ключи</h3><p>При рендеринге списков обязательно указывайте уникальный <code>key</code> для каждого элемента.</p>',
            'Хуки в React' => '<h2>Хуки в React</h2><p>Хуки — функции, позволяющие использовать состояние и другие возможности React в функциональных компонентах.</p><h3>useState</h3><pre><code>import { useState } from \'react\';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    &lt;button onClick={() =&gt; setCount(count + 1)}&gt;\n      Кликов: {count}\n    &lt;/button&gt;\n  );\n}</code></pre><h3>useEffect</h3><p>Для побочных эффектов: запросы к API, подписки, таймеры:</p><pre><code>import { useEffect, useState } from \'react\';\n\nfunction UserProfile({ userId }) {\n  const [user, setUser] = useState(null);\n  useEffect(() =&gt; {\n    fetch(`/api/users/${userId}`)\n      .then(res =&gt; res.json())\n      .then(data =&gt; setUser(data));\n  }, [userId]);\n  return user ? &lt;div&gt;{user.name}&lt;/div&gt; : &lt;div&gt;Загрузка...&lt;/div&gt;;\n}</code></pre><h3>useContext</h3><pre><code>const ThemeContext = React.createContext(\'light\');\nfunction App() {\n  return (\n    &lt;ThemeContext.Provider value="dark"&gt;\n      &lt;Toolbar /&gt;\n    &lt;/ThemeContext.Provider&gt;\n  );\n}\nfunction Toolbar() {\n  const theme = useContext(ThemeContext);\n  return &lt;div className={theme}&gt;...&lt;/div&gt;;\n}</code></pre><h3>useRef</h3><p>Для доступа к DOM-элементам или сохранения изменяемого значения без ре-рендера:</p><pre><code>const inputRef = useRef(null);\ninputRef.current.focus();</code></pre><h3>Пользовательские хуки</h3><p>Создавайте свои хуки для переиспользования логики: <code>useFetch</code>, <code>useLocalStorage</code>, <code>useDebounce</code>.</p>',
            'Роутинг и навигация' => '<h2>Роутинг и навигация</h2><p>React Router — стандартная библиотека для маршрутизации в React-приложениях.</p><h3>Установка и настройка</h3><pre><code>npm install react-router-dom</code></pre><h3>Базовый роутинг</h3><pre><code>import { BrowserRouter, Routes, Route, Link } from \'react-router-dom\';\n\nfunction App() {\n  return (\n    &lt;BrowserRouter&gt;\n      &lt;nav&gt;\n        &lt;Link to="/"&gt;Главная&lt;/Link&gt;\n        &lt;Link to="/about"&gt;О нас&lt;/Link&gt;\n      &lt;/nav&gt;\n      &lt;Routes&gt;\n        &lt;Route path="/" element={&lt;Home /&gt;} /&gt;\n        &lt;Route path="/about" element={&lt;About /&gt;} /&gt;\n        &lt;Route path="/users/:id" element={&lt;UserProfile /&gt;} /&gt;\n        &lt;Route path="*" element={&lt;NotFound /&gt;} /&gt;\n      &lt;/Routes&gt;\n    &lt;/BrowserRouter&gt;\n  );\n}</code></pre><h3>Параметры маршрута</h3><pre><code>import { useParams } from \'react-router-dom\';\n\nfunction UserProfile() {\n  const { id } = useParams();\n  return &lt;div&gt;Пользователь {id}&lt;/div&gt;;\n}</code></pre><h3>Вложенные маршруты</h3><pre><code>&lt;Route path="/dashboard" element={&lt;Dashboard /&gt;}&gt;\n  &lt;Route path="settings" element={&lt;Settings /&gt;} /&gt;\n  &lt;Route path="profile" element={&lt;Profile /&gt;} /&gt;\n&lt;/Route&gt;</code></pre><h3>useNavigate</h3><pre><code>const navigate = useNavigate();\nnavigate(\'/login\');\nnavigate(-1); // назад</code></pre>',
            'Управление состоянием' => '<h2>Управление состоянием</h2><p>Для управления состоянием в React есть множество подходов: встроенные хуки, Context, Redux, Zustand.</p><h3>Локальное состояние (useState)</h3><p>Для простых случаев: форма, модальное окно, переключатель.</p><h3>Context API</h3><p>Для глобального состояния без внешних библиотек:</p><pre><code>const AppContext = createContext();\n\nfunction App() {\n  const [theme, setTheme] = useState(\'light\');\n  const [user, setUser] = useState(null);\n  return (\n    &lt;AppContext.Provider value={{ theme, setTheme, user, setUser }}&gt;\n      &lt;Router /&gt;\n    &lt;/AppContext.Provider&gt;\n  );\n}</code></pre><h3>Redux Toolkit</h3><p>Для сложных приложений с множеством состояний:</p><pre><code>import { createSlice, configureStore } from \'@reduxjs/toolkit\';\n\nconst counterSlice = createSlice({\n  name: \'counter\',\n  initialState: { value: 0 },\n  reducers: {\n    increment: (state) =&gt; { state.value += 1; },\n    decrement: (state) =&gt; { state.value -= 1; },\n  },\n});\n\nconst store = configureStore({ reducer: { counter: counterSlice.reducer } });</code></pre><h3>Zustand</h3><p>Лёгкая альтернатива Redux:</p><pre><code>import create from \'zustand\';\n\nconst useStore = create((set) =&gt; ({\n  count: 0,\n  increment: () =&gt; set((state) =&gt; ({ count: state.count + 1 })),\n}));</code></pre><h3>Когда что использовать?</h3><ul><li>useState — простые локальные состояния</li><li>Context — тема, язык, текущий пользователь</li><li>Redux/Zustand — сложная бизнес-логика, много состояний</li></ul>'
        ],
        'quizzes' => [
            'Основы React' => [
                ['q' => 'Что такое JSX?', 'o' => ['Новый язык программирования', 'Расширение JavaScript для написания HTML-подобного кода', 'Тип данных', 'Библиотека'], 'c' => 1, 'e' => 'JSX — это синтаксическое расширение, позволяющее писать HTML-подобную разметку в JavaScript-кодах.'],
                ['q' => 'Что такое Props в React?', 'o' => ['Состояние компонента', 'Входные данные, передаваемые родителем в дочерний компонент', 'Метод жизненного цикла', 'Глобальное состояние'], 'c' => 1, 'e' => 'Props (properties) — это входные данные компонента, передаваемые родителем.'],
                ['q' => 'Как рендерить список элементов в React?', 'o' => ['Через for loop', 'Через метод .map() на массиве', 'Через while loop', 'Через forEach'], 'c' => 1, 'e' => 'В React для рендеринга списков используется .map(). Каждый элемент должен иметь уникальный key.'],
                ['q' => 'Что такое компонент в React?', 'o' => ['Файл JavaScript', 'Переиспользуемая функция, возвращающая JSX', 'HTML-тег', 'CSS-класс'], 'c' => 1, 'e' => 'Компонент — это функция, которая принимает props и возвращает JSX-разметку.'],
                ['q' => 'Как условно отрендерить элемент?', 'o' => ['if/else внутри return', 'Тернарный оператор или &&', 'switch/case', 'for loop'], 'c' => 1, 'e' => 'Для условного рендеринга: тернарный оператор {condition ? <A /> : <B />} или {condition && <A />}.']
            ],
            'Хуки в React' => [
                ['q' => 'Что делает useState?', 'o' => ['Побочные эффекты', 'Управление состоянием компонента', 'Роутинг', 'Работа с DOM'], 'c' => 1, 'e' => 'useState возвращает [значение, функциюОбновления]. При вызове функции обновления компонент ре-рендерится.'],
                ['q' => 'Когда срабатывает useEffect с пустым массивом зависимостей?', 'o' => ['Каждый рендер', 'Только при монтировании компонента', 'При каждом изменении пропсов', 'Никогда'], 'c' => 1, 'e' => 'useEffect(() => {}, []) — пустой массив означает, что эффект запустится только один раз при монтировании.'],
                ['q' => 'Для чего используется useContext?', 'o' => ['Для создания контекста', 'Для чтения значения из контекста в дочернем компоненте', 'Для управления формами', 'Для работы с API'], 'c' => 1, 'e' => 'useContext позволяет прочитать значение Context без пропс-дриллинга.'],
                ['q' => 'Что такое custom hook?', 'o' => ['Встроенный хук React', 'Пользовательская функция с префиксом use для переиспользования логики', 'Компонент', 'Тип пропсов'], 'c' => 1, 'e' => 'Custom hook — это функция, начинающаяся с use, которая может вызывать другие хуки.'],
                ['q' => 'Что делает useRef?', 'o' => ['Ссылка на DOM-элемент или изменяемое значение без ре-рендера', 'Управление формами', 'Работа с API', 'Создание компонентов'], 'c' => 0, 'e' => 'useRef возвращает объект {current: ...}. Изменение .current не вызывает ре-рендер.']
            ],
            'Роутинг и навигация' => [
                ['q' => 'Какая библиотека стандартна для роутинга в React?', 'o' => ['React Router', 'Redux', 'Axios', 'Moment.js'], 'c' => 0, 'e' => 'React Router — стандартная библиотека для маршрутизации в React-приложениях.'],
                ['q' => 'Как получить параметр из URL (например /users/123)?', 'o' => ['useParams()', 'useQuery()', 'useRoute()', 'useURL()'], 'c' => 0, 'e' => 'useParams() возвращает объект с параметрами маршрута: { id: "123" }.'],
                ['q' => 'Как программно перейти на другой маршрут?', 'o' => ['window.location', 'useNavigate()', 'Link', 'redirect()'], 'c' => 1, 'e' => 'useNavigate() возвращает функцию навигации: navigate("/login").'],
                ['q' => 'Что такое "catch-all" маршрут?', 'o' => ['Маршрут для всех страниц', 'Маршрут path="*", отлавливающий несуществующие пути', 'Главная страница', 'Страница ошибки'], 'c' => 1, 'e' => 'Маршрут с path="*" отлавливает все несовпавшие пути (аналог 404 страницы).'],
                ['q' => 'Для чего используется вложенные Routes?', 'o' => ['Для создания мультиязычности', 'Для отображения дочерних компонентов внутри родительского маршрута', 'Для кеширования', 'Для SEO'], 'c' => 1, 'e' => 'Вложенные Routes позволяют отображать подстраницы внутри общего layout.']
            ],
            'Управление состоянием' => [
                ['q' => 'Когда лучше использовать useState, а не Redux?', 'o' => ['Всегда', 'Для простых локальных состояний (формы, модалки)', 'Никогда', 'Только для темы'], 'c' => 1, 'e' => 'useState подходит для простых локальных состояний. Redux нужен для сложной бизнес-логики.'],
                ['q' => 'Что такое Context API?', 'o' => ['Библиотека', 'Встроенный механизм передачи данных через дерево компонентов без пропсов', 'Тип хука', 'CSS-метод'], 'c' => 1, 'e' => 'Context позволяет передавать данные глубоко в дерево компонентов без пропс-дриллинга.'],
                ['q' => 'Какой state менеджер самый легковесный?', 'o' => ['Redux', 'MobX', 'Zustand', 'Apollo Client'], 'c' => 2, 'e' => 'Zustand — легковесный state менеджер (~1KB), простой API, не требует провайдеров.'],
                ['q' => 'Что такое "prop drilling"?', 'o' => ['Передача пропсов через множество уровней компонентов', 'Использование Context', 'Удаление пропсов', 'Тип пропсов'], 'c' => 0, 'e' => 'Prop drilling — проблема, когда пропсы передаются через 5+ уровней компонентов.'],
                ['q' => 'Для чего используется Redux Toolkit?', 'o' => ['Для работы с DOM', 'Для упрощения работы с Redux (createSlice, configureStore)', 'Для стилизации', 'Для роутинга'], 'c' => 1, 'e' => 'Redux Toolkit упрощает Redux: createSlice для редюсеров, configureStore для создания стора.']
            ],
            'Тест по React' => [
                ['q' => 'Что такое React.memo?', 'o' => ['Компонент без пропсов', 'HOC для оптимизации ре-рендера при неизменных пропсах', 'Компонент без состояния', 'Компонент без JSX'], 'c' => 1, 'e' => 'React.memo оборачивает компонент и пропускает ре-рендер, если пропсы не изменились.'],
                ['q' => 'Как правильно обновлять состояние на основе предыдущего?', 'o' => ['setState({ count: count + 1 })', 'setState(prev => ({ count: prev.count + 1 }))', 'this.state.count++', 'forceUpdate()'], 'c' => 1, 'e' => 'Используйте функциональное обновление: setCount(prev => prev + 1).'],
                ['q' => 'Для чего используется useMemo?', 'o' => ['Для запоминания результата вычисления', 'Для работы с формами', 'Для роутинга', 'Для стилизации'], 'c' => 0, 'e' => 'useMemo кеширует результат вычисления и пересчитывает только при изменении зависимостей.'],
                ['q' => 'Что такое Error Boundary?', 'o' => ['Обработка ошибок JavaScript', 'Компонент ловящий ошибки в дочерних компонентах', 'Тип пропсов', 'Хук для ошибок'], 'c' => 1, 'e' => 'Error Boundary — классовый компонент с componentDidCatch, ловящий ошибки рендеринга.'],
                ['q' => 'Какой хук позволяет выполнять副作用и при изменении зависимостей?', 'o' => ['useState', 'useEffect', 'useContext', 'useRef'], 'c' => 1, 'e' => 'useEffect(callback, [deps]) запускает callback при монтировании и при изменении зависимостей.']
            ]
        ],
        'practice' => [
            'Основы React' => [
                ['lang' => 'jsx', 'title' => 'Компонент карточки', 'prompt' => 'Создайте React-компонент карточки товара с изображением, названием и ценой.', 'out' => '', 'start' => $startReact1, 'tests' => [['contains', 'function Card'], ['contains', 'props'], ['contains', 'return']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'jsx', 'title' => 'Список элементов', 'prompt' => 'Отрендерите список пользователей с помощью .map().', 'out' => '', 'start' => '', 'tests' => [['contains', '.map('], ['contains', 'key='], ['contains', 'return']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'jsx', 'title' => 'Условный рендеринг', 'prompt' => 'Покажите разный контент в зависимости от статуса авторизации.', 'out' => '', 'start' => '', 'tests' => [['contains', '?'], ['contains', 'isLoggedIn'], ['contains', '&&']], 'diff' => 'easy', 'time' => 15]
            ],
            'Хуки в React' => [
                ['lang' => 'jsx', 'title' => 'Счётчик с useState', 'prompt' => 'Создайте счётчик с кнопками + и - используя useState.', 'out' => '', 'start' => $startReact2, 'tests' => [['contains', 'useState'], ['contains', 'setCount'], ['contains', 'onClick']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'jsx', 'title' => 'Загрузка данных с useEffect', 'prompt' => 'Загрузите данные пользователя при монтировании компонента.', 'out' => '', 'start' => '', 'tests' => [['contains', 'useEffect'], ['contains', 'fetch'], ['contains', 'useState']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'jsx', 'title' => 'Пользовательский хук useFetch', 'prompt' => 'Создайте хук useFetch для загрузки данных с API.', 'out' => '', 'start' => '', 'tests' => [['contains', 'function useFetch'], ['contains', 'useState'], ['contains', 'useEffect'], ['contains', 'return']], 'diff' => 'hard', 'time' => 25]
            ],
            'Роутинг и навигация' => [
                ['lang' => 'jsx', 'title' => 'Настройка роутинга', 'prompt' => 'Настройте маршруты для приложения с главной, о нас и профилем.', 'out' => '', 'start' => $startReactRouter, 'tests' => [['contains', 'BrowserRouter'], ['contains', 'Routes'], ['contains', 'Route']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'jsx', 'title' => 'Навигационное меню', 'prompt' => 'Создайте навигационное меню с активными ссылками.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Link'], ['contains', 'NavLink'], ['contains', 'active']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'jsx', 'title' => 'Динамические маршруты', 'prompt' => 'Создайте страницу профиля с динамическим параметром ID.', 'out' => '', 'start' => '', 'tests' => [['contains', 'useParams'], ['contains', ':id'], ['contains', 'UserProfile']], 'diff' => 'medium', 'time' => 20]
            ],
            'Управление состоянием' => [
                ['lang' => 'jsx', 'title' => 'Context для темы', 'prompt' => 'Создайте Context для переключения темы (светлая/тёмная).', 'out' => '', 'start' => '', 'tests' => [['contains', 'createContext'], ['contains', 'Provider'], ['contains', 'useContext']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'jsx', 'title' => 'Redux store', 'prompt' => 'Настройте Redux store с одним редюсером для корзины.', 'out' => '', 'start' => $startReactRedux, 'tests' => [['contains', 'createSlice'], ['contains', 'configureStore'], ['contains', 'Provider']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'jsx', 'title' => 'Zustand store', 'prompt' => 'Создайте Zustand store для управления списком задач.', 'out' => '', 'start' => '', 'tests' => [['contains', 'create('], ['contains', 'set('], ['contains', 'addTodo'], ['contains', 'removeTodo']], 'diff' => 'hard', 'time' => 25]
            ],
            'Тест по React' => [
                ['lang' => 'jsx', 'title' => 'Оптимизация производительности', 'prompt' => 'Оптимизируйте компонент с помощью React.memo и useMemo.', 'out' => '', 'start' => '', 'tests' => [['contains', 'React.memo'], ['contains', 'useMemo'], ['contains', 'useCallback']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'jsx', 'title' => 'Обработка ошибок', 'prompt' => 'Создайте Error Boundary для отлова ошибок в дочерних компонентах.', 'out' => '', 'start' => '', 'tests' => [['contains', 'componentDidCatch'], ['contains', 'getDerivedStateFromError'], ['contains', 'Error']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'jsx', 'title' => 'Форма с валидацией', 'prompt' => 'Создайте форму регистрации с управляемыми полями и валидацией.', 'out' => '', 'start' => '', 'tests' => [['contains', 'useState'], ['contains', 'onChange'], ['contains', 'onSubmit'], ['contains', 'value=']], 'diff' => 'medium', 'time' => 20]
            ]
        ]
    ],

    15 => [
        'lessons' => [
            'Основы Node.js' => '<h2>Основы Node.js</h2><p>Node.js — среда выполнения JavaScript на стороне сервера, построенная на движке V8 (Chrome).</p><h3>Установка</h3><p>Скачайте LTS-версию с <code>nodejs.org</code> или используйте nvm: <code>nvm install 18 && nvm use 18</code>.</p><h3>Запуск JavaScript</h3><pre><code>node script.js          # запуск файла\nnode -e "console.log(1)"  # запуск строки кода\nnode                    # REPL (интерактивный режим)</code></pre><h3>Модули (CommonJS)</h3><pre><code>// math.js\nmodule.exports = {\n  add: (a, b) => a + b,\n  multiply: (a, b) => a * b\n};\n\n// app.js\nconst math = require(\'./math\');\nconsole.log(math.add(2, 3));  // 5</code></pre><h3>Модули (ES Modules)</h3><pre><code>// math.js\nexport const add = (a, b) => a + b;\n\n// app.js\nimport { add } from \'./math.js\';\nconsole.log(add(2, 3));</code></pre><h3>Асинхронность</h3><p>Node.js использует event loop для неблокирующего I/O:</p><pre><code>// async/await\nasync function main() {\n  const data = await fs.promises.readFile(\'file.txt\', \'utf8\');\n  console.log(data);\n}</code></pre><h3>Пакетный менеджер npm</h3><pre><code>npm init -y               # инициализация package.json\nnpm install express        # установка пакета\nnpm install -D nodemon     # dev-зависимость\nnpm start                  # запуск скрипта из scripts</code></pre>',
            'Express.js' => '<h2>Express.js</h2><p>Express — минималистичный фреймворк для Node.js, де-факто стандарт для веб-серверов.</p><h3>Установка и базовый сервер</h3><pre><code>npm install express\n\nconst express = require(\'express\');\nconst app = express();\n\napp.get(\'/\', (req, res) => {\n  res.json({ message: \'Привет, мир!\' });\n});\n\napp.listen(3000, () => {\n  console.log(\'Сервер запущен на порту 3000\');\n});</code></pre><h3>Маршруты (Routes)</h3><pre><code>app.get(\'/users\', getUsers);           // GET /users\napp.post(\'/users\', createUser);       // POST /users\napp.get(\'/users/:id\', getUser);       // GET /users/123\napp.put(\'/users/:id\', updateUser);    // PUT /users/123\napp.delete(\'/users/:id\', deleteUser); // DELETE /users/123</code></pre><h3>Мидлвары (Middleware)</h3><pre><code>// Логирование\napp.use((req, res, next) => {\n  console.log(`${req.method} ${req.url}`);\n  next();\n});\n\n// Парсинг JSON\napp.use(express.json());\n\n// Статические файлы\napp.use(express.static(\'public\'));</code></pre><h3>Роутер Express</h3><pre><code>const router = express.Router();\n\nrouter.get(\'/\', listUsers);\nrouter.post(\'/\', createUser);\nrouter.get(\'/:id\', getUser);\n\napp.use(\'/api/users\', router);</code></pre><h3>Обработка ошибок</h3><pre><code>app.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ error: \'Что-то пошло не так!\' });\n});</code></pre>',
            'REST API' => '<h2>REST API</h2><p>REST (Representational State Transfer) — архитектурный стиль проектирования API.</p><h3>Принципы REST</h3><ul><li><strong>Клиент-сервер</strong> — разделение ответственности</li><li><strong>Без состояния</strong> — каждый запрос содержит всю необходимую информацию</li><li><strong>Кеширование</strong> — ответы могут кешироваться</li><li><strong>Единообразный интерфейс</strong> — стандартные HTTP-методы и коды</li></ul><h3>HTTP-методы</h3><pre><code>GET    /api/users       → список пользователей\nGET    /api/users/123   → один пользователь\nPOST   /api/users       → создание\nPUT    /api/users/123   → полное обновление\nPATCH  /api/users/123   → частичное обновление\nDELETE /api/users/123   → удаление</code></pre><h3>Коды ответов</h3><ul><li><strong>200 OK</strong> — успешный запрос</li><li><strong>201 Created</strong> — ресурс создан</li><li><strong>204 No Content</strong> — успешно, без тела</li><li><strong>400 Bad Request</strong> — ошибка клиента</li><li><strong>401 Unauthorized</strong> — не авторизован</li><li><strong>403 Forbidden</strong> — нет доступа</li><li><strong>404 Not Found</strong> — не найдено</li><li><strong>500 Internal Server Error</strong> — ошибка сервера</li></ul><h3>Пример CRUD API</h3><pre><code>const express = require(\'express\');\nconst app = express();\napp.use(express.json());\n\nlet users = [\n  { id: 1, name: "Алексей", email: "alex@example.com" }\n];\n\napp.get(\'/api/users\', (req, res) => res.json(users));\napp.post(\'/api/users\', (req, res) => {\n  const user = { id: users.length + 1, ...req.body };\n  users.push(user);\n  res.status(201).json(user);\n});\napp.get(\'/api/users/:id\', (req, res) => {\n  const user = users.find(u => u.id === +req.params.id);\n  if (!user) return res.status(404).json({ error: \'Не найдено\' });\n  res.json(user);\n});</code></pre>',
            'Аутентификация' => '<h2>Аутентификация</h2><p>Аутентификация — процесс подтверждения личности пользователя. Авторизация — проверка прав доступа.</p><h3>Типы аутентификации</h3><ul><li><strong>Сессии</strong> — сервер хранит данные пользователя (cookies)</li><li><strong>JWT (JSON Web Tokens)</strong> — токен хранится на клиенте</li><li><strong>OAuth 2.0</strong> — аутентификация через сторонние сервисы (Google, GitHub)</li></ul><h3>JWT</h3><p>Структура JWT: Header.Payload.Signature</p><pre><code>const jwt = require(\'jsonwebtoken\');\n\n// Генерация токена\nconst token = jwt.sign(\n  { userId: 1, role: \'admin\' },\n  process.env.JWT_SECRET,\n  { expiresIn: \'24h\' }\n);\n\n// Верификация токена\nconst decoded = jwt.verify(token, process.env.JWT_SECRET);</code></pre><h3>Хеширование паролей</h3><pre><code>const bcrypt = require(\'bcryptjs\');\n\n// Хеширование\nconst hash = await bcrypt.hash(\'password123\', 10);\n\n// Сравнение\nconst isMatch = await bcrypt.compare(\'password123\', hash);</code></pre><h3>Middleware авторизации</h3><pre><code>function authMiddleware(req, res, next) {\n  const token = req.headers.authorization?.split(\' \')[1];\n  if (!token) return res.status(401).json({ error: \'Нет токена\' });\n  try {\n    const decoded = jwt.verify(token, process.env.JWT_SECRET);\n    req.user = decoded;\n    next();\n  } catch (err) {\n    res.status(401).json({ error: \'Неверный токен\' });\n  }\n}\n\napp.get(\'/api/profile\', authMiddleware, getProfile);</code></pre><h3>Безопасность</h3><ul><li>Используйте HTTPS</li><li>Не храните пароли в открытом виде</li><li>Используйте bcrypt/argon2 для хеширования</li><li>Настройте CORS</li><li>Валидируйте все входные данные</li></ul>',
            'Тест по Node.js' => '<h2>Тест по Node.js</h2><p>Проверьте свои знания по Node.js, Express.js, REST API и аутентификации.</p>'
        ],
        'quizzes' => [
            'Основы Node.js' => [
                ['q' => 'Что такое Node.js?', 'o' => ['Фреймворк', 'Среда выполнения JavaScript на стороне сервера', 'База данных', 'Операционная система'], 'c' => 1, 'e' => 'Node.js — среда выполнения JavaScript, построенная на движке V8 (тот же что в Chrome).'],
                ['q' => 'Какой модульный стандарт использует Node.js по умолчанию?', 'o' => ['ES Modules', 'CommonJS', 'AMD', 'UMD'], 'c' => 1, 'e' => 'Node.js исторически использует CommonJS (require/module.exports). ES Modules доступны через import/export.'],
                ['q' => 'Что такое event loop в Node.js?', 'o' => ['Цикл для обработки событий, обеспечивающий неблокирующий I/O', 'Функция для циклических операций', 'Тип цикла в for', 'Алгоритм сортировки'], 'c' => 0, 'e' => 'Event loop — ключевой механизм Node.js, обрабатывающий асинхронные операции без блокировки основного потока.'],
                ['q' => 'Как установить пакет как dev-зависимость?', 'o' => ['npm install nodemon', 'npm install --save-dev nodemon', 'npm install -D nodemon', 'Оба варианта верны'], 'c' => 3, 'e' => 'Флаги --save-dev и -D делают пакет dev-зависимостью (не будет в production).'],
                ['q' => 'Что делает команда npm start?', 'o' => ['Устанавливает пакеты', 'Запускает скрипт "start" из package.json', 'Обновляет Node.js', 'Создаёт проект'], 'c' => 1, 'e' => 'npm start выполняет команду из scripts.start в package.json.']
            ],
            'Express.js' => [
                ['q' => 'Как создать простейший Express-сервер?', 'o' => ['new Server()', 'express()', 'http.createServer()', 'app.listen()'], 'c' => 1, 'e' => 'const app = express(); app.listen(3000); — создаёт сервер на порту 3000.'],
                ['q' => 'Что такое middleware в Express?', 'o' => ['Функция, обрабатывающая запрос/ответ и вызывающая next()', 'Тип маршрута', 'Порт сервера', 'База данных'], 'c' => 0, 'e' => 'Middleware — функция (req, res, next), которая имеет доступ к запросу/ответу и может модифицировать их.'],
                ['q' => 'Как получить JSON из тела POST-запроса?', 'o' => ['req.body', 'req.json()', 'req.data', 'req.params'], 'c' => 0, 'e' => 'После app.use(express.json()) тело запроса доступно в req.body как объект.'],
                ['q' => 'Как передать параметр маршрута (например /users/123)?', 'o' => ['req.query.id', 'req.params.id', 'req.body.id', 'req.url.id'], 'c' => 1, 'e' => 'Параметры маршрута (/:id) доступны в req.params. Query-параметры (?id=123) — в req.query.'],
                ['q' => 'Для чего используется express.static()?', 'o' => ['Для раздачи статических файлов (CSS, JS, изображения)', 'Для создания API', 'Для работы с БД', 'Для аутентификации'], 'c' => 0, 'e' => 'express.static(\'public\') раздаёт файлы из папки public без дополнительных маршрутов.']
            ],
            'REST API' => [
                ['q' => 'Какой HTTP-метод используется для создания ресурса?', 'o' => ['GET', 'POST', 'PUT', 'DELETE'], 'c' => 1, 'e' => 'POST используется для создания нового ресурса. GET — чтение, PUT — обновление, DELETE — удаление.'],
                ['q' => 'Какой код ответа означает "ресурс создан"?', 'o' => ['200', '201', '204', '301'], 'c' => 1, 'e' => '201 Created — стандартный ответ при успешном создании ресурса через POST.'],
                ['q' => 'Что такое "без состояния" (stateless) в REST?', 'o' => ['Сервер не хранит данные', 'Каждый запрос содержит всю информацию для его обработки', 'Нет базы данных', 'Нет сессий'], 'c' => 1, 'e' => 'Stateless означает, что сервер не хранит состояние между запросами. Каждый запрос независим.'],
                ['q' => 'Какой метод безопаснее для удаления: PUT или DELETE?', 'o' => ['PUT', 'DELETE', 'Оба одинаковы', 'Ни один'], 'c' => 1, 'e' => 'DELETE — семантически правильный метод для удаления ресурса.'],
                ['q' => 'Что такое HATEOAS?', 'o' => ['Тип базы данных', 'Расширение REST, где ответы содержат ссылки на связанные ресурсы', 'Фреймворк', 'Протокол'], 'c' => 1, 'e' => 'HATEOAS — уровень REST API, где каждый ответ содержит ссылки на доступные действия.']
            ],
            'Аутентификация' => [
                ['q' => 'Что такое JWT?', 'o' => ['Java Web Token', 'JSON Web Token', 'JavaScript Web Token', 'JSON Wide Token'], 'c' => 1, 'e' => 'JWT (JSON Web Token) — стандарт для создания токенов доступа, состоящий из Header.Payload.Signature.'],
                ['q' => 'Какой алгоритм безопаснее для хеширования паролей?', 'o' => ['MD5', 'SHA-1', 'bcrypt', 'Base64'], 'c' => 2, 'e' => 'bcrypt специально разработан для хеширования паролей с поддержкой соли и адаптивной сложностью.'],
                ['q' => 'Где должен храниться JWT на клиенте?', 'o' => ['В localStorage (небезопасно)', 'В httpOnly cookie (безопаснее)', 'В sessionStorage', 'В переменной'], 'c' => 1, 'e' => 'httpOnly cookie safest для JWT — недоступен из JavaScript, защищён от XSS.'],
                ['q' => 'Для чего нужен CORS?', 'o' => ['Кеширование запросов', 'Разрешение кросс-доменных запросов из браузера', 'Сжатие данных', 'Логирование'], 'c' => 1, 'e' => 'CORS (Cross-Origin Resource Sharing) — механизм безопасности, разрешающий запросы с других доменов.'],
                ['q' => 'Какой заголовок содержит JWT токен?', 'o' => ['Cookie: token=...', 'Authorization: Bearer token...', 'X-Token: token...', 'Auth: token...'], 'c' => 1, 'e' => 'Стандартный формат: Authorization: Bearer <jwt-token>.']
            ],
            'Тест по Node.js' => [
                ['q' => 'Какой метод Express вызывается при ошибке (4 аргумента)?', 'o' => ['app.use(handler)', 'app.use((err, req, res, next) => {})', 'app.error()', 'app.on("error")'], 'c' => 1, 'e' => 'Обработчик ошибок в Express: app.use((err, req, res, next) => {}) — 4 аргумента.'],
                ['q' => 'Что такое RESTful API?', 'o' => ['API, работающий только с JSON', 'API, следующий принципам REST', 'API с аутентификацией', 'API для мобильных приложений'], 'c' => 1, 'e' => 'RESTful API — API, следующее архитектурным принципам REST.'],
                ['q' => 'Как защитить Express-сервер от атак?', 'o' => ['helmet, cors, rate-limiting, валидация', 'Только HTTPS', 'Без пароля', 'Без API'], 'c' => 0, 'e' => 'Комплексная защита: helmet, cors, rate-limiting, валидация входных данных.'],
                ['q' => 'Для чего используется async/await в Node.js?', 'o' => ['Для ускорения кода', 'Для красивого написания асинхронного кода (Promise-based)', 'Для работы с БД', 'Для тестирования'], 'c' => 1, 'e' => 'async/await делает асинхронный код более читаемым и удобным.'],
                ['q' => 'Какой статус-код вернёт сервер при отсутствии JWT в запросе?', 'o' => ['200', '400', '401', '403'], 'c' => 2, 'e' => '401 Unauthorized — клиент не предоставил аутентификационные данные.']
            ]
        ],
        'practice' => [
            'Основы Node.js' => [
                ['lang' => 'javascript', 'title' => 'Создание сервера', 'prompt' => 'Создайте простой HTTP-сервер на Node.js без фреймворков.', 'out' => '', 'start' => $startNode1, 'tests' => [['contains', 'require('], ['contains', 'createServer'], ['contains', 'listen']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'javascript', 'title' => 'Модульная система', 'prompt' => 'Создайте модуль math.js с функциями сложения и умножения и импортируйте его.', 'out' => '', 'start' => '', 'tests' => [['contains', 'module.exports'], ['contains', 'require('], ['contains', 'exports.']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Асинхронные операции', 'prompt' => 'Прочитайте файл и выведите его содержимое, используя async/await.', 'out' => '', 'start' => '', 'tests' => [['contains', 'async'], ['contains', 'await'], ['contains', 'readFile']], 'diff' => 'medium', 'time' => 20]
            ],
            'Express.js' => [
                ['lang' => 'javascript', 'title' => 'Базовый Express-сервер', 'prompt' => 'Настройте Express-сервер с парсингом JSON и статическими файлами.', 'out' => '', 'start' => $startNode2, 'tests' => [['contains', 'express()'], ['contains', 'json()'], ['contains', 'static(']], 'diff' => 'easy', 'time' => 15],
                ['lang' => 'javascript', 'title' => 'CRUD маршруты', 'prompt' => 'Создайте CRUD API для пользователей (GET, POST, PUT, DELETE).', 'out' => '', 'start' => '', 'tests' => [['contains', 'app.get('], ['contains', 'app.post('], ['contains', 'app.put('], ['contains', 'app.delete(']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Роутер Express', 'prompt' => 'Вынесите маршруты в отдельный роутер с префиксом /api/users.', 'out' => '', 'start' => '', 'tests' => [['contains', 'Router()'], ['contains', 'router.get('], ['contains', 'app.use(']], 'diff' => 'medium', 'time' => 20]
            ],
            'REST API' => [
                ['lang' => 'javascript', 'title' => 'REST API для задач', 'prompt' => 'Создайте REST API для управления списком задач (Task) с CRUD операциями.', 'out' => '', 'start' => '', 'tests' => [['contains', 'GET'], ['contains', 'POST'], ['contains', 'PUT'], ['contains', 'DELETE'], ['contains', '/api/tasks']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Валидация входных данных', 'prompt' => 'Добавьте валидацию входных данных с помощью express-validator.', 'out' => '', 'start' => '', 'tests' => [['contains', 'body('], ['contains', 'validationResult'], ['contains', 'isValid()']], 'diff' => 'hard', 'time' => 25],
                ['lang' => 'javascript', 'title' => 'Обработка ошибок', 'prompt' => 'Создайте централизованный обработчик ошибок для Express API.', 'out' => '', 'start' => '', 'tests' => [['contains', 'err, req, res, next'], ['contains', 'status('], ['contains', 'json(']], 'diff' => 'hard', 'time' => 25]
            ],
            'Аутентификация' => [
                ['lang' => 'javascript', 'title' => 'Генерация JWT токена', 'prompt' => 'Создайте функцию для генерации JWT токена при авторизации.', 'out' => '', 'start' => $startNodeAuth, 'tests' => [['contains', 'jwt.sign('], ['contains', 'expiresIn'], ['contains', 'JWT_SECRET']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Хеширование паролей', 'prompt' => 'Реализуйте регистрацию с хешированием пароля через bcrypt.', 'out' => '', 'start' => $startNodeAuth, 'tests' => [['contains', 'bcrypt.hash('], ['contains', 'bcrypt.compare('], ['contains', 'saltRounds']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Middleware авторизации', 'prompt' => 'Создайте middleware для проверки JWT токена в заголовке запроса.', 'out' => '', 'start' => $startNodeAuth, 'tests' => [['contains', 'authorization'], ['contains', 'split('], ['contains', 'jwt.verify('], ['contains', 'next()']], 'diff' => 'hard', 'time' => 25]
            ],
            'Тест по Node.js' => [
                ['lang' => 'javascript', 'title' => 'Rate Limiting', 'prompt' => 'Добавьте ограничение количества запросов (rate limiting) к API.', 'out' => '', 'start' => '', 'tests' => [['contains', 'rateLimit'], ['contains', 'windowMs'], ['contains', 'max']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Логирование запросов', 'prompt' => 'Настройте логирование всех HTTP-запросов с временем响应а.', 'out' => '', 'start' => '', 'tests' => [['contains', 'morgan'], ['contains', 'app.use('], ['contains', 'dev']], 'diff' => 'medium', 'time' => 20],
                ['lang' => 'javascript', 'title' => 'Graceful Shutdown', 'prompt' => 'Реализуйте корректное завершение работы сервера при получении SIGTERM.', 'out' => '', 'start' => '', 'tests' => [['contains', 'process.on('], ['contains', 'SIGTERM'], ['contains', 'server.close(']], 'diff' => 'hard', 'time' => 25]
            ]
        ]
    ],
];
