import os

path = r'C:\OSPanel\home\Codemaster\database\seeders\part4.php'

def q(s):
    """Escape single quotes for PHP single-quoted strings"""
    return s.replace("\\", "\\\\").replace("'", "\\'")

lines = []
lines.append('<?php')
lines.append('')

# Variable definitions (double-quoted PHP strings for content with single quotes)
lines.append('$startTs1 = "interface User {\\n  name: string;\\n  age: number;\\n  email?: string;\\n}\\n\\nconst users: User[] = [\\n  { name: \'Alice\', age: 25 },\\n  { name: \'Bob\', age: 30 }\\n];\\n\\nfunction findUser(name: string): User | undefined {\\n  return users.find(u => u.name === name);\\n}";')
lines.append('')
lines.append('$startTs2 = "type StringOrNumber = string | number;\\n\\nfunction process(value: StringOrNumber): string {\\n  if (typeof value === \'string\') {\\n    return value.toUpperCase();\\n  }\\n  return String(value);\\n}";')
lines.append('')
lines.append('$startTs3 = "function merge<T extends object, U extends object>(a: T, b: U): T & U {\\n  return { ...a, ...b };\\n}\\n\\nconst result = merge({ name: \'Alice\' }, { age: 25 });";')
lines.append('')
lines.append('$startTs4 = "type UserRole = \'admin\' | \'user\' | \'moderator\';\\n\\ninterface User {\\n  name: string;\\n  role: UserRole;\\n  permissions: string[];\\n}\\n\\nfunction hasPermission(user: User, perm: string): boolean {\\n  return user.permissions.includes(perm);\\n}";')
lines.append('')
lines.append('$startTsDecorator = "function Log(target: any, key: string, descriptor: PropertyDescriptor) {\\n  const original = descriptor.value;\\n  descriptor.value = function(...args: any[]) {\\n    console.log(\'Calling \' + key + \' with\', args);\\n    return original.apply(this, args);\\n  };\\n  return descriptor;\\n}\\n\\nclass Calculator {\\n  @Log\\n  add(a: number, b: number) {\\n    return a + b;\\n  }\\n}";')
lines.append('')
lines.append("$startDockerCmds = 'docker pull nginx:latest\\ndocker run -d --name web -p 8080:80 nginx:latest\\ndocker ps\\ndocker logs web';")
lines.append('')
lines.append("$startDockerfile16 = 'FROM node:18-alpine")
lines.append('WORKDIR /app')
lines.append('COPY package*.json ./')
lines.append('RUN npm ci --production')
lines.append('COPY . .')
lines.append('EXPOSE 3000')
lines.append('CMD ["node", "server.js"]';')
lines.append('')
lines.append('$startCompose16 = "version: \'3.8\'\\nservices:\\n  web:\\n    build: .\\n    ports:\\n      - \'3000:3000\'\\n  db:\\n    image: postgres:15\\n    environment:\\n      POSTGRES_PASSWORD: secret";')
lines.append('')
lines.append("$startK8sPod = 'apiVersion: v1")
lines.append('kind: Pod')
lines.append('metadata:')
lines.append('  name: my-pod')
lines.append('spec:')
lines.append('  containers:')
lines.append('  - name: app')
lines.append('    image: nginx:latest')
lines.append('    ports:')
lines.append('    - containerPort: 80';')
lines.append('')
lines.append("$startK8sDeploy = 'apiVersion: apps/v1")
lines.append('kind: Deployment')
lines.append('metadata:')
lines.append('  name: my-deployment')
lines.append('spec:')
lines.append('  replicas: 3')
lines.append('  selector:')
lines.append('    matchLabels:')
lines.append('      app: my-app')
lines.append('  template:')
lines.append('    metadata:')
lines.append('      labels:')
lines.append('        app: my-app')
lines.append('    spec:')
lines.append('      containers:')
lines.append('      - name: app')
lines.append('        image: nginx:latest';')
lines.append('')
lines.append("$startK8sService = 'apiVersion: v1")
lines.append('kind: Service')
lines.append('metadata:')
lines.append('  name: my-service')
lines.append('spec:')
lines.append('  selector:')
lines.append('    app: my-app')
lines.append('  ports:')
lines.append('  - port: 80')
lines.append('    targetPort: 8080')
lines.append('  type: LoadBalancer';')
lines.append('')
lines.append("$startK8sConfig = 'apiVersion: v1")
lines.append('kind: ConfigMap')
lines.append('metadata:')
lines.append('  name: app-config')
lines.append('data:')
lines.append('  DATABASE_URL: "postgres://db:5432/mydb"')
lines.append('  API_KEY: "my-secret-key";')
lines.append('')
lines.append('$startMobile2 = "import React from \'react\';\\nimport { View, Text, StyleSheet } from \'react-native\';\\n\\nconst App = () => {\\n  return (\\n    <View style={styles.container}>\\n      <Text style={styles.title}>Hello World</Text>\\n    </View>\\n  );\\n};\\n\\nconst styles = StyleSheet.create({\\n  container: { flex: 1, justifyContent: \'center\', alignItems: \'center\' },\\n  title: { fontSize: 24, fontWeight: \'bold\' }\\n});";')
lines.append('')
lines.append('$startMobileNav = "import { NavigationContainer } from \'@react-navigation/native\';\\nimport { createStackNavigator } from \'@react-navigation/stack\';\\n\\nconst Stack = createStackNavigator();\\n\\nfunction App() {\\n  return (\\n    <NavigationContainer>\\n      <Stack.Navigator>\\n        <Stack.Screen name=\'Home\' component={HomeScreen} />\\n        <Stack.Screen name=\'Details\' component={DetailsScreen} />\\n      </Stack.Navigator>\\n    </NavigationContainer>\\n  );\\n}";')
lines.append('')
lines.append('$startMobileApi = "const fetchUsers = async () => {\\n  try {\\n    const response = await fetch(\'https://api.example.com/users\');\\n    const data = await response.json();\\n    return data;\\n  } catch (error) {\\n    console.error(\'Error:\', error);\\n  }\\n};";')
lines.append('')

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print("Phase 1: Variables written")
