<?php

return [
    'two-sum' => [
        ['input' => '[2,7,11,15]\n9', 'expected' => '[0,1]', 'description' => 'Basic case'],
        ['input' => '[3,2,4]\n6', 'expected' => '[1,2]', 'description' => 'Middle elements'],
        ['input' => '[3,3]\n6', 'expected' => '[0,1]', 'description' => 'Duplicate values'],
        ['input' => '[1,5,8,3,9,2]\n11', 'expected' => '[1,3]', 'description' => 'Six elements'],
        ['input' => '[-1,-2,-3,-4,-5]\n-8', 'expected' => '[2,4]', 'description' => 'All negatives'],
        ['input' => '[0,4,3,0]\n0', 'expected' => '[0,3]', 'description' => 'Zero sum with zeros'],
        ['input' => '[1,2,3,4,5,6,7,8,9,10]\n19', 'expected' => '[8,9]', 'description' => 'Large array'],
        ['input' => '[-3,4,3,90]\n0', 'expected' => '[0,2]', 'description' => 'Mixed neg pos'],
        ['input' => '[5,75,25]\n100', 'expected' => '[1,2]', 'description' => 'Non-adjacent sum'],
        ['input' => '[1,2,3,4,5,6,7,8,9,10,11,12]\n24', 'expected' => '[10,11]', 'description' => 'Twelve elements'],
    ],
    'maximum-subarray' => [
        ['input' => '[-2,1,-3,4,-1,2,1,-5,4]', 'expected' => '6', 'description' => 'Mixed values'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[5,4,-1,7,8]', 'expected' => '23', 'description' => 'Mostly positive'],
        ['input' => '[-1]', 'expected' => '-1', 'description' => 'Single negative'],
        ['input' => '[-2,-1]', 'expected' => '-1', 'description' => 'All negative'],
        ['input' => '[0,0,0,0,0]', 'expected' => '0', 'description' => 'All zeros'],
        ['input' => '[-5,4,-1,7,8,-3]', 'expected' => '18', 'description' => 'Multiple subarrays'],
        ['input' => '[1,-1,1,-1,1,-1,1]', 'expected' => '1', 'description' => 'Alternating'],
    ],
    'best-time-to-buy-and-sell-stock' => [
        ['input' => '[7,1,5,3,6,4]', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '[7,6,4,3,1]', 'expected' => '0', 'description' => 'Always decreasing'],
        ['input' => '[1,2]', 'expected' => '1', 'description' => 'Two days profit'],
        ['input' => '[2,4,1]', 'expected' => '2', 'description' => 'Small profit'],
        ['input' => '[3,3,3,3,3]', 'expected' => '0', 'description' => 'All same'],
        ['input' => '[1,2,3,4,5]', 'expected' => '4', 'description' => 'Linear increase'],
        ['input' => '[5,4,3,2,1]', 'expected' => '0', 'description' => 'Linear decrease'],
        ['input' => '[1,2,4,2,5,7,2,4,9,0]', 'expected' => '8', 'description' => 'Multiple peaks'],
    ],
    'product-of-array-except-self' => [
        ['input' => '[1,2,3,4]', 'expected' => '[24,12,8,6]', 'description' => 'Basic case'],
        ['input' => '[-1,1,0,-3,3]', 'expected' => '[0,0,9,0,0]', 'description' => 'With zero'],
        ['input' => '[2,3]', 'expected' => '[3,2]', 'description' => 'Two elements'],
        ['input' => '[1,1]', 'expected' => '[1,1]', 'description' => 'Two ones'],
        ['input' => '[0,0]', 'expected' => '[0,0]', 'description' => 'Two zeros'],
        ['input' => '[-1,-2,-3,-4]', 'expected' => '[-24,-12,-8,-6]', 'description' => 'All negative'],
    ],
    '3sum' => [
        ['input' => '[-1,0,1,2,-1,-4]', 'expected' => '[[-1,-1,2],[-1,0,1]]', 'description' => 'Basic case'],
        ['input' => '[0,1,1]', 'expected' => '[]', 'description' => 'No valid triplet'],
        ['input' => '[0,0,0]', 'expected' => '[[0,0,0]]', 'description' => 'All zeros'],
        ['input' => '[-2,0,1,1,2]', 'expected' => '[[-2,0,2],[-2,1,1]]', 'description' => 'Multiple solutions'],
        ['input' => '[-1,0,1,2,-1,-4,-2,-2,8,8]', 'expected' => '[[-1,-1,2],[-1,0,1],[-2,0,2]]', 'description' => 'With duplicates'],
    ],
    'container-with-most-water' => [
        ['input' => '[1,8,6,2,5,4,8,3,7]', 'expected' => '49', 'description' => 'Basic case'],
        ['input' => '[1,1]', 'expected' => '1', 'description' => 'Two elements'],
        ['input' => '[4,3,2,1,4]', 'expected' => '16', 'description' => 'Symmetric'],
        ['input' => '[1,2,1]', 'expected' => '2', 'description' => 'Three elements'],
        ['input' => '[1,2,4,3]', 'expected' => '4', 'description' => 'Four elements'],
    ],
    'contains-duplicate' => [
        ['input' => '[1,2,3,1]', 'expected' => 'true', 'description' => 'Has duplicate'],
        ['input' => '[1,2,3,4]', 'expected' => 'false', 'description' => 'No duplicate'],
        ['input' => '[1,1,1,3,3,4,3,2,4,2]', 'expected' => 'true', 'description' => 'Multiple duplicates'],
        ['input' => '[1]', 'expected' => 'false', 'description' => 'Single element'],
        ['input' => '[1,2]', 'expected' => 'false', 'description' => 'Two unique'],
        ['input' => '[1,1]', 'expected' => 'true', 'description' => 'Two same'],
        ['input' => '[]', 'expected' => 'false', 'description' => 'Empty array'],
    ],
    'sort-colors' => [
        ['input' => '[2,0,2,1,1,0]', 'expected' => '[0,0,1,1,2,2]', 'description' => 'Basic case'],
        ['input' => '[2,0,1]', 'expected' => '[0,1,2]', 'description' => 'Three elements'],
        ['input' => '[0]', 'expected' => '[0]', 'description' => 'Single element'],
        ['input' => '[1,1,1]', 'expected' => '[1,1,1]', 'description' => 'All same'],
        ['input' => '[2,2,2,0,0,1,1]', 'expected' => '[0,0,1,1,2,2,2]', 'description' => 'More whites'],
    ],
    'merge-intervals' => [
        ['input' => '[[1,3],[2,6],[8,10],[15,18]]', 'expected' => '[[1,6],[8,10],[15,18]]', 'description' => 'Basic merging'],
        ['input' => '[[1,4],[4,5]]', 'expected' => '[[1,5]]', 'description' => 'Adjacent intervals'],
        ['input' => '[[1,4],[0,4]]', 'expected' => '[[0,4]]', 'description' => 'Overlapping'],
        ['input' => '[[1,4],[2,3]]', 'expected' => '[[1,4]]', 'description' => 'One inside another'],
        ['input' => '[[1,4]]', 'expected' => '[[1,4]]', 'description' => 'Single interval'],
    ],
    'subsets' => [
        ['input' => '[1,2,3]', 'expected' => '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]', 'description' => 'Three elements'],
        ['input' => '[0]', 'expected' => '[[],[0]]', 'description' => 'Single element'],
        ['input' => '[1,2]', 'expected' => '[[],[1],[2],[1,2]]', 'description' => 'Two elements'],
    ],
    'jump-game' => [
        ['input' => '[2,3,1,1,4]', 'expected' => 'true', 'description' => 'Can reach end'],
        ['input' => '[3,2,1,0,4]', 'expected' => 'false', 'description' => 'Cannot reach end'],
        ['input' => '[0]', 'expected' => 'true', 'description' => 'Already at end'],
        ['input' => '[1,0]', 'expected' => 'true', 'description' => 'One jump'],
        ['input' => '[1,1,1,1]', 'expected' => 'true', 'description' => 'All ones'],
    ],
    'rotate-image' => [
        ['input' => '[[1,2,3],[4,5,6],[7,8,9]]', 'expected' => '[[7,4,1],[8,5,2],[9,6,3]]', 'description' => '3x3 matrix'],
        ['input' => '[[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]', 'expected' => '[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]', 'description' => '4x4 matrix'],
        ['input' => '[[1]]', 'expected' => '[[1]]', 'description' => '1x1 matrix'],
        ['input' => '[[1,2],[3,4]]', 'expected' => '[[3,1],[4,2]]', 'description' => '2x2 matrix'],
    ],
    'spiral-matrix' => [
        ['input' => '[[1,2,3],[4,5,6],[7,8,9]]', 'expected' => '[1,2,3,6,9,8,7,4,5]', 'description' => '3x3 matrix'],
        ['input' => '[[1,2,3,4],[5,6,7,8],[9,10,11,12]]', 'expected' => '[1,2,3,4,8,12,11,10,9,5,6,7]', 'description' => '3x4 matrix'],
        ['input' => '[[1]]', 'expected' => '[1]', 'description' => '1x1 matrix'],
        ['input' => '[[1,2],[3,4]]', 'expected' => '[1,2,4,3]', 'description' => '2x2 matrix'],
    ],
    'search-in-rotated-sorted-array' => [
        ['input' => '[4,5,6,7,0,1,2]\n0', 'expected' => '4', 'description' => 'Found'],
        ['input' => '[4,5,6,7,0,1,2]\n3', 'expected' => '-1', 'description' => 'Not found'],
        ['input' => '[1]\n0', 'expected' => '-1', 'description' => 'Single element not found'],
        ['input' => '[1]\n1', 'expected' => '0', 'description' => 'Single element found'],
        ['input' => '[3,1]\n1', 'expected' => '1', 'description' => 'Rotated two elements'],
        ['input' => '[5,1,3]\n3', 'expected' => '2', 'description' => 'Three elements rotated'],
    ],
    'search-a-2d-matrix' => [
        ['input' => 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]]\ntarget = 3', 'expected' => 'true', 'description' => 'Found'],
        ['input' => 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]]\ntarget = 13', 'expected' => 'false', 'description' => 'Not found'],
        ['input' => 'matrix = [[1]]\ntarget = 1', 'expected' => 'true', 'description' => 'Single element found'],
        ['input' => 'matrix = [[1]]\ntarget = 0', 'expected' => 'false', 'description' => 'Single element not found'],
        ['input' => 'matrix = [[1,2,3,4,5]]\ntarget = 5', 'expected' => 'true', 'description' => 'Single row last element'],
    ],
    'find-peak-element' => [
        ['input' => '[1,2,3,1]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[1,2,1,3,5,6,4]', 'expected' => '5', 'description' => 'Multiple peaks'],
        ['input' => '[1]', 'expected' => '0', 'description' => 'Single element'],
        ['input' => '[1,2]', 'expected' => '1', 'description' => 'Two elements increasing'],
        ['input' => '[2,1]', 'expected' => '0', 'description' => 'Two elements decreasing'],
    ],
    'kth-largest-element-in-an-array' => [
        ['input' => '[3,2,1,5,6,4]\nk = 2', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '[3,2,3,1,2,4,5,5,6]\nk = 4', 'expected' => '4', 'description' => 'With duplicates'],
        ['input' => '[1]\nk = 1', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1,2,3,4,5]\nk = 3', 'expected' => '3', 'description' => 'Middle k'],
        ['input' => '[5,4,3,2,1]\nk = 1', 'expected' => '5', 'description' => 'First in reverse sorted'],
    ],
    'top-k-frequent-elements' => [
        ['input' => '[1,1,1,2,2,3]\nk = 2', 'expected' => '[1,2]', 'description' => 'Basic case'],
        ['input' => '[1]\nk = 1', 'expected' => '[1]', 'description' => 'Single element'],
        ['input' => '[4,1,-1,2,-1,2,3]\nk = 2', 'expected' => '[-1,2]', 'description' => 'With negatives'],
        ['input' => '[1,2,3,4,5]\nk = 3', 'expected' => '[1,2,3]', 'description' => 'All unique'],
    ],
    'partition-equal-subset-sum' => [
        ['input' => '[1,5,11,5]', 'expected' => 'true', 'description' => 'Basic case'],
        ['input' => '[1,2,3,5]', 'expected' => 'false', 'description' => 'Not partitionable'],
        ['input' => '[1,1]', 'expected' => 'true', 'description' => 'Two equal elements'],
        ['input' => '[1]', 'expected' => 'false', 'description' => 'Single element'],
        ['input' => '[10,10]', 'expected' => 'true', 'description' => 'Two equal halves'],
    ],
    'longest-consecutive-sequence' => [
        ['input' => '[100,4,200,1,3,2]', 'expected' => '4', 'description' => 'Basic case'],
        ['input' => '[0,3,7,2,5,8,4,6,0,1]', 'expected' => '9', 'description' => 'Long sequence'],
        ['input' => '[]', 'expected' => '0', 'description' => 'Empty array'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[9,1,4,7,3,-1,0,5,8,-1,6]', 'expected' => '7', 'description' => 'With negatives'],
    ],
    'missing-number' => [
        ['input' => '[3,0,1]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[0,1]', 'expected' => '2', 'description' => 'Missing last'],
        ['input' => '[9,6,4,2,3,5,7,0,1]', 'expected' => '8', 'description' => 'Missing 8'],
        ['input' => '[0]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1]', 'expected' => '0', 'description' => 'Missing zero'],
    ],
    'majority-element' => [
        ['input' => '[3,2,3]', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '[2,2,1,1,1,2,2]', 'expected' => '2', 'description' => 'Majority exists'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1,1,1,2,2,2,2]', 'expected' => '2', 'description' => 'Two majority candidates'],
        ['input' => '[6,5,5]', 'expected' => '5', 'description' => 'Simple majority'],
    ],
    'move-zeroes' => [
        ['input' => '[0,1,0,3,12]', 'expected' => '[1,3,12,0,0]', 'description' => 'Basic case'],
        ['input' => '[0]', 'expected' => '[0]', 'description' => 'Single zero'],
        ['input' => '[1,0,1]', 'expected' => '[1,1,0]', 'description' => 'One zero in middle'],
        ['input' => '[0,0,1]', 'expected' => '[1,0,0]', 'description' => 'Leading zeros'],
        ['input' => '[1,2,3]', 'expected' => '[1,2,3]', 'description' => 'No zeros'],
    ],
    'remove-duplicates-from-sorted-array' => [
        ['input' => '[1,1,2]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[0,0,1,1,1,2,3,3]', 'expected' => '4', 'description' => 'Multiple duplicates'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1,2,3]', 'expected' => '3', 'description' => 'No duplicates'],
        ['input' => '[1,1]', 'expected' => '1', 'description' => 'Two same'],
    ],
    'plus-one' => [
        ['input' => '[1,2,3]', 'expected' => '[1,2,4]', 'description' => 'Basic case'],
        ['input' => '[4,3,2,1]', 'expected' => '[4,3,2,2]', 'description' => 'No carry'],
        ['input' => '[9]', 'expected' => '[1,0]', 'description' => 'Single digit carry'],
        ['input' => '[9,9,9]', 'expected' => '[1,0,0,0]', 'description' => 'Full carry cascade'],
        ['input' => '[1,9,9]', 'expected' => '[2,0,0]', 'description' => 'Partial carry'],
    ],
    'single-number' => [
        ['input' => '[2,2,1]', 'expected' => '1', 'description' => 'Basic case'],
        ['input' => '[4,1,2,1,2]', 'expected' => '4', 'description' => 'Larger array'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1,1,2,2,3]', 'expected' => '3', 'description' => 'Odd element at end'],
        ['input' => '[5,3,5,3,7]', 'expected' => '7', 'description' => 'Odd element in middle'],
    ],
    'intersection-of-two-arrays' => [
        ['input' => '[1,2,2,1]\n[2,2]', 'expected' => '[2]', 'description' => 'Basic case'],
        ['input' => '[4,9,5]\n[9,4,9,8,4]', 'expected' => '[4,9]', 'description' => 'Multiple intersection'],
        ['input' => '[1]\n[2]', 'expected' => '[]', 'description' => 'No intersection'],
        ['input' => '[]\n[1]', 'expected' => '[]', 'description' => 'Empty first'],
        ['input' => '[1]\n[]', 'expected' => '[]', 'description' => 'Empty second'],
    ],
    'two-sum-ii-input-array-is-sorted' => [
        ['input' => '[2,7,11,15]\n9', 'expected' => '[1,2]', 'description' => 'Basic case'],
        ['input' => '[2,3,4]\n6', 'expected' => '[1,3]', 'description' => 'First and last'],
        ['input' => '[-1,0]\n-1', 'expected' => '[1,2]', 'description' => 'Negative target'],
        ['input' => '[1,2,3,4,4,9,56,90]\n8', 'expected' => '[4,5]', 'description' => 'Duplicate values'],
        ['input' => '[5,25,75]\n100', 'expected' => '[2,3]', 'description' => 'Large gap'],
    ],
    'gas-station' => [
        ['input' => '[1,2,3,4,5]\n[3,4,5,1,2]', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '[2,3,4]\n[3,4,3]', 'expected' => '-1', 'description' => 'Impossible'],
        ['input' => '[5]\n[4]', 'expected' => '0', 'description' => 'Single station'],
        ['input' => '[1,2,3,4,5]\n[2,3,4,5,1]', 'expected' => '0', 'description' => 'Start at 0'],
        ['input' => '[3,1,1]\n[1,2,2]', 'expected' => '0', 'description' => 'Tight margin'],
    ],
    'happy-number' => [
        ['input' => '19', 'expected' => 'true', 'description' => 'Is happy'],
        ['input' => '2', 'expected' => 'false', 'description' => 'Not happy'],
        ['input' => '1', 'expected' => 'true', 'description' => 'Trivial happy'],
        ['input' => '7', 'expected' => 'true', 'description' => 'Happy chain'],
        ['input' => '4', 'expected' => 'false', 'description' => 'Cycle chain'],
    ],
    'reverse-bits' => [
        ['input' => '00000010100101000001111010011100', 'expected' => '00111001011110000010100101000000', 'description' => 'Basic case'],
        ['input' => '11111111111111111111111111111101', 'expected' => '10111111111111111111111111111111', 'description' => 'All ones except last'],
        ['input' => '00000000000000000000000000000000', 'expected' => '00000000000000000000000000000000', 'description' => 'All zeros'],
        ['input' => '11111111111111111111111111111111', 'expected' => '11111111111111111111111111111111', 'description' => 'All ones'],
    ],
    'counting-bits' => [
        ['input' => '2', 'expected' => '[0,1,1]', 'description' => 'n=2'],
        ['input' => '5', 'expected' => '[0,1,1,2,1,2]', 'description' => 'n=5'],
        ['input' => '0', 'expected' => '[0]', 'description' => 'n=0'],
        ['input' => '1', 'expected' => '[0,1]', 'description' => 'n=1'],
        ['input' => '10', 'expected' => '[0,1,1,2,1,2,2,3,1,2,2]', 'description' => 'n=10'],
    ],
    'reverse-integer' => [
        ['input' => '123', 'expected' => '321', 'description' => 'Basic case'],
        ['input' => '-123', 'expected' => '-321', 'description' => 'Negative'],
        ['input' => '120', 'expected' => '21', 'description' => 'Trailing zero'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1534236469', 'expected' => '0', 'description' => 'Overflow returns 0'],
    ],
    'number-of-1-bits' => [
        ['input' => '11', 'expected' => '3', 'description' => 'Binary 1011'],
        ['input' => '128', 'expected' => '1', 'description' => 'Power of 2'],
        ['input' => '2147483645', 'expected' => '30', 'description' => 'Almost all ones'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1', 'expected' => '1', 'description' => 'Single one'],
    ],
    'palindrome-number' => [
        ['input' => '121', 'expected' => 'true', 'description' => 'Odd palindrome'],
        ['input' => '-121', 'expected' => 'false', 'description' => 'Negative'],
        ['input' => '10', 'expected' => 'false', 'description' => 'Ends with zero'],
        ['input' => '0', 'expected' => 'true', 'description' => 'Zero'],
        ['input' => '1234321', 'expected' => 'true', 'description' => '7-digit palindrome'],
        ['input' => '11', 'expected' => 'true', 'description' => 'Double digit'],
        ['input' => '123456789', 'expected' => 'false', 'description' => 'Non-palindrome large'],
        ['input' => '12321', 'expected' => 'true', 'description' => '5-digit palindrome'],
    ],
    'length-of-last-word' => [
        ['input' => '"Hello World"', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '"   fly me   to   the moon  "', 'expected' => '4', 'description' => 'Trailing spaces'],
        ['input' => '"luffy is still joyboy"', 'expected' => '6', 'description' => 'Last word long'],
        ['input' => '"a"', 'expected' => '1', 'description' => 'Single char'],
        ['input' => '"day"', 'expected' => '3', 'description' => 'Single word'],
    ],
    'maximum-product-subarray' => [
        ['input' => '[2,3,-2,4]', 'expected' => '6', 'description' => 'Basic case'],
        ['input' => '[-2,0,-1]', 'expected' => '0', 'description' => 'Zero in between'],
        ['input' => '[-2]', 'expected' => '-2', 'description' => 'Single negative'],
        ['input' => '[2,-5,-2,-4,3]', 'expected' => '24', 'description' => 'Two negatives product'],
        ['input' => '[-2,3,-4]', 'expected' => '24', 'description' => 'All contribute'],
    ],
    'max-area-of-island' => [
        ['input' => '[[1,1,0,0,0],[1,1,0,0,0],[0,0,1,0,0],[0,0,0,1,1]]', 'expected' => '4', 'description' => 'Two islands'],
        ['input' => '[[0,0,1,0,0],[0,1,0,1,0],[0,1,0,1,0]]', 'expected' => '3', 'description' => 'Cross-shaped island'],
        ['input' => '[[1,1],[1,1]]', 'expected' => '4', 'description' => 'Single large island'],
        ['input' => '[[0,0]]', 'expected' => '0', 'description' => 'No island'],
    ],
    'find-all-numbers-disappeared-in-an-array' => [
        ['input' => '[4,3,2,7,8,2,3,1]', 'expected' => '[5,6]', 'description' => 'Basic case'],
        ['input' => '[1,1]', 'expected' => '[2]', 'description' => 'Duplicate'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[]', 'description' => 'No missing'],
        ['input' => '[2,2]', 'expected' => '[1]', 'description' => 'Missing first'],
        ['input' => '[1,1,2,2]', 'expected' => '[3,4]', 'description' => 'Multiple missing'],
    ],
    'find-all-duplicates-in-an-array' => [
        ['input' => '[4,3,2,7,8,2,3,1]', 'expected' => '[2,3]', 'description' => 'Basic case'],
        ['input' => '[1,1,2]', 'expected' => '[1]', 'description' => 'One duplicate'],
        ['input' => '[1]', 'expected' => '[]', 'description' => 'No duplicates'],
        ['input' => '[2,2]', 'expected' => '[2]', 'description' => 'Single pair'],
        ['input' => '[3,3,3]', 'expected' => '[3]', 'description' => 'Triple same'],
    ],
    'degree-of-an-array' => [
        ['input' => '[1,2,2,3,1]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[1,2,2,3,1,4,2]', 'expected' => '6', 'description' => 'Largest subarray'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1,2]', 'expected' => '2', 'description' => 'Two different'],
        ['input' => '[3,3,3]', 'expected' => '3', 'description' => 'All same'],
    ],
    'shortest-unsorted-continuous-subarray' => [
        ['input' => '[2,6,4,8,10,9,15]', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '[1,2,3,4]', 'expected' => '0', 'description' => 'Already sorted'],
        ['input' => '[1]', 'expected' => '0', 'description' => 'Single element'],
        ['input' => '[1,3,2,0,-1]', 'expected' => '5', 'description' => 'Reverse sorted'],
        ['input' => '[1,2,3,4,5,1,2,3,4]', 'expected' => '8', 'description' => 'Long unsorted suffix'],
    ],
    'array-nesting' => [
        ['input' => '[5,4,0,3,1,6,2]', 'expected' => '4', 'description' => 'Basic case'],
        ['input' => '[0,1,2]', 'expected' => '1', 'description' => 'All self loops'],
        ['input' => '[1,0,2]', 'expected' => '3', 'description' => 'Long cycle'],
        ['input' => '[3,1,4,0,2]', 'expected' => '3', 'description' => 'Mixed cycles'],
        ['input' => '[0]', 'expected' => '1', 'description' => 'Single element'],
    ],
    'maximal-rectangle' => [
        ['input' => '[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', 'expected' => '6', 'description' => 'Basic case'],
        ['input' => '[["0"]]', 'expected' => '0', 'description' => 'All zeros'],
        ['input' => '[["1"]]', 'expected' => '1', 'description' => 'Single 1'],
        ['input' => '[["1","1"],["1","1"]]', 'expected' => '4', 'description' => 'All ones'],
    ],
    'next-permutation' => [
        ['input' => '[1,2,3]', 'expected' => '[1,3,2]', 'description' => 'Basic case'],
        ['input' => '[3,2,1]', 'expected' => '[1,2,3]', 'description' => 'Reverse sorted'],
        ['input' => '[1,1,5]', 'expected' => '[1,5,1]', 'description' => 'Duplicate elements'],
        ['input' => '[1,3,2]', 'expected' => '[2,1,3]', 'description' => 'Partial reverse'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single element'],
    ],
];
