<?php

return [
    'median-of-two-sorted-arrays' => [
        ['input' => '[1,3]\n[2]', 'expected' => '2.00000', 'description' => 'Odd total'],
        ['input' => '[1,2]\n[3,4]', 'expected' => '2.50000', 'description' => 'Even total'],
        ['input' => '[]\n[1]', 'expected' => '1.00000', 'description' => 'One empty'],
        ['input' => '[2]\n[]', 'expected' => '2.00000', 'description' => 'Other empty'],
        ['input' => '[1,2,3]\n[4,5,6]', 'expected' => '3.50000', 'description' => 'Equal sizes'],
    ],
    'basic-calculator' => [
        ['input' => '"1 + 2 * 3"', 'expected' => '7', 'description' => 'Order of operations'],
        ['input' => '" 3/2 "', 'expected' => '1', 'description' => 'Integer division'],
        ['input' => '" 3+5 / 2 "', 'expected' => '5', 'description' => 'Mixed operations'],
        ['input' => '"1+1"', 'expected' => '2', 'description' => 'Simple add'],
        ['input' => '"2-1"', 'expected' => '1', 'description' => 'Simple subtract'],
    ],
    'powx-n' => [
        ['input' => '2.00000\n10', 'expected' => '1024.00000', 'description' => 'Positive power'],
        ['input' => '2.10000\n3', 'expected' => '9.26100', 'description' => 'Decimal base'],
        ['input' => '2.00000\n-2', 'expected' => '0.25000', 'description' => 'Negative power'],
        ['input' => '0.00001\n2147483647', 'expected' => '0.00000', 'description' => 'Very small base'],
        ['input' => '1.00000\n2147483647', 'expected' => '1.00000', 'description' => 'One to any power'],
    ],
    'sqrtx' => [
        ['input' => '4', 'expected' => '2', 'description' => 'Perfect square'],
        ['input' => '8', 'expected' => '2', 'description' => 'Not perfect square'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1', 'expected' => '1', 'description' => 'One'],
        ['input' => '2147483647', 'expected' => '46340', 'description' => 'Max int'],
    ],
    'factorial-trailing-zeroes' => [
        ['input' => '3', 'expected' => '0', 'description' => 'No trailing zeros'],
        ['input' => '5', 'expected' => '1', 'description' => 'One trailing zero'],
        ['input' => '10', 'expected' => '2', 'description' => 'Two trailing zeros'],
        ['input' => '25', 'expected' => '6', 'description' => 'Six trailing zeros'],
        ['input' => '100', 'expected' => '24', 'description' => '24 trailing zeros'],
    ],
    'excel-sheet-column-title' => [
        ['input' => '1', 'expected' => '"A"', 'description' => 'Column 1'],
        ['input' => '28', 'expected' => '"AB"', 'description' => 'Column 28'],
        ['input' => '701', 'expected' => '"ZY"', 'description' => 'Column 701'],
        ['input' => '703', 'expected' => '"AAA"', 'description' => 'Column 703'],
        ['input' => '52', 'expected' => '"AZ"', 'description' => 'Column 52'],
    ],
    'add-digits' => [
        ['input' => '38', 'expected' => '2', 'description' => '3+8=11, 1+1=2'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1', 'expected' => '1', 'description' => 'Single digit'],
        ['input' => '99', 'expected' => '9', 'description' => '9+9=18, 1+8=9'],
        ['input' => '9999', 'expected' => '9', 'description' => 'All nines'],
    ],
    'ugly-number' => [
        ['input' => '6', 'expected' => 'true', 'description' => '6 = 2 * 3'],
        ['input' => '1', 'expected' => 'true', 'description' => '1 is ugly'],
        ['input' => '14', 'expected' => 'false', 'description' => '14 = 2 * 7'],
        ['input' => '8', 'expected' => 'true', 'description' => '8 = 2^3'],
        ['input' => '2147483647', 'expected' => 'false', 'description' => 'Max int'],
    ],
    'missing-number' => [
        ['input' => '[3,0,1]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[0,1]', 'expected' => '2', 'description' => 'Missing last'],
        ['input' => '[9,6,4,2,3,5,7,0,1]', 'expected' => '8', 'description' => 'Missing 8'],
        ['input' => '[0]', 'expected' => '1', 'description' => 'Single element'],
        ['input' => '[1]', 'expected' => '0', 'description' => 'Missing zero'],
    ],
    'happy-number' => [
        ['input' => '19', 'expected' => 'true', 'description' => 'Is happy'],
        ['input' => '2', 'expected' => 'false', 'description' => 'Not happy'],
        ['input' => '1', 'expected' => 'true', 'description' => 'Trivial happy'],
        ['input' => '7', 'expected' => 'true', 'description' => 'Happy chain'],
        ['input' => '4', 'expected' => 'false', 'description' => 'Cycle chain'],
    ],
    'count-primes' => [
        ['input' => '10', 'expected' => '4', 'description' => '4 primes below 10'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1', 'expected' => '0', 'description' => 'No primes below 1'],
        ['input' => '2', 'expected' => '0', 'description' => 'No primes below 2'],
        ['input' => '100', 'expected' => '25', 'description' => '25 primes below 100'],
    ],
    'roman-to-integer' => [
        ['input' => '"III"', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '"IV"', 'expected' => '4', 'description' => 'Subtractive'],
        ['input' => '"IX"', 'expected' => '9', 'description' => 'Subtractive IX'],
        ['input' => '"LVIII"', 'expected' => '58', 'description' => 'Complex case'],
        ['input' => '"MCMXCIV"', 'expected' => '1994', 'description' => 'Large number'],
    ],
    'integer-to-roman' => [
        ['input' => '3', 'expected' => '"III"', 'description' => 'Basic case'],
        ['input' => '4', 'expected' => '"IV"', 'description' => 'Subtractive'],
        ['input' => '9', 'expected' => '"IX"', 'description' => 'Subtractive IX'],
        ['input' => '58', 'expected' => '"LVIII"', 'description' => 'Complex case'],
        ['input' => '1994', 'expected' => '"MCMXCIV"', 'description' => 'Large number'],
    ],
    'number-of-digit-one' => [
        ['input' => '13', 'expected' => '6', 'description' => '1,10,11,12,13'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero'],
        ['input' => '1', 'expected' => '1', 'description' => 'One'],
        ['input' => '100', 'expected' => '21', 'description' => '100 has 21 ones'],
        ['input' => '99', 'expected' => '20', 'description' => '99 has 20 ones'],
    ],
    'water-and-jug-problem' => [
        ['input' => '3\n5\n4', 'expected' => 'true', 'description' => 'Can measure 4'],
        ['input' => '2\n6\n5', 'expected' => 'false', 'description' => 'Cannot measure 5'],
        ['input' => '1\n2\n3', 'expected' => 'true', 'description' => 'Sum of jugs'],
        ['input' => '5\n5\n5', 'expected' => 'true', 'description' => 'Same size'],
        ['input' => '1\n1\n2', 'expected' => 'true', 'description' => 'Two 1-jugs'],
    ],
    'pointers' => [
        ['input' => '[1,0,-1,0,-2,2]\n0', 'expected' => '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]', 'description' => '4sum basic'],
        ['input' => '[2,2,2,2,2]\n8', 'expected' => '[[2,2,2,2]]', 'description' => 'All same'],
        ['input' => '[1,2,3,4,5]\n10', 'expected' => '[[1,2,3,4]]', 'description' => 'No solution'],
        ['input' => '[0,0,0]\n0', 'expected' => '[[0,0,0,0]]', 'description' => 'All zeros'],
        ['input' => '[-3,-2,-1,0,0,1,2,3]\n0', 'expected' => '[[-3,-2,2,3],[-3,-1,1,3],[-3,0,0,3],[-3,0,1,2],[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]', 'description' => 'Multiple solutions'],
    ],
    'combination-sum' => [
        ['input' => '[2,3,6,7]\n7', 'expected' => '[[2,2,3],[7]]', 'description' => 'Basic case'],
        ['input' => '[2,3,5]\n8', 'expected' => '[[2,2,2,2],[2,3,3],[3,5]]', 'description' => 'Multiple combos'],
        ['input' => '[2]\n1', 'expected' => '[]', 'description' => 'No solution'],
        ['input' => '[1]\n1', 'expected' => '[[1]]', 'description' => 'Single element'],
        ['input' => '[1]\n7', 'expected' => '[[1,1,1,1,1,1,1]]', 'description' => 'All ones'],
    ],
    'combination-sum-ii' => [
        ['input' => '[10,1,2,7,6,1,5]\n8', 'expected' => '[[1,1,6],[1,2,5],[1,7],[2,6]]', 'description' => 'Basic case'],
        ['input' => '[2,5,2,1,2]\n5', 'expected' => '[[1,2,2],[5]]', 'description' => 'With duplicates'],
        ['input' => '[1]\n1', 'expected' => '[[1]]', 'description' => 'Single element'],
        ['input' => '[1]\n2', 'expected' => '[]', 'description' => 'No solution'],
    ],
    'permutations' => [
        ['input' => '[1,2,3]', 'expected' => '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]', 'description' => 'Three elements'],
        ['input' => '[0,1]', 'expected' => '[[0,1],[1,0]]', 'description' => 'Two elements'],
        ['input' => '[1]', 'expected' => '[[1]]', 'description' => 'Single element'],
    ],
    'permutations-ii' => [
        ['input' => '[1,1,2]', 'expected' => '[[1,1,2],[1,2,1],[2,1,1]]', 'description' => 'With duplicates'],
        ['input' => '[1,2,3]', 'expected' => '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]', 'description' => 'No duplicates'],
        ['input' => '[1]', 'expected' => '[[1]]', 'description' => 'Single element'],
    ],
    'combination-sum-iii' => [
        ['input' => 'k = 3\nn = 7', 'expected' => '[[1,2,4]]', 'description' => 'Basic case'],
        ['input' => 'k = 3\nn = 9', 'expected' => '[[1,2,6],[1,3,5],[2,3,4]]', 'description' => 'Multiple solutions'],
        ['input' => 'k = 4\nn = 1', 'expected' => '[]', 'description' => 'Impossible'],
        ['input' => 'k = 9\nn = 45', 'expected' => '[[1,2,3,4,5,6,7,8,9]]', 'description' => 'All digits'],
    ],
    'subset-sum' => [
        ['input' => '[1,2,3,5]\n8', 'expected' => 'true', 'description' => 'Can form 8'],
        ['input' => '[1,2,3,5]\n4', 'expected' => 'false', 'description' => 'Cannot form 4'],
        ['input' => '[0]', 'expected' => 'true', 'description' => 'Zero subset'],
        ['input' => '[100]\n100', 'expected' => 'true', 'description' => 'Exact match'],
        ['input' => '[]\n0', 'expected' => 'true', 'description' => 'Empty set sums to 0'],
    ],
    'word-search-ii' => [
        ['input' => '[["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]]\n["oath","pea","eat","rain"]', 'expected' => '["eat","oath"]', 'description' => 'Basic case'],
        ['input' => '[["a","b"],["c","d"]]\n["abcb"]', 'expected' => '[]', 'description' => 'No words found'],
        ['input' => '[["a"]]\n["a"]', 'expected' => '["a"]', 'description' => 'Single cell board'],
    ],
    'binary-tree-inorder-traversal' => [
        ['input' => '[1,null,2,3]', 'expected' => '[1,3,2]', 'description' => 'Basic case'],
        ['input' => '[]', 'expected' => '[]', 'description' => 'Empty tree'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single node'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[4,2,5,1,3]', 'description' => 'Full tree'],
    ],
    'binary-tree-preorder-traversal' => [
        ['input' => '[1,null,2,3]', 'expected' => '[1,2,3]', 'description' => 'Basic case'],
        ['input' => '[]', 'expected' => '[]', 'description' => 'Empty tree'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single node'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[1,2,4,5,3]', 'description' => 'Full tree'],
    ],
    'binary-tree-postorder-traversal' => [
        ['input' => '[1,null,2,3]', 'expected' => '[3,2,1]', 'description' => 'Basic case'],
        ['input' => '[]', 'expected' => '[]', 'description' => 'Empty tree'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single node'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[4,5,2,3,1]', 'description' => 'Full tree'],
    ],
    'kth-smallest-element-in-a-bst' => [
        ['input' => '[3,1,4,null,2]\nk = 1', 'expected' => '1', 'description' => 'Smallest'],
        ['input' => '[5,3,6,2,4,null,null,1]\nk = 3', 'expected' => '3', 'description' => 'Middle k'],
        ['input' => '[1]\nk = 1', 'expected' => '1', 'description' => 'Single node'],
        ['input' => '[2,1,3]\nk = 2', 'expected' => '2', 'description' => 'Second smallest'],
    ],
    'count-complete-tree-nodes' => [
        ['input' => '[1,2,3,4,5,6]', 'expected' => '6', 'description' => 'Complete tree'],
        ['input' => '[]', 'expected' => '0', 'description' => 'Empty tree'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single node'],
        ['input' => '[1,2,3,4]', 'expected' => '4', 'description' => 'Almost complete'],
    ],
    'invert-binary-tree' => [
        ['input' => '[4,2,7,1,3,6,9]', 'expected' => '[4,7,2,9,6,3,1]', 'description' => 'Basic case'],
        ['input' => '[2,1,3]', 'expected' => '[2,3,1]', 'description' => 'Three nodes'],
        ['input' => '[]', 'expected' => '[]', 'description' => 'Empty tree'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single node'],
    ],
    'maximum-depth-of-binary-tree' => [
        ['input' => '[3,9,20,null,null,15,7]', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '[1,null,2]', 'expected' => '2', 'description' => 'Right skewed'],
        ['input' => '[1]', 'expected' => '1', 'description' => 'Single node'],
        ['input' => '[]', 'expected' => '0', 'description' => 'Empty tree'],
    ],
    'same-tree' => [
        ['input' => '[1,2,3]\n[1,2,3]', 'expected' => 'true', 'description' => 'Same trees'],
        ['input' => '[1,2]\n[1,null,2]', 'expected' => 'false', 'description' => 'Different structure'],
        ['input' => '[1,2,1]\n[1,1,2]', 'expected' => 'false', 'description' => 'Different values'],
        ['input' => '[]\n[]', 'expected' => 'true', 'description' => 'Both empty'],
        ['input' => '[1]\n[]', 'expected' => 'false', 'description' => 'One empty'],
    ],
    'symmetric-tree' => [
        ['input' => '[1,2,2,3,4,4,3]', 'expected' => 'true', 'description' => 'Symmetric'],
        ['input' => '[1,2,2,null,3,null,3]', 'expected' => 'false', 'description' => 'Not symmetric'],
        ['input' => '[1]', 'expected' => 'true', 'description' => 'Single node'],
        ['input' => '[]', 'expected' => 'true', 'description' => 'Empty tree'],
        ['input' => '[1,2,2,3,4,4,3,5,6,7,8,8,7,6,5]', 'expected' => 'true', 'description' => 'Deep symmetric'],
    ],
    'subtree-of-another-tree' => [
        ['input' => '[3,4,5,1,2]\n[4,1,2]', 'expected' => 'true', 'description' => 'Is subtree'],
        ['input' => '[3,4,5,1,2,null,null,null,null,0]\n[4,1,2]', 'expected' => 'false', 'description' => 'Not subtree'],
        ['input' => '[1]\n[1]', 'expected' => 'true', 'description' => 'Same single node'],
        ['input' => '[1,2,3]\n[2]', 'expected' => 'true', 'description' => 'Partial match'],
    ],
    'average-of-levels-in-binary-tree' => [
        ['input' => '[3,9,20,null,null,15,7]', 'expected' => '[3.0,14.5,11.0]', 'description' => 'Basic case'],
        ['input' => '[1]', 'expected' => '[1.0]', 'description' => 'Single node'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[1.0,2.5,4.5]', 'description' => 'Full tree'],
    ],
    'merge-sorted-array' => [
        ['input' => '[1,2,3,0,0,0]\n3\n[2,5,6]\n3', 'expected' => '[1,2,2,3,5,6]', 'description' => 'Basic merge'],
        ['input' => '[1]\n1\n[]\n0', 'expected' => '[1]', 'description' => 'Second empty'],
        ['input' => '[0]\n0\n[1]\n1', 'expected' => '[1]', 'description' => 'First empty'],
        ['input' => '[2,0]\n1\n[1]\n1', 'expected' => '[1,2]', 'description' => 'Two elements'],
        ['input' => '[4,5,6,0,0,0]\n3\n[1,2,3]\n3', 'expected' => '[1,2,3,4,5,6]', 'description' => 'All different'],
    ],
    'binary-search' => [
        ['input' => '[-1,0,3,5,9,12]\n9', 'expected' => '4', 'description' => 'Found'],
        ['input' => '[-1,0,3,5,9,12]\n2', 'expected' => '-1', 'description' => 'Not found'],
        ['input' => '[5]\n5', 'expected' => '0', 'description' => 'Single element found'],
        ['input' => '[5]\n-5', 'expected' => '-1', 'description' => 'Single element not found'],
        ['input' => '[-1,0,2,4,6,8]\n4', 'expected' => '3', 'description' => 'Middle element'],
    ],
    'first-bad-version' => [
        ['input' => '5\n4', 'expected' => '4', 'description' => 'Bad at 4'],
        ['input' => '1\n1', 'expected' => '1', 'description' => 'First is bad'],
        ['input' => '3\n2', 'expected' => '2', 'description' => 'Middle is bad'],
        ['input' => '100\n1', 'expected' => '1', 'description' => 'First is bad large range'],
        ['input' => '2147483647\n2147483647', 'expected' => '2147483647', 'description' => 'Last is bad'],
    ],
    'guess-number-higher-or-lower' => [
        ['input' => '10\n6', 'expected' => '6', 'description' => 'Guess 6'],
        ['input' => '1\n1', 'expected' => '1', 'description' => 'Guess 1'],
        ['input' => '2\n1', 'expected' => '1', 'description' => 'Guess first'],
        ['input' => '100\n50', 'expected' => '50', 'description' => 'Middle guess'],
    ],
    'arranging-coins' => [
        ['input' => '5', 'expected' => '2', 'description' => 'Complete 2 rows'],
        ['input' => '8', 'expected' => '3', 'description' => 'Complete 3 rows'],
        ['input' => '1', 'expected' => '1', 'description' => 'One coin'],
        ['input' => '0', 'expected' => '0', 'description' => 'Zero coins'],
        ['input' => '2147483647', 'expected' => '65535', 'description' => 'Large number'],
    ],
    'find-the-duplicate-number' => [
        ['input' => '[1,3,4,2,2]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[3,1,3,4,2]', 'expected' => '3', 'description' => 'Another duplicate'],
        ['input' => '[1,1]', 'expected' => '1', 'description' => 'Two same'],
        ['input' => '[1,2,2]', 'expected' => '2', 'description' => 'Last duplicate'],
        ['input' => '[2,5,9,6,9,3,8,9,7,1]', 'expected' => '9', 'description' => 'Multiple occurrences'],
    ],
    'candy' => [
        ['input' => '[1,0,2]', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '[1,2,2]', 'expected' => '4', 'description' => 'Equal neighbors'],
        ['input' => '[1,3,2,2,1]', 'expected' => '7', 'description' => 'Peak in middle'],
        ['input' => '[1,2,3,4,5]', 'expected' => '15', 'description' => 'Strictly increasing'],
        ['input' => '[5,4,3,2,1]', 'expected' => '15', 'description' => 'Strictly decreasing'],
    ],
    'h-index' => [
        ['input' => '[3,0,6,1,5]', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '[1,3,1]', 'expected' => '1', 'description' => 'Low h-index'],
        ['input' => '[100]', 'expected' => '1', 'description' => 'Single paper'],
        ['input' => '[0,0,0]', 'expected' => '0', 'description' => 'All zeros'],
        ['input' => '[1,1,1,1,1]', 'expected' => '1', 'description' => 'All ones'],
    ],
    'max-points-on-a-line' => [
        ['input' => '[[1,1],[2,2],[3,3]]', 'expected' => '3', 'description' => 'Collinear'],
        ['input' => '[[1,1],[3,2],[5,3],[4,1],[2,3],[1,4]]', 'expected' => '4', 'description' => 'Four on line'],
        ['input' => '[[0,0]]', 'expected' => '1', 'description' => 'Single point'],
        ['input' => '[[0,0],[1,1]]', 'expected' => '2', 'description' => 'Two points'],
        ['input' => '[[1,1],[2,2],[3,4],[4,5],[5,6],[7,7]]', 'expected' => '3', 'description' => 'Multiple slopes'],
    ],
    'minimum-path-sum' => [
        ['input' => '[[1,3,1],[1,5,1],[4,2,1]]', 'expected' => '7', 'description' => 'Basic case'],
        ['input' => '[[1,2,3],[4,5,6]]', 'expected' => '12', 'description' => '2x3 grid'],
        ['input' => '[[1]]', 'expected' => '1', 'description' => '1x1 grid'],
        ['input' => '[[1,2],[1,1]]', 'expected' => '3', 'description' => '2x2 grid'],
    ],
    'unique-paths' => [
        ['input' => 'm = 3\nn = 7', 'expected' => '28', 'description' => 'Basic case'],
        ['input' => 'm = 3\nn = 2', 'expected' => '3', 'description' => 'Small grid'],
        ['input' => 'm = 1\nn = 1', 'expected' => '1', 'description' => '1x1 grid'],
        ['input' => 'm = 2\nn = 2', 'expected' => '2', 'description' => '2x2 grid'],
        ['input' => 'm = 5\nn = 5', 'expected' => '70', 'description' => '5x5 grid'],
    ],
    'set-matrix-zeroes' => [
        ['input' => '[[1,1,1],[1,0,1],[1,1,1]]', 'expected' => '[[1,0,1],[0,0,0],[1,0,1]]', 'description' => 'Basic case'],
        ['input' => '[[0,1,2,0],[3,4,5,2],[1,3,1,5]]', 'expected' => '[[0,0,0,0],[0,4,5,0],[0,3,1,0]]', 'description' => 'Multiple zeros'],
        ['input' => '[[1]]', 'expected' => '[[1]]', 'description' => 'Single cell'],
        ['input' => '[[0]]', 'expected' => '[[0]]', 'description' => 'Single zero'],
    ],
    'spiral-matrix-ii' => [
        ['input' => '3', 'expected' => '[[1,2,3],[8,9,4],[7,6,5]]', 'description' => 'n=3'],
        ['input' => '1', 'expected' => '[[1]]', 'description' => 'n=1'],
        ['input' => '2', 'expected' => '[[1,2],[4,3]]', 'description' => 'n=2'],
        ['input' => '4', 'expected' => '[[1,2,3,4],[12,13,14,5],[11,16,15,6],[10,9,8,7]]', 'description' => 'n=4'],
    ],
    'insert-interval' => [
        ['input' => '[[1,3],[6,9]]\n[2,5]', 'expected' => '[[1,5],[6,9]]', 'description' => 'Overlapping'],
        ['input' => '[[1,2],[3,5],[6,7],[8,10],[12,16]]\n[4,8]', 'expected' => '[[1,2],[3,10],[12,16]]', 'description' => 'Merge multiple'],
        ['input' => '[]\n[5,7]', 'expected' => '[[5,7]]', 'description' => 'Empty intervals'],
        ['input' => '[[1,5]]\n[2,3]', 'expected' => '[[1,5]]', 'description' => 'Inside existing'],
        ['input' => '[[1,5]]\n[6,8]', 'expected' => '[[1,5],[6,8]]', 'description' => 'No overlap'],
    ],
    'non-overlapping-intervals' => [
        ['input' => '[[1,2],[2,3],[3,4],[1,3]]', 'expected' => '1', 'description' => 'Remove one'],
        ['input' => '[[1,2],[1,2],[1,2]]', 'expected' => '2', 'description' => 'All overlap'],
        ['input' => '[[1,2],[2,3]]', 'expected' => '0', 'description' => 'No overlap'],
        ['input' => '[[1,2]]', 'expected' => '0', 'description' => 'Single interval'],
    ],
    'meeting-rooms' => [
        ['input' => '[[0,30],[5,10],[15,20]]', 'expected' => 'false', 'description' => 'Overlapping'],
        ['input' => '[[7,10],[2,4]]', 'expected' => 'true', 'description' => 'No overlap'],
        ['input' => '[[0,10]]', 'expected' => 'true', 'description' => 'Single meeting'],
        ['input' => '[[1,2],[3,4],[5,6]]', 'expected' => 'true', 'description' => 'Three non-overlapping'],
    ],
    'meeting-rooms-ii' => [
        ['input' => '[[0,30],[5,10],[15,20]]', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '[[7,10],[2,4]]', 'expected' => '1', 'description' => 'No overlap'],
        ['input' => '[[1,3],[2,4],[6,8]]', 'expected' => '2', 'description' => 'Two concurrent'],
        ['input' => '[[1,2],[2,3],[3,4]]', 'expected' => '1', 'description' => 'Sequential'],
    ],
    'task-scheduler' => [
        ['input' => '["A","A","A","B","B","B"]\nn = 2', 'expected' => '8', 'description' => 'Basic case'],
        ['input' => '["A","A","A","B","B","B"]\nn = 0', 'expected' => '6', 'description' => 'No cooldown'],
        ['input' => '["A","A","A","A","A","A"]\nn = 2', 'expected' => '16', 'description' => 'Single task type'],
        ['input' => '["A","B"]\nn = 2', 'expected' => '5', 'description' => 'Two tasks with long cooldown'],
    ],
    'gas-station' => [
        ['input' => '[1,2,3,4,5]\n[3,4,5,1,2]', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '[2,3,4]\n[3,4,3]', 'expected' => '-1', 'description' => 'Impossible'],
        ['input' => '[5]\n[4]', 'expected' => '0', 'description' => 'Single station'],
        ['input' => '[1,2,3,4,5]\n[2,3,4,5,1]', 'expected' => '0', 'description' => 'Start at 0'],
        ['input' => '[3,1,1]\n[1,2,2]', 'expected' => '0', 'description' => 'Tight margin'],
    ],
    'hand-of-straights' => [
        ['input' => '[1,2,3,6,2,3,4,7,8]\n3', 'expected' => 'true', 'description' => 'Basic case'],
        ['input' => '[1,2,3,4,5]\n4', 'expected' => 'false', 'description' => 'Not enough for group'],
        ['input' => '[1,1,2,2,3,3]\n2', 'expected' => 'true', 'description' => 'Pairs'],
        ['input' => '[1,2,3,4,5,6]\n3', 'expected' => 'true', 'description' => 'Two groups'],
    ],
    'reorganize-string' => [
        ['input' => '"aab"', 'expected' => '"aba"', 'description' => 'Basic case'],
        ['input' => '"aaab"', 'expected' => '""', 'description' => 'Impossible'],
        ['input' => '"aaabb"', 'expected' => '"ababa"', 'description' => 'Five chars'],
        ['input' => '"aabbcc"', 'expected' => '"abcabc"', 'description' => 'Three pairs'],
        ['input' => '"a"', 'expected' => '"a"', 'description' => 'Single char'],
    ],
    'wiggle-sort' => [
        ['input' => '[3,5,2,1,6,4]', 'expected' => '[3,5,1,6,2,4]', 'description' => 'Basic case'],
        ['input' => '[1,2,3,4,5]', 'expected' => '[1,3,2,5,4]', 'description' => 'Sorted array'],
        ['input' => '[1,1,1,1]', 'expected' => '[1,1,1,1]', 'description' => 'All same'],
        ['input' => '[1,5,1,1,6,4]', 'expected' => '[1,5,1,6,1,4]', 'description' => 'With duplicates'],
    ],
    'wiggle-sort-ii' => [
        ['input' => '[1,5,1,1,6,4]', 'expected' => '[1,6,1,5,1,4]', 'description' => 'Basic case'],
        ['input' => '[1,3,2,2,3,1]', 'expected' => '[2,3,1,3,1,2]', 'description' => 'Sorted result'],
        ['input' => '[1]', 'expected' => '[1]', 'description' => 'Single element'],
        ['input' => '[1,1]', 'expected' => '[1,1]', 'description' => 'Two elements'],
    ],
    'maximum-swap' => [
        ['input' => '2736', 'expected' => '7236', 'description' => 'Basic swap'],
        ['input' => '9973', 'expected' => '9973', 'description' => 'Already maximum'],
        ['input' => '1', 'expected' => '1', 'description' => 'Single digit'],
        ['input' => '10', 'expected' => '10', 'description' => 'Two digits no swap'],
        ['input' => '98368', 'expected' => '98863', 'description' => 'Complex swap'],
    ],
    'next-closest-time' => [
        ['input' => '"19:34"', 'expected' => '"19:39"', 'description' => 'Basic case'],
        ['input' => '"23:59"', 'expected' => '"22:22"', 'description' => 'Wrap around'],
        ['input' => '"00:00"', 'expected' => '"00:00"', 'description' => 'Midnight unique'],
        ['input' => '"13:55"', 'expected' => '"15:11"', 'description' => 'Different hours'],
    ],
    'stocks-problems' => [
        ['input' => '[7,1,5,3,6,4]', 'expected' => '5', 'description' => 'Basic buy-sell'],
        ['input' => '[7,6,4,3,1]', 'expected' => '0', 'description' => 'Always decreasing'],
        ['input' => '[1,2,3,4,5]', 'expected' => '4', 'description' => 'Linear increase'],
        ['input' => '[2,4,1]', 'expected' => '2', 'description' => 'Small profit'],
    ],
    'best-time-to-buy-and-sell-stock-ii' => [
        ['input' => '[7,1,5,3,6,4]', 'expected' => '7', 'description' => 'Multiple transactions'],
        ['input' => '[1,2,3,4,5]', 'expected' => '4', 'description' => 'Hold till end'],
        ['input' => '[7,6,4,3,1]', 'expected' => '0', 'description' => 'No profit'],
        ['input' => '[1,2]', 'expected' => '1', 'description' => 'Single transaction'],
    ],
    'sum-of-two-integers' => [
        ['input' => '1\n2', 'expected' => '3', 'description' => 'Simple add'],
        ['input' => '2\n3', 'expected' => '5', 'description' => 'Basic case'],
        ['input' => '-1\n1', 'expected' => '0', 'description' => 'Cancel out'],
        ['input' => '-1\n-1', 'expected' => '-2', 'description' => 'Both negative'],
        ['input' => '0\n0', 'expected' => '0', 'description' => 'Both zero'],
    ],
    'divide-two-integers' => [
        ['input' => '10\n3', 'expected' => '3', 'description' => 'Basic division'],
        ['input' => '7\n-2', 'expected' => '-3', 'description' => 'Negative divisor'],
        ['input' => '0\n1', 'expected' => '0', 'description' => 'Zero dividend'],
        ['input' => '1\n1', 'expected' => '1', 'description' => 'Same values'],
        ['input' => '-2147483648\n-1', 'expected' => '2147483647', 'description' => 'Overflow case'],
    ],
    'multiply-strings' => [
        ['input' => '"2"\n"3"', 'expected' => '"6"', 'description' => 'Basic case'],
        ['input' => '"123"\n"456"', 'expected' => '"56088"', 'description' => 'Large multiply'],
        ['input' => '"0"\n"0"', 'expected' => '"0"', 'description' => 'Zero times zero'],
        ['input' => '"9"\n"9"', 'expected' => '"81"', 'description' => 'Single digits'],
        ['input' => '"999"\n"999"', 'expected' => '"998001"', 'description' => 'Three digits'],
    ],
    'basic-calculator-ii' => [
        ['input' => '"3+2*2"', 'expected' => '7', 'description' => 'Order of ops'],
        ['input' => '" 3/2 "', 'expected' => '1', 'description' => 'Integer division'],
        ['input' => '" 3+5 / 2 "', 'expected' => '5', 'description' => 'Mixed ops'],
        ['input' => '"1+1"', 'expected' => '2', 'description' => 'Simple add'],
        ['input' => '"2-1"', 'expected' => '1', 'description' => 'Simple subtract'],
    ],
    'fraction-to-recurring-decimal' => [
        ['input' => '1\n2', 'expected' => '"0.5"', 'description' => 'Simple division'],
        ['input' => '2\n1', 'expected' => '"2"', 'description' => 'No decimal'],
        ['input' => '2\n3', 'expected' => '"0.(6)"', 'description' => 'Repeating'],
        ['input' => '1\n3', 'expected' => '"0.(3)"', 'description' => 'Single repeat'],
        ['input' => '1\n7', 'expected' => '"0.(142857)"', 'description' => 'Long repeat'],
    ],
    'maximal-square' => [
        ['input' => '[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', 'expected' => '4', 'description' => 'Basic case'],
        ['input' => '[["0","1"],["1","0"]]', 'expected' => '1', 'description' => 'No larger square'],
        ['input' => '[["0"]]', 'expected' => '0', 'description' => 'All zeros'],
        ['input' => '[["1"]]', 'expected' => '1', 'description' => 'Single one'],
        ['input' => '[["1","1"],["1","1"]]', 'expected' => '4', 'description' => '2x2 square'],
    ],
    'paint-house' => [
        ['input' => '[[17,2,17],[16,16,5],[14,3,19]]', 'expected' => '10', 'description' => 'Basic case'],
        ['input' => '[[7,6,2]]', 'expected' => '2', 'description' => 'Single house'],
        ['input' => '[[2,1,3],[3,1,4],[4,2,3],[5,3,2]]', 'expected' => '6', 'description' => 'Four houses'],
    ],
];
