<?php

return [
    'reverse-string' => [
        ['input' => '["h","e","l","l","o"]', 'expected' => '["o","l","l","e","h"]', 'description' => 'Basic'],
        ['input' => '["H","a","n","n","a","h"]', 'expected' => '["h","a","n","n","a","H"]', 'description' => 'Mixed case'],
        ['input' => '["a"]', 'expected' => '["a"]', 'description' => 'Single char'],
        ['input' => '[" "," ","a"]', 'expected' => '["a"," "," "]', 'description' => 'With spaces'],
        ['input' => '["A","B","C","D"]', 'expected' => '["D","C","B","A"]', 'description' => 'Four chars'],
        ['input' => '["1","2","3","4","5"]', 'expected' => '["5","4","3","2","1"]', 'description' => 'Digits as chars'],
        ['input' => '["a","b","c","d","e","f"]', 'expected' => '["f","e","d","c","b","a"]', 'description' => 'Six chars'],
    ],
    'valid-parentheses' => [
        ['input' => '"()"', 'expected' => 'true', 'description' => 'Simple pair'],
        ['input' => '"()[]{}"', 'expected' => 'true', 'description' => 'Multiple types'],
        ['input' => '"(]"', 'expected' => 'false', 'description' => 'Mismatch close'],
        ['input' => '"(["', 'expected' => 'false', 'description' => 'Unclosed'],
        ['input' => '"{[]}"', 'expected' => 'true', 'description' => 'Nested'],
        ['input' => '"((()))"', 'expected' => 'true', 'description' => 'Deep nesting 3'],
        ['input' => '"([{()}])"', 'expected' => 'true', 'description' => 'All types nested'],
        ['input' => '"(("', 'expected' => 'false', 'description' => 'Only opens'],
        ['input' => '"())"', 'expected' => 'false', 'description' => 'Close without open'],
        ['input' => '"(("', 'expected' => 'false', 'description' => 'Extra open'],
    ],
    'valid-anagram' => [
        ['input' => 's = "anagram"\nt = "nagaram"', 'expected' => 'true', 'description' => 'Anagram'],
        ['input' => 's = "rat"\nt = "car"', 'expected' => 'false', 'description' => 'Not anagram'],
        ['input' => 's = "listen"\nt = "silent"', 'expected' => 'true', 'description' => 'Classic anagram'],
        ['input' => 's = "hello"\nt = "bello"', 'expected' => 'false', 'description' => 'Different first char'],
        ['input' => 's = "a"\nt = "a"', 'expected' => 'true', 'description' => 'Single char same'],
        ['input' => 's = "ab"\nt = "a"', 'expected' => 'false', 'description' => 'Different length'],
        ['input' => 's = ""\nt = ""', 'expected' => 'true', 'description' => 'Both empty'],
    ],
    'longest-substring-without-repeating-characters' => [
        ['input' => '"abcabcbb"', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => '"bbbbb"', 'expected' => '1', 'description' => 'All same'],
        ['input' => '"pwwkew"', 'expected' => '3', 'description' => 'Middle substring'],
        ['input' => '""', 'expected' => '0', 'description' => 'Empty string'],
        ['input' => '"a"', 'expected' => '1', 'description' => 'Single char'],
        ['input' => '"dvdf"', 'expected' => '3', 'description' => 'Hidden longer'],
    ],
    'group-anagrams' => [
        ['input' => '["eat","tea","tan","ate","nat","bat"]', 'expected' => '[["bat"],["nat","tan"],["ate","eat","tea"]]', 'description' => 'Basic grouping'],
        ['input' => '[""]', 'expected' => '[[""]]', 'description' => 'Empty string'],
        ['input' => '["a"]', 'expected' => '[["a"]]', 'description' => 'Single string'],
        ['input' => '["abc","bca","cab","xyz","zyx","yxz"]', 'expected' => '[["abc","bca","cab"],["xyz","zyx","yxz"]]', 'description' => 'Two groups of 3'],
    ],
    'minimum-window-substring' => [
        ['input' => '"ADOBECODEBANC"\n"ABC"', 'expected' => '"BANC"', 'description' => 'Basic case'],
        ['input' => '"a"\n"a"', 'expected' => '"a"', 'description' => 'Same single char'],
        ['input' => '"a"\n"aa"', 'expected' => '""', 'description' => 'Impossible'],
        ['input' => '"abc"\n"ac"', 'expected' => '"abc"', 'description' => 'Full string needed'],
        ['input' => '"aa"\n"aa"', 'expected' => '"aa"', 'description' => 'Exact match'],
        ['input' => '"ab"\n"b"', 'expected' => '"b"', 'description' => 'Single char at end'],
    ],
    'longest-common-subsequence' => [
        ['input' => 'text1 = "abcde"\ntext2 = "ace"', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => 'text1 = "abc"\ntext2 = "abc"', 'expected' => '3', 'description' => 'Same strings'],
        ['input' => 'text1 = "abc"\ntext2 = "def"', 'expected' => '0', 'description' => 'No common'],
        ['input' => 'text1 = ""\ntext2 = ""', 'expected' => '0', 'description' => 'Both empty'],
        ['input' => 'text1 = "abc"\ntext2 = ""', 'expected' => '0', 'description' => 'One empty'],
    ],
    'edit-distance' => [
        ['input' => 'word1 = "horse"\nword2 = "ros"', 'expected' => '3', 'description' => 'Basic case'],
        ['input' => 'word1 = "intention"\nword2 = "execution"', 'expected' => '5', 'description' => 'Complex case'],
        ['input' => 'word1 = ""\nword2 = ""', 'expected' => '0', 'description' => 'Both empty'],
        ['input' => 'word1 = "a"\nword2 = ""', 'expected' => '1', 'description' => 'Delete one'],
        ['input' => 'word1 = ""\nword2 = "a"', 'expected' => '1', 'description' => 'Insert one'],
        ['input' => 'word1 = "abc"\nword2 = "abc"', 'expected' => '0', 'description' => 'Same strings'],
    ],
    'word-break' => [
        ['input' => 's = "leetcode"\nwordDict = ["leet","code"]', 'expected' => 'true', 'description' => 'Basic case'],
        ['input' => 's = "applepenapple"\nwordDict = ["apple","pen"]', 'expected' => 'true', 'description' => 'Repeated word'],
        ['input' => 's = "catsandog"\nwordDict = ["cats","dog","sand","and","cat"]', 'expected' => 'false', 'description' => 'No valid segmentation'],
        ['input' => 's = "a"\nwordDict = ["a"]', 'expected' => 'true', 'description' => 'Single char match'],
        ['input' => 's = "ab"\nwordDict = ["a","b"]', 'expected' => 'true', 'description' => 'Two single chars'],
        ['input' => 's = "ab"\nwordDict = ["c"]', 'expected' => 'false', 'description' => 'No match at all'],
    ],
    'decode-ways' => [
        ['input' => '"12"', 'expected' => '2', 'description' => 'Basic case'],
        ['input' => '"226"', 'expected' => '3', 'description' => 'Multiple ways'],
        ['input' => '"06"', 'expected' => '0', 'description' => 'Invalid leading zero'],
        ['input' => '"10"', 'expected' => '1', 'description' => 'Must use 10'],
        ['input' => '"27"', 'expected' => '1', 'description' => 'Only one way'],
        ['input' => '"11106"', 'expected' => '2', 'description' => 'Complex case'],
        ['input' => '"1"', 'expected' => '1', 'description' => 'Single digit'],
    ],
    'text-justification' => [
        ['input' => 'words = ["This","is","an","example","of","text","justification."]\nmaxWidth = 16', 'expected' => '["This    is    an","example  of text","justification.  "]', 'description' => 'Basic case'],
        ['input' => 'words = ["What","must","be","acknowledgment","shall","be"]\nmaxWidth = 16', 'expected' => '["What   must   be","acknowledgment  ","shall be        "]', 'description' => 'Multiple words'],
    ],
    'longest-palindromic-substring' => [
        ['input' => '"babad"', 'expected' => '"bab"', 'description' => 'Basic case'],
        ['input' => '"cbbd"', 'expected' => '"bb"', 'description' => 'Double char'],
        ['input' => '"a"', 'expected' => '"a"', 'description' => 'Single char'],
        ['input' => '"ac"', 'expected' => '"a"', 'description' => 'Two chars'],
        ['input' => '"racecar"', 'expected' => '"racecar"', 'description' => 'Full palindrome'],
    ],
    'palindromic-substrings' => [
        ['input' => '"abc"', 'expected' => '3', 'description' => 'All single chars'],
        ['input' => '"aaa"', 'expected' => '6', 'description' => 'All same'],
        ['input' => '"a"', 'expected' => '1', 'description' => 'Single char'],
        ['input' => '"ab"', 'expected' => '2', 'description' => 'Two chars'],
        ['input' => '"aba"', 'expected' => '4', 'description' => 'Odd palindrome'],
    ],
    'generate-parentheses' => [
        ['input' => '3', 'expected' => '["((()))","(()())","(())()","()(())","()()()"]', 'description' => 'n=3'],
        ['input' => '1', 'expected' => '["()"]', 'description' => 'n=1'],
        ['input' => '2', 'expected' => '["(())","()()"]', 'description' => 'n=2'],
    ],
    'letter-combinations-of-a-phone-number' => [
        ['input' => '"23"', 'expected' => '["ad","ae","af","bd","be","bf","cd","ce","cf"]', 'description' => 'Basic case'],
        ['input' => '""', 'expected' => '[]', 'description' => 'Empty input'],
        ['input' => '"2"', 'expected' => '["a","b","c"]', 'description' => 'Single digit'],
        ['input' => '"7"', 'expected' => '["p","q","r","s"]', 'description' => 'Digit 7 four letters'],
    ],
    'string-to-integer-atoi' => [
        ['input' => '"42"', 'expected' => '42', 'description' => 'Basic positive'],
        ['input' => '"   -42"', 'expected' => '-42', 'description' => 'Negative with spaces'],
        ['input' => '"4193 with words"', 'expected' => '4193', 'description' => 'Trailing words'],
        ['input' => '"words and 987"', 'expected' => '0', 'description' => 'Leading words'],
        ['input' => '"-91283472332"', 'expected' => '-2147483648', 'description' => 'Underflow clamped'],
    ],
    'implement-strstr' => [
        ['input' => '"hello"\n"ll"', 'expected' => '2', 'description' => 'Found'],
        ['input' => '"aaaaa"\n"bba"', 'expected' => '-1', 'description' => 'Not found'],
        ['input' => '""\n""', 'expected' => '0', 'description' => 'Both empty'],
        ['input' => '"a"\n"a"', 'expected' => '0', 'description' => 'Single match'],
        ['input' => '"mississippi"\n"issip"', 'expected' => '4', 'description' => 'Partial overlap'],
    ],
    'repeated-substring-pattern' => [
        ['input' => '"abab"', 'expected' => 'true', 'description' => 'Basic case'],
        ['input' => '"aba"', 'expected' => 'false', 'description' => 'Not repeating'],
        ['input' => '"abcabcabcabc"', 'expected' => 'true', 'description' => 'Repeated 4 times'],
        ['input' => '"a"', 'expected' => 'false', 'description' => 'Single char'],
        ['input' => '"ababba"', 'expected' => 'false', 'description' => 'Not a pattern'],
    ],
    'longest-common-prefix' => [
        ['input' => '["flower","flow","flight"]', 'expected' => '"fl"', 'description' => 'Basic case'],
        ['input' => '["dog","racecar","car"]', 'expected' => '""', 'description' => 'No common prefix'],
        ['input' => '["interstellar","internet","interval"]', 'expected' => '"inter"', 'description' => 'Common prefix'],
        ['input' => '["a"]', 'expected' => '"a"', 'description' => 'Single string'],
        ['input' => '["","b"]', 'expected' => '""', 'description' => 'Empty string'],
    ],
    'reverse-words-in-a-string' => [
        ['input' => '"the sky is blue"', 'expected' => '"blue is sky the"', 'description' => 'Basic case'],
        ['input' => '"  hello world  "', 'expected' => '"world hello"', 'description' => 'Extra spaces'],
        ['input' => '"a good   example"', 'expected' => '"example good a"', 'description' => 'Multiple spaces'],
        ['input' => '"  Bob    Loves  Alice  "', 'expected' => '"Alice Loves Bob"', 'description' => 'Mixed spaces'],
        ['input' => '"word"', 'expected' => '"word"', 'description' => 'Single word'],
    ],
    'excel-sheet-column-number' => [
        ['input' => '"A"', 'expected' => '1', 'description' => 'Single A'],
        ['input' => '"AB"', 'expected' => '28', 'description' => 'Two chars'],
        ['input' => '"ZY"', 'expected' => '701', 'description' => 'Two chars end'],
        ['input' => '"AAA"', 'expected' => '703', 'description' => 'Three As'],
        ['input' => '"FXSHRXW"', 'expected' => '2147483647', 'description' => 'Max int'],
    ],
    'zigzag-conversion' => [
        ['input' => '"PAYPALISHIRING"\n3', 'expected' => '"PAHNAPLSIIGYIR"', 'description' => '3 rows'],
        ['input' => '"PAYPALISHIRING"\n4', 'expected' => '"PINALSIGYAHRPI"', 'description' => '4 rows'],
        ['input' => '"A"\n1', 'expected' => '"A"', 'description' => 'Single row'],
        ['input' => '"AB"\n1', 'expected' => '"AB"', 'description' => 'Two chars one row'],
        ['input' => '"ABC"\n2', 'expected' => '"ACB"', 'description' => 'Two rows'],
    ],
    'longest-palindrome' => [
        ['input' => '"abccccdd"', 'expected' => '7', 'description' => 'Basic case'],
        ['input' => '"a"', 'expected' => '1', 'description' => 'Single char'],
        ['input' => '"aaaa"', 'expected' => '4', 'description' => 'All same'],
        ['input' => '"aaabbb"', 'expected' => '6', 'description' => 'Two pairs'],
        ['input' => '"aaabbbccc"', 'expected' => '9', 'description' => 'Three pairs'],
    ],
    'count-and-say' => [
        ['input' => '1', 'expected' => '"1"', 'description' => 'n=1'],
        ['input' => '2', 'expected' => '"11"', 'description' => 'n=2'],
        ['input' => '3', 'expected' => '"21"', 'description' => 'n=3'],
        ['input' => '4', 'expected' => '"1211"', 'description' => 'n=4'],
        ['input' => '5', 'expected' => '"111221"', 'description' => 'n=5'],
    ],
    'first-unique-character-in-a-string' => [
        ['input' => '"leetcode"', 'expected' => '0', 'description' => 'First char unique'],
        ['input' => '"loveleetcode"', 'expected' => '2', 'description' => 'Middle unique'],
        ['input' => '"aabb"', 'expected' => '-1', 'description' => 'No unique'],
        ['input' => '"a"', 'expected' => '0', 'description' => 'Single char'],
        ['input' => '"aadadaad"', 'expected' => '-1', 'description' => 'All duplicates'],
    ],
    'custom-sort-string' => [
        ['input' => '"cba"\n"abcd"', 'expected' => '"cbad"', 'description' => 'Basic case'],
        ['input' => '"cbafg"\n"abcd"', 'expected' => '"cbad"', 'description' => 'Partial order'],
        ['input' => '"z"\n"abc"', 'expected' => '"abc"', 'description' => 'No chars match'],
        ['input' => '"abc"\n"abc"', 'expected' => '"abc"', 'description' => 'Same order'],
        ['input' => '"cba"\n"aabbcc"', 'expected' => '"ccbbaa"', 'description' => 'All reversed'],
    ],
    'sort-characters-by-frequency' => [
        ['input' => '"tree"', 'expected' => '"eert"', 'description' => 'Basic case'],
        ['input' => '"cccaaa"', 'expected' => '"aaaccc"', 'description' => 'Tie broken by order'],
        ['input' => '"Aabb"', 'expected' => '"bbAa"', 'description' => 'Mixed case'],
        ['input' => '"a"', 'expected' => '"a"', 'description' => 'Single char'],
        ['input' => '"abab"', 'expected' => '"aabb"', 'description' => 'Equal freq'],
    ],
    'find-all-anagrams-in-a-string' => [
        ['input' => '"cbaebabacd"\n"abc"', 'expected' => '[0,6]', 'description' => 'Two anagrams'],
        ['input' => '"abab"\n"ab"', 'expected' => '[0,1,2]', 'description' => 'Overlapping'],
        ['input' => '"a"\n"a"', 'expected' => '[0]', 'description' => 'Single match'],
        ['input' => '"abc"\n"def"', 'expected' => '[]', 'description' => 'No anagrams'],
        ['input' => '"aa"\n"bb"', 'expected' => '[]', 'description' => 'No match'],
    ],
    'rabin-karp' => [
        ['input' => '"sadbutsad"\n"sad"', 'expected' => '[0,6]', 'description' => 'Two occurrences'],
        ['input' => '"leetcode"\n"leeto"', 'expected' => '[]', 'description' => 'No match'],
        ['input' => '"a"\n"a"', 'expected' => '[0]', 'description' => 'Single match'],
        ['input' => '"aaa"\n"aa"', 'expected' => '[0,1]', 'description' => 'Overlapping'],
        ['input' => '"abcde"\n"cde"', 'expected' => '[2]', 'description' => 'At end'],
    ],
    'shortest-palindrome' => [
        ['input' => '"aacecaaa"', 'expected' => '"aaacecaaa"', 'description' => 'Basic case'],
        ['input' => '"abcd"', 'expected' => '"dcbabcd"', 'description' => 'No prefix palindrome'],
        ['input' => '"a"', 'expected' => '"a"', 'description' => 'Single char'],
        ['input' => '"aa"', 'expected' => '"aa"', 'description' => 'Already palindrome'],
        ['input' => '"aba"', 'expected' => '"aba"', 'description' => 'Odd palindrome'],
    ],
    'isomorphic-strings' => [
        ['input' => '"egg"\n"add"', 'expected' => 'true', 'description' => 'Isomorphic'],
        ['input' => '"foo"\n"bar"', 'expected' => 'false', 'description' => 'Not isomorphic'],
        ['input' => '"paper"\n"title"', 'expected' => 'true', 'description' => '5-char isomorphic'],
        ['input' => '"a"\n"b"', 'expected' => 'true', 'description' => 'Single char'],
        ['input' => '"ab"\n"aa"', 'expected' => 'false', 'description' => 'One-to-many'],
    ],
    'word-pattern' => [
        ['input' => '"abba"\n"dog cat cat dog"', 'expected' => 'true', 'description' => 'Basic case'],
        ['input' => '"abba"\n"dog cat cat fish"', 'expected' => 'false', 'description' => 'Pattern mismatch'],
        ['input' => '"aaaa"\n"dog cat cat dog"', 'expected' => 'false', 'description' => 'One-to-many'],
        ['input' => '"ab"\n"dog"', 'expected' => 'false', 'description' => 'Different length'],
        ['input' => '""\n""', 'expected' => 'true', 'description' => 'Both empty'],
    ],
    'sort-colors' => [
        ['input' => '[2,0,2,1,1,0]', 'expected' => '[0,0,1,1,2,2]', 'description' => 'Basic case'],
        ['input' => '[2,0,1]', 'expected' => '[0,1,2]', 'description' => 'Three elements'],
        ['input' => '[0]', 'expected' => '[0]', 'description' => 'Single element'],
        ['input' => '[1,1,1]', 'expected' => '[1,1,1]', 'description' => 'All same'],
        ['input' => '[2,2,2,0,0,1,1]', 'expected' => '[0,0,1,1,2,2,2]', 'description' => 'More whites'],
    ],
    'compare-version-numbers' => [
        ['input' => '"1.01"\n"1.001"', 'expected' => '0', 'description' => 'Equal with leading zeros'],
        ['input' => '"1.0"\n"1.0.0"', 'expected' => '0', 'description' => 'Different lengths'],
        ['input' => '"0.1"\n"1.1"', 'expected' => '-1', 'description' => 'Less than'],
        ['input' => '"1.0.1"\n"1"', 'expected' => '1', 'description' => 'Greater than'],
        ['input' => '"1"\n"1"', 'expected' => '0', 'description' => 'Same version'],
    ],
    'reorganize-string' => [
        ['input' => '"aab"', 'expected' => '"aba"', 'description' => 'Basic case'],
        ['input' => '"aaab"', 'expected' => '""', 'description' => 'Impossible'],
        ['input' => '"aaabb"', 'expected' => '"ababa"', 'description' => 'Five chars'],
        ['input' => '"aabbcc"', 'expected' => '"abcabc"', 'description' => 'Three pairs'],
        ['input' => '"a"', 'expected' => '"a"', 'description' => 'Single char'],
    ],
    'reorder-data-in-log-files' => [
        ['input' => '["dig1 8 1 5 1","let1 art can","dig2 3 6","let2 own kit dig","let3 art zero"]', 'expected' => '["let1 art can","let3 art zero","let2 own kit dig","dig1 8 1 5 1","dig2 3 6"]', 'description' => 'Mixed logs'],
        ['input' => '["a1 9 2 3 1","g1 act car","zo4 4 7","ab1 off key dog","a8 act zoo"]', 'expected' => '["g1 act car","a8 act zoo","ab1 off key dog","a1 9 2 3 1","zo4 4 7"]', 'description' => 'Letter then digit'],
        ['input' => '["a1 a2 a3"]', 'expected' => '["a1 a2 a3"]', 'description' => 'Single letter log'],
        ['input' => '["1 a 2 b"]', 'expected' => '["1 a 2 b"]', 'description' => 'Single digit log'],
    ],
    'greatest-common-divisor-of-strings' => [
        ['input' => '"ABCABC"\n"ABC"', 'expected' => '"ABC"', 'description' => 'Basic case'],
        ['input' => '"ABABAB"\n"ABAB"', 'expected' => '"AB"', 'description' => 'Shorter divisor'],
        ['input' => '"LEET"\n"CODE"', 'expected' => '""', 'description' => 'No common divisor'],
        ['input' => '"ABC"\n"ABC"', 'expected' => '"ABC"', 'description' => 'Same strings'],
        ['input' => '"AAAA"\n"AA"', 'expected' => '"AA"', 'description' => 'Multiple repeats'],
    ],
];
